- Dockerfile
This brings this repo inline with https://github.com/edx/front-end-cookie-cutter-application/blob/master/Dockerfile#L29 and enables `docker up` to work.
> Fix Docker start up.

- src/components/LoginForm/__snapshots__/LoginForm.test.jsx.snap
- src/components/LoginForm/index.jsx
This allows the 'enter' key to be used on any of the form elements to submit the login form. Visually looks exactly the same.
> Updates the Sign In button to a submit button

- src/data/actions/authentication.js
- src/data/actions/authentication.test.js
This was manifesting itself as two odd bugs - sometimes the email address
was not being loaded because the cookie could not be read, therefore the
dropdown was not being shown. It was also causing an issue where when logging
out the cookie wasn't actually removed since the path didnt match when
calling cookies.remove
> Forces all cookies to use path '/' for access from all pages

- .babelrc
This was resulting in a very odd bug in our prod builds where after
fetching the enterprise list this error would be displayed:
>"TypeError: Cannot set property 'getCurrentStack' of undefined"
As the react-spinners documentation points out:
> IMPORTANT: This package uses emotion. Remember to add the plugin to .babelrc
> react-spinners requires 'emotion' to be included as a babel plugin

- src/components/EnterpriseList/EnterpriseList.test.jsx
- src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap
- src/components/EnterpriseList/index.jsx
- src/containers/EnterpriseIndexPage/index.jsx
Unlike the admin dashboard, the enterprise list sits outside the `<App />` therefore
the call to getLocalUser() was never made and the user dropdown was not being shown
> Ensure the user is read from the cookie when loading the enterprise list

- config/webpack.dev.config.js
- src/data/services/EnterpriseDataApiService.js
- src/data/services/LmsApiService.js
- src/httpClient.js
When an API response returns an error with a status code of 401 (unauthorized) or 403 (forbidden), we should force logout the user so they return to the login page to reset their session.
> Dispatch logout action when API calls return 401 or 403 errors

- src/components/Header/index.jsx
- src/containers/Header/__snapshots__/Header.test.jsx.snap
- src/index.jsx
Currently, we do not enforce that the `/` route is a `PrivateRoute`. As such, we try to load the `EnterpriseList` which results in a 401 error. The `logout` action is properly dispatched to handle this but the redirect to the `Login` page does not work. 
By making the `/` route a `PrivateRoute`, we ensure that the login page will be shown if logged out.
Also, I updated the enterprise logo link in the `Header` to link to `/` so that clicking on the logo will go back to the `EnterpriseList` (which would redirect back to the dashboard page if there's only one enterprise the user has access to.
> Ensure / route is a PrivateRoute to force login

- src/components/Admin/Admin.scss
- src/containers/EnterpriseApp/index.jsx
- src/containers/ErrorPage/ErrorPage.test.jsx
- src/containers/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap
* In testing IE11 and Edge on Windows, the top 4 boxes on admin dashboard had no height. Removing `flex-direction: column;` fixes the issue so that the height of the boxes are consistent across browsers.
* `<ErrorPage>`'s `status` prop should be a number, but in the tests, we were passing in a string. Modified this and updated the snapshot so that we are actually testing that the `NotFoundPage` renders.
* We renamed `App` to `EnterpriseApp` but didn't update the name of the component within `EnterpriseApp/index.jsx`.
> Fix ErrorPage tests & IE11 CSS issue, rename EnterpriseApp

- package-lock.json
- package.json
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/containers/AdminPage/AdminPage.test.jsx
- src/containers/AdminPage/index.jsx
- src/data/reducers/courseEnrollments.js
- src/data/reducers/courseEnrollments.test.js
- src/index.scss
This also upgrades edx-bootstrap to 1.0.0 which includes bootstrap 4.0.0 rather than the 4 beta.
The bootstrap 4 beta had removed cursor:pointer on buttons, we no longer need to handle this ourselves.
> Adds error and loading state for CSV downloading

- config/webpack.dev.config.js
- src/config/index.js
We are getting warnings about the New Relic keys being `undefined` when building in the dev environment:
Since only the prod webpack config uses the New Relic plugin, we can safely remove the env vars from the dev webpack config as well as `src/config/index.js`.
> Remove new relic env vars from dev build

- src/components/CourseEnrollments/CourseEnrollments.test.jsx
- src/components/CourseEnrollments/index.jsx
- src/components/EnterpriseList/EnterpriseList.test.jsx
- src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap
- src/components/EnterpriseList/index.jsx
- src/components/TableWithPagination/TableWithPagination.test.jsx
- src/components/TableWithPagination/index.jsx
Adds client-side sorting to `TableWithPagination` to avoid making unnecessary API calls when there's only 1 page of table data.
Note that the sorting function being in `TableWithPagination` means it should be able to sort any type of data (e.g., strings, dates, numbers). The [`sortTableData` function](https://github.com/edx/edx-portal/compare/astankiewicz/client-table-sorting?expand=1#diff-499b0c7921fe2ca35e04265122d9da23R83) uses lodash's `orderBy` to simplify the sorting logic.
> Client-side sorting in TableWithPagination for page count < 1

- config/webpack.prod.config.js
While we were excluding the demoDataLoader.js file from our production bundle, it
was still being chunked so the the vendors~demoDataLoader.js chunk was being included
in the body and included faker.js which is unnecessary outside the demoDataLoader
This change now removes that chunking
> Removes demoDataLoader from chunking in our prod bundles

- src/components/TableWithPagination/index.jsx
The `.trim()` in `parseKeyValue` was left in there when it was meant to be removed. This is causing issues for sorting columns that are not strings.
> Remove .trim() in client-side sorting

- src/config/index.js
- src/utils.js
If some features are behind a feature flag (e.g., the collapsible cards), it's impossible to see and verify changes on stage and prod. This PR supports temporarily enabling one or more feature flags by passing a `features` URL query parameter. To have more than one feature enabled, simply put them in a comma-separated list:
```
http://localhost:1991/enterprise-slug/admin/learners?features=DASHBOARD_V2
http://localhost:1991/enterprise-slug/admin/learners?features=DASHBOARD_V2,OTHER_FEATURE
```
> Support temporarily enabling feature flags with query parameter

- src/components/Admin/index.jsx
- src/components/CompletedLearnersTable/index.jsx
- src/components/LearnerActivityTable/LearnerActivityTable.test.jsx
- src/components/LearnerActivityTable/__snapshots__/LearnerActivityTable.test.jsx.snap
- src/components/LearnerActivityTable/index.jsx
- src/components/TableComponent/index.jsx
- src/utils.js
This PR adds front-end functionality for Learner Activity cards. They include:
1. Active learners in past week.
2. Inactive learners in past week.
3. Inactive learners in past month.
Related enterprise-data PR: https://github.com/edx/edx-enterprise-data/pull/64
[ENT-1166](https://openedx.atlassian.net/browse/ENT-1166)
[ENT-1218](https://openedx.atlassian.net/browse/ENT-1218)
> Learner activity details

- src/components/EnterpriseList/EnterpriseList.test.jsx
Since the generic table refactor, the `EnterpriseList` component no longer has a `searchQuery` prop. We should remove the test for when the prop changes since it is no longer relevant.
> Remove irrelevant test in EnterpriseList

- src/components/NumberCard/index.jsx
NumberCards were not properly updating their route and instead adding appending their route to the existing querystring. This was introduced in https://github.com/edx/edx-portal/pull/70
> Fixes routing issue with NumberCards

- src/components/Admin/Admin.test.jsx
- src/components/Admin/AdminCards.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/DownloadCsvButton/index.jsx
- src/components/EnrolledLearnersForInactiveCoursesTable/EnrolledLearnersForInactiveCoursesTable.test.jsx
- src/components/EnrolledLearnersForInactiveCoursesTable/__snapshots__/EnrolledLearnersForInactiveCoursesTable.test.jsx.snap
- src/components/EnrolledLearnersForInactiveCoursesTable/index.jsx
- src/components/EnrollmentsTable/EnrollmentsTable.mocks.js
- src/components/LearnerActivityTable/index.jsx
- src/components/PastWeekPassedLearnersTable/PastWeekPassedLearnersTable.test.jsx
- src/components/PastWeekPassedLearnersTable/__snapshots__/PastWeekPassedLearnersTable.test.jsx.snap
- src/components/PastWeekPassedLearnersTable/index.jsx
- src/components/RegisteredLearnersTable/RegisteredLearnersTable.test.jsx
- src/components/RegisteredLearnersTable/index.jsx
- src/containers/AdminPage/index.jsx
- src/containers/DownloadCsvButton/DownloadCsvButton.test.jsx
- src/containers/LearnerActivityTable/index.jsx
- src/data/services/EnterpriseDataApiService.js
1. Ensures each card action table has an associated csv fetch method;
2. Refactors the `EnterpriseDataApiService` so that we don't have two methods (i.e., one for normal and one for csv) for every request; instead, supports passing a `csv` boolean flag to the fetch method for it to fetch the csv.
3. Refactors the logic around when the csv button is disabled:
- Disables whenever the table data is loading (to prevent accidentally downloading a csv while a different table is loading);
- Disables if there are no results in the table (no reason to let users download if there's no data to download).
4. Updates the `LearnerActivityTable` to clear it's associated Redux state whenever the `id` prop changes.
- This is necessary because this component is used for 3 of the card action tables. When …
> Ensure all card action tables have a CSV fetch method

- src/demo/rewireEnterpriseDataApiService.test.js
I noticed this test on `master` was failing after @mushtaqak merged his demo data changes. The reason why it was failing is because the `last_updated_date` was a string, but we were checking to verify it as a `Date` object. `last_updated_date` changed to be a string when I had Mushtaq add `.toString()` to the date as the last updated date wasn't showing in the UI otherwise.
Also, this test had the key `last_update_date`, not `last_updated_date`.
Still TBD how the test was passing on @mushtaqak branch.
> Fix failing test for demo data

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/DownloadCsvButton/index.jsx
- src/containers/DownloadCsvButton/index.jsx
Updates the `DownloadCsvButton` component to accept a `buttonLabel` prop such that the logic around the button label text is determined by the consuming component.
Before, the text displayed was dependent on the `actionSlug` URL parameter which doesn't make sense to couple in a generic download csv button component.
> Minor DownloadCsvButton refactor

- src/components/Admin/index.jsx
I noticed for one of the card actions, the csv button was always disabled. This is happening because the logic for whether the csv button should be disabled checks to see if there is any table data. It couldn't find the table data in question because the key it uses to do the lookup doesn't match the table id.
Currently, the table id and csv button id must be the same. In this case, the csv button id was different than the table id. This PR updates the table id so that the logic for disabling the CSV button works correctly for the "top active learners" report.
> Fixing table id for learners-active-week

- src/demo/rewireEnterpriseDataApiService.test.js
An "unresolved promise rejection" warning was happening for the `fetchDashboardAnalytics` test in `rewireEnterpriseDataApiService.test.js` but the test was not actually failing, which is why we didn't catch it.
The reason for the error occurring was because the test in question was within a `describe` block but missing the nested `it` block. Adding the `it` block ensures that the test actually fails if the `expect`'s don't match without the "unresolved promise rejection" warning.
Also, I moved around the tests to:
* Add the `rewire()` call in the `beforeEach()`
* Remove unnecessary `describe` blocks.
> Fixing unresolved promise rejection

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/NumberCard/NumberCard.scss
- src/components/NumberCard/NumberCard.test.jsx
- src/components/NumberCard/__snapshots__/NumberCard.test.jsx.snap
- src/components/NumberCard/index.jsx
Right now, the click target is the just the icon to toggle the the expand/collapse of the `NumberCard` actions. This PR refactors the click target to make the entire details add-on clickable so it's easier to click.
> Update NumberCard details toggle button

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/CompletedLearnersTable/__snapshots__/CompletedLearnersTable.test.jsx.snap
- src/components/DownloadCsvButton/index.jsx
- src/components/EnrolledLearnersForInactiveCoursesTable/__snapshots__/EnrolledLearnersForInactiveCoursesTable.test.jsx.snap
- src/components/EnrolledLearnersTable/__snapshots__/EnrolledLearnersTable.test.jsx.snap
- src/components/EnrollmentsTable/__snapshots__/EnrollmentsTable.test.jsx.snap
- src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap
- src/components/EnterpriseList/index.jsx
- src/components/LearnerActivityTable/__snapshots__/LearnerActivityTable.test.jsx.snap
- src/components/RegisteredLearnersTable/__snapshots__/RegisteredLearnersTable.test.jsx.snap
- src/components/StatusAlert/index.jsx
- src/components/TableLoadingOverlay/index.jsx
- src/containers/EnterpriseApp/__snapshots__/EnterpriseApp.test.jsx.snap
- src/containers/EnterpriseApp/index.jsx
- src/containers/EnterpriseIndexPage/index.jsx
- src/containers/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap
- src/containers/ErrorPage/index.jsx
- src/containers/LogoutHandler/index.jsx
- src/index.jsx
In React, DOM/JSX elements must be nested under a single parent node. This usually leads to having unnecessary elements rendered to the DOM. For example, our `DownloadCsvButton` renders text next to an icon, so we need to wrap both the icon and the text in a `<span>`, e.g.
```jsx
<span>
<Icon {...props} />
This is an awesome button.
</span>
```
However, this results in rendering an unnecessary `<span>` in the DOM. Instead, we could use [`React.Fragment`](https://reactjs.org/docs/fragments.html) which allows you to group elements without rendering any unneeded elements to the DOM.
This PR goes through our components/containers to identify where using `React.Fragment` makes sense. FYI, because this changes the underlying structure of our DOM (i.e., removing elements), there are a fair …
> Use React.Fragment where relevant

- src/components/Admin/index.jsx
- src/components/StatusAlert/index.jsx
- src/components/TableComponent/index.jsx
The prop `iconClassName` is misleading as it should be an array of strings, not a single string. In this PR, I recommend renaming `iconClassName` to `iconClassNames` as well as simplifying the logic by defaulting this prop to an empty array.
> Rename iconClassName to iconClassNames in StatusAlert

- src/demo/rewireEnterpriseDataApiService.js
- src/demo/rewireEnterpriseDataApiService.test.js
We have 2 imports that are going up beyond the `src` direction, when it is not needed to get to the relevant files.
> Fix import paths to remove src

- config/webpack.dev.config.js
- config/webpack.prod.config.js
Currently, when running `npm run build` emits several warnings about `EnvironmentPlugin` environment variables being undefined:
This PR fixes these warnings by setting the default values of the environment variables to `null` instead of `undefined`.
> Fix EnvironmentPlugin warnings during production builds

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/NumberCard/__snapshots__/NumberCard.test.jsx.snap
- src/components/NumberCard/index.jsx
With the refactor of the `NumberCard` expand/collapse button, we're not setting the `buttonType` prop which causes the background to appear gray on Safari and Firefox.
This PR adds `buttonType="link"` to the button which resolves this issue. It also adds a hover/focus state of underline the text in the button which is better for a11y.
> Add buttonType prop to NumberCard details button

- README.md
- config/webpack.dev.config.js
- config/webpack.prod.config.js
This was confusing some folks attempting to use edx-portal as an example of how to do a frontend app.
> Remove outdated OAuth references from docs and settings.

- src/components/Admin/AdminCards.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Coupon/index.jsx
- src/components/CouponDetails/index.jsx
- src/components/NumberCard/NumberCard.scss
- src/components/NumberCard/NumberCard.test.jsx
- src/components/NumberCard/__snapshots__/NumberCard.test.jsx.snap
- src/components/NumberCard/index.jsx
This PR fixes the a11y of our collapsible components (i.e., `NumberCard`, `Coupon`, `CouponDetails`) by using the `aria-expanded` and `aria-controls` props where relevant.
Note that I needed to refactor the `Coupon` component such that the `CouponDetails` component is always rendered. The reason for this is the `aria-controls` prop in `Coupon` refers to an `id` which must already exist. Before, we would not render the `CouponDetails` until the `Coupon` was expanded so the `id` within `CouponDetails` would not exist, throwing an a11y error. Instead, I am adding the `.d-none` class to hide the `CouponDetails` until the `Coupon` is expanded, ensuring the `id` exists for `aria-controls`.
Also included in this PR is a minor style change to the `NumberCard` details toggle button such that the …
> Add aria-expanded and aria-controls props to collapsible components

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/CompletedLearnersTable/__snapshots__/CompletedLearnersTable.test.jsx.snap
- src/components/EnrolledLearnersForInactiveCoursesTable/__snapshots__/EnrolledLearnersForInactiveCoursesTable.test.jsx.snap
- src/components/EnrolledLearnersTable/__snapshots__/EnrolledLearnersTable.test.jsx.snap
- src/components/EnrollmentsTable/__snapshots__/EnrollmentsTable.test.jsx.snap
- src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap
- src/components/LearnerActivityTable/__snapshots__/LearnerActivityTable.test.jsx.snap
- src/components/LoadingMessage/index.jsx
- src/components/PastWeekPassedLearnersTable/__snapshots__/PastWeekPassedLearnersTable.test.jsx.snap
- src/components/RegisteredLearnersTable/__snapshots__/RegisteredLearnersTable.test.jsx.snap
- src/components/TableComponent/index.jsx
I noticed a few other places where we had unnecessary DOM wrapper elements:
- `<div>`'s with no other purpose as to wrap multiple elements. These were replaced with `<React.Fragment>`.
- `<span>`'s around text. These spans were removed and replaced with `<React.Fragment>` where needed.
This caused several snapshots to change, but confirmed that they are rendering the expected DOM nodes.
> Remove unnecessary DOM wrapper elements

- package-lock.json
- package.json
I deployed a [fix](https://github.com/edx/paragon/pull/359) for the Paragon `SearchField` component that resolves a UX issue regarding clearing a search. This PR upgrades Paragon in `edx-portal` to take advantage of that fix.
> Upgrade Paragon to 3.7.1 for SearchField fix

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/CodeManagement/index.jsx
- src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap
- src/components/EnterpriseList/index.jsx
- src/components/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap
- src/components/ErrorPage/index.jsx
- src/components/Footer/index.jsx
- src/components/Header/index.jsx
- src/components/Hero/index.jsx
- src/components/NotFoundPage/__snapshots__/NotFoundPage.test.jsx.snap
- src/components/NotFoundPage/index.jsx
- src/components/RequestCodesPage/index.jsx
- src/components/SupportPage/__snapshots__/SupportPage.test.jsx.snap
- src/components/SupportPage/index.jsx
- src/containers/EnterpriseApp/__snapshots__/EnterpriseApp.test.jsx.snap
- src/containers/Footer/__snapshots__/Footer.test.jsx.snap
- src/containers/Header/__snapshots__/Header.test.jsx.snap
By switching to `.container-fluid` instead of the current `.container`, our pages/header/footer will fill the entire screen instead of Bootstrap's responsive widths. This will make it simpler to implement the sidebar navigation.
> Refactor to use `.container-fluid` instead of `.container`

- package-lock.json
- package.json
- src/components/Admin/index.jsx
- src/components/CodeManagement/index.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/RequestCodesPage/index.jsx
- src/containers/AdminPage/index.jsx
- src/containers/CodeManagementPage/index.jsx
- src/containers/EnterpriseApp/index.jsx
- src/containers/RequestCodesPage/index.jsx
Refactors `this.props.fetchPortalConfiguration(enterpriseSlug)` to be called in `EnterpriseApp` instead of within each individual page.
Additionally, the issue I was having with the empty `SupportPage` & `NotFoundPage` had to do with using `<React.Fragment>` inside of react-router's `<Switch>` which turns out is not currently supported (see https://github.com/ReactTraining/react-router/issues/5785 for more details). Instead of using a fragment, we can just output an array of the routes to include if the `CODE_MANAGEMENT` feature flag is truthy. 
Note that we currently don't see this issue on stage/prod until you enable the `CODE_MANAGEMENT` feature flag in the URL.
I also removed my `node_modules` folder & `package-lock.json` to do a fresh install of all packages, which resulted in a …
> Refactor fetchPortalConfiguration into EnterpriseApp

- src/components/Coupon/Coupon.test.jsx
- src/components/Coupon/__snapshots__/Coupon.test.jsx.snap
- src/components/Coupon/index.jsx
- src/demo/coupons.js
- src/demo/data.js
- src/demo/rewireEcommerceApiService.js
Now that we have know the format of the coupon overview API response, we can update the field names in the `Coupon` component and demo data.
Also, after discussing with @brittneyexline and Jennifer about how the `max_uses` field can potentially be `null` (i.e., "unlimited" uses), the UI should only show "X of Y" in the "Enrollments Redeemed" column of the coupons if `max_uses` is set. If it isn't, we will only show `num_uses` field, e.g.:
> Update coupon demo data api response to reflect actual api fields

- src/components/Sidebar/index.jsx
- src/containers/Sidebar/Sidebar.test.jsx
Before, we were filtering out the sidebar menu items where `shouldInclude` is explicitly `false`. However, this results in the "Code Management" link still appearing in the sidebar on stage after merging the original sidebar navigation PR.
This PR swaps out `shouldInclude` for `hidden`, filtering out menu items for which `hidden` is truthy.
> Fix sidebar shouldInclude logic to use hidden instead

- src/components/Coupon/Coupon.test.jsx
- src/components/Coupon/index.jsx
- src/components/CouponDetails/CouponDetails.scss
- src/components/CouponDetails/index.jsx
This PR removes the previous filter buttons and, in their place, puts in an `InputSelect` component. I also rename a few variables/props to be `isExpanded`. This PR should be probably be merged before @mushtaqak's WIP PR lands as the filter UI has changed here.
> Swap out filter buttons with dropdown select

- src/components/Header/index.jsx
- src/containers/Header/Header.test.jsx
- src/containers/Header/__snapshots__/Header.test.jsx.snap
We were attempting to make an unauthenticated user profile API call on render of the Header under the public support route causing a redirect to the login page. 
This can be tested here: https://portal.edxdev.org/public/support
> Fix public support page.

- .eslintrc
- package.json
- src/components/ErrorBoundary/ErrorBoundary.test.jsx
- src/components/ErrorBoundary/__snapshots__/ErrorBoundary.test.jsx.snap
- src/components/ErrorBoundary/index.jsx
- src/components/RequestCodesPage/index.jsx
- src/data/actions/coupons.js
- src/data/actions/csv.js
- src/data/actions/dashboardAnalytics.js
- src/data/actions/enterpriseList.js
- src/data/actions/portalConfiguration.js
- src/data/actions/table.js
- src/data/services/NewRelicService.js
- src/data/services/NewRelicService.test.js
- src/index.jsx
[ENT-1290](https://openedx.atlassian.net/browse/ENT-1290)
> send handled/unhandled errors to newrelic

- src/data/actions/table.js
- The ```/enterprise/api/v0/enterprise/<enterprise_uuid>/enrollments```
api used to return 404 if there were no enrollments for that
enterprise.  So, the front-end code had to catch that error and
display an empty list.
- That error handling is no longer necessary because the api returns an
empty list now. (https://github.com/edx/edx-enterprise-data/pull/106)
> ENT-1455: Remove Unneeded Error Handling

- src/demo/coupons.js
This PR fixes a miner bug where we get `used > available`  redemptions(screenshot below)
This also modifies filters data such that data resembles data returned by backend api.
Below is short description for modified filters in demo data:
**Unassigned**: Codes with assignedTo ket as `undefined`.
**Unredeemed**: Assigned codes with assignedTo key set.
**Partially redeemed**: Codes with at-least one redemption but not completely redeemed (there is no 
way in frontend to determine from the `used` key if a code was redeemed or assigned.)
**Redeemed**: Codes with `used === available`.
[ENT-1471](https://openedx.atlassian.net/browse/ENT-1471)
> Fix selected toggles demo data 

- src/components/CodeAssignmentModal/index.jsx
[ENT-1525](https://openedx.atlassian.net/browse/ENT-1525)
Fixes the bulk version of `CodeAssignmentModal` to support 0 unassigned codes.
> Ensure bulk assign modal supports 0 unassigned codes

- src/components/CodeAssignmentModal/CodeAssignmentModal.scss
Increases the `max-width` property of the modal so it doesn't appear as narrow/congested. Prior to this change, the `max-width` was 500px. Here, we're increasing the modal width by 150px.
> Increase modal width

- src/components/CouponDetails/index.jsx
[ENT-1521](https://openedx.atlassian.net/browse/ENT-1521)
For the "partially redeemed" and "redeemed" table views, rename the `assigned_to` column label to be "Redeemed By" instead of "Assigned To".
I'm also removing the "Actions" column if the table view is "Redeemed" as there aren't any actions available for the codes in that view.
> Rename assigned_to column key for partially-redeemed and redeemed columns

- src/components/CodeAssignmentModal/index.jsx
- src/components/CouponDetails/CouponDetails.scss
- src/components/CouponDetails/index.jsx
- src/containers/CodeAssignmentModal/CodeAssignmentModal.test.jsx
- src/containers/CodeAssignmentModal/index.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
- src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
This PR updates the code selection logic to better handle the selection of individual codes as well as selecting all codes through the "select all" checkbox in the table header.
If there are more codes than shown on the page, a status alert is shown, prompting the user to select all codes across all pages.
The `CodeAssignmentModal` component is updated to handle when codes across all pages are selected.
If codes are selected on a page, but not all of them, a partial "select all" checkbox is displayed, as seen below.
**UI Example of Selection Checkboxes**
> Updating CouponDetails selection logic to handle select all

- src/components/CouponDetails/index.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
[ENT-1530](https://openedx.atlassian.net/browse/ENT-1530)
For coupons that have 0 unassigned codes, we should disable the bulk assign action in the input select as there are no codes to assign.
> Disable assign bulk action for coupons with 0 unassigned codes

- src/components/CouponDetails/index.jsx
1. Sends the selected toggle/filter to the coupon details CSV endpoint so it downloads codes for the currently selected toggle.
2. Disables selecting all codes across pages for toggles other than `unassigned` as the Remind/Revoke endpoints require specifying the exact codes. Note this still allows selecting all codes on a single page.
> Send selected toggle to CSV endpoint and hide select status alert

- src/components/CodeReminderModal/index.jsx
- src/components/CodeRevokeModal/emailTemplate.js
- src/components/CodeRevokeModal/index.jsx
- src/components/CouponDetails/index.jsx
- src/containers/CodeReminderModal/CodeReminderModal.test.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
1. Prevents submission of bulk remind form if no codes are selected (throws an error) as the remind endpoint requires specific codes to be specified.
2. Disables the "Remind"/"Revoke" options in the bulk action input select if no codes are currently selected as this wouldn't be a valid action anyways.
3. Updates the messaging in the error message of the bulk remind/revoke modals when no codes are selected.
4. Adds line break in the reminder email template.
> Minor updates to bulk remind

- src/components/CouponDetails/index.jsx
[ENT-1560](https://openedx.atlassian.net/browse/ENT-1560)
Prevents the select all checkbox from being checked when switching coupon details toggle from a view with 0 results to another table view.
> Prevent select all checked state when switching toggles

- src/components/CodeReminderModal/index.jsx
Description: This PR fixes error handling in the CodeReminderModal
> ENT-1486 Fixed issue with error handling

- src/components/CodeAssignmentModal/emailTemplate.js
Replace double curly braces with single braces, We need this because due to double curly braces python format does not work and placeholders were not filled.
> update assignment email template

- public/index.html
These two meta tags are in the cookie cutter but we didn't bring them into the edx-portal yet. This will fix `edx-portal` for mobile (so it doesn't load desktop view), and should resolve the issue outlined in [ENT-1577](https://openedx.atlassian.net/browse/ENT-1577).
> Adding utf-8 charset and viewport meta to index.html

- src/components/Coupon/Coupon.test.jsx
- src/components/Coupon/index.jsx
- src/components/CouponDetails/index.jsx
- src/containers/CodeManagementPage/CodeManagementPage.test.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
- src/data/constants/coupons.js
[ENT-1580](https://openedx.atlassian.net/browse/ENT-1580)
This PR removes the "Partially Redeemed" toggle option for "Single use" and "Once per customer" coupons.
I also did some refactoring to pass through all the data associated with a coupon to the `CouponDetails` component instead of as individual props, e.g.:
```jsx
<CouponDetails
isExpanded={isExpanded}
couponData={data}
/>
```
instead of:
```jsx
<CouponDetails
isExpanded={isExpanded}
id={data.id}
hasError={data.has_error}
unassignedCodes={data.num_unassigned}
couponTitle={data.title}
// etc...
/>
```
>  Hide partial redeem toggle for single use and once per customer coupons

- src/components/CouponDetails/index.jsx
Currently, the "select all" checkbox remains in a partial state after a successful code action. To fix, we should call `this.updateSelectAllCheckBox()` after a code action success to ensure the checkbox gets updated properly.
> Fix partial select status after code action success

- src/components/CouponDetails/index.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
**JIRA TIcket:** [ENT-1522](https://openedx.atlassian.net/browse/ENT-1522)
Currently, remind/revoke endpoints return HTTP 200 even if there is an error. We do send the error message in the returned response but frontend ignores that and show a generic successful message which is misleading because, in reality, it happens that remind/revoke failed for every assignment and we showed the successful message on the frontend. It would be nice to consider the error messages coming from the server and either highlight the rows to show that remind/revoke failed or some better way to convey the error message.
**Acceptance Criteria:**
Correctly show the error message to the user if there is an error with remind/revoke.
> ENT-1522: Update coupon code remind/revoke backend and frontend with proper error checking

- src/components/CodeAssignmentModal/index.jsx
- src/components/CouponDetails/index.jsx
[ENT-1573](https://openedx.atlassian.net/browse/ENT-1573)
For "Once per customer" coupons, we should allow the user to assign more emails than the number of selected codes since an individual code can be assigned to multiple users.
This PR removes the validation check for "Once per customer" coupons that looks to see if the number of emails provided is <= the number of selected codes. This will allow more emails to be assigned than the number of selected codes per the ticket description.
If a particular cannot be assigned, the modal will show an error and display the associated error message. In some cases, the response will contain an array of `non_field_errors` which should be included in the error status alert within the modal. If these `non_field_errors` exist in the response, we now …
> Support assigning more than num selected codes for "once per customer" coupons

- src/components/Coupon/Coupon.test.jsx
- src/components/Coupon/index.jsx
- src/components/CouponDetails/index.jsx
- src/containers/CodeManagementPage/CodeManagementPage.test.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
- src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
- src/demo/coupons.js
- src/demo/rewireEcommerceApiService.js
This PR improves error message display for a coupon.
Previously, a coupon used to get `has_error` key which is now changed to give us a complete list of errors if any.
```javascript
errors: [{'code': 'JKAPSIJ', 'user_email': 'test@example.com'}, {'code': 'CHJKNEM': 'user_email': 'test2@example.com'}]
```
This is how errors would be now show:
**1) In case of a single error**
**2) In case of multiple errors**
[ENT-1531](https://openedx.atlassian.net/browse/ENT-1531)
> Improved error messages display

- src/components/CodeManagement/index.jsx
- src/containers/CodeManagementPage/CodeManagementPage.test.jsx
It was an issue with remounting the code management page after redirecting back from the request form. It was solved by checking props on mount instead of on receiving now props. Also changed a test to reflect the new structure.
> Fixed request codes success banner not properly showing bug.

- src/components/CodeManagement/index.jsx
- src/components/Coupon/Coupon.test.jsx
- src/components/Coupon/index.jsx
- src/components/CouponDetails/index.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/Sidebar/index.jsx
- src/containers/CodeManagementPage/CodeManagementPage.test.jsx
- src/containers/CouponDetails/index.jsx
- src/containers/EnterpriseApp/__snapshots__/EnterpriseApp.test.jsx.snap
- src/containers/Sidebar/__snapshots__/Sidebar.test.jsx.snap
- src/data/reducers/table.js
- src/data/reducers/table.test.js
- src/data/services/EcommerceApiService.js
[ENT-1491](https://openedx.atlassian.net/browse/ENT-1491)
For coupon pagination, we modify the `overview_page` query parameter. For code pagination (coupon details), we modify the `page` query parameter.
When a coupon is expanded, a `coupon_id` query parameter is added. This gets removed when the coupon is collapsed. On initial page load, if the `coupon_id` query parameter is set, the component will try to expand the coupon with that id. If the id is not in the results from the API, the `coupon_id` query parameter is removed.
For example, if you expand a coupon on page 2 of the overview page, and are on page 3 of the coupon details, the URL would look something like: `/coupons?coupon_id=1&overview_page=2&page=3`.
This now supports pagination for both coupons and codes, as well as deep …
> Fixes pagination / history for Code Management

- src/components/CodeManagement/index.jsx
When testing the recent pagination changes on stage, I noticed the opacity of the coupons were not always correct. I did some more testing locally and did a minor refactor the logic in `setCouponOpacity` function to fix the issue.
> Minor fix for ensuring the coupon opacities are correct

- src/components/CouponDetails/index.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
- src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
Restrict bounced codes on redeemed toggle because it does not make sense to show error messages for codes that do not appear on unassigned, redeeemed or partial-redeemed toggles.
[ENT-1635](https://openedx.atlassian.net/browse/ENT-1635)
> Restrict bounced codes on redeemed toggle

- src/components/Coupon/__snapshots__/Coupon.test.jsx.snap
- src/components/Coupon/index.jsx
- src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap
Currently, the overview shows "unassigned codes" but this doesn't actually show the # of un-assignments remaining i.e. if 1 code has 500 potential assignments, it will always only show 1. It would be more useful to the admin to know the # of assignments there are left for them to take action on.
> ENT-1714: Update Overview to Include Assignments Remaining

- src/data/actions/enterpriseList.test.js
- src/data/actions/portalConfiguration.test.js
- src/data/services/LmsApiService.js
Per [ENT-1760](https://openedx.atlassian.net/browse/ENT-1760), we should replace our `with_access_to` calls with the new `dashboard_list` call. The response with both of these calls is the same; the `dashboard_list` endpoint uses the new permissions.
See the PR for the `dashboard_list` endpoint [here](https://github.com/edx/edx-enterprise/pull/444/files#diff-4495418c366e5831b5e2daaea415aa56R240). Also, I removed where we pass `{ permissions: 'enterprise_data_api_access' }` as the new endpoint does not check the permissions name.
Additionally, the `dashboard_list` endpoint looks for an `enterprise_slug` query parameter, where before we were passing `slug`. I've updated this as well to match what the endpoint expects.
**Important note: This PR should be merged AFTER we turn on the …
> Replace `with_access_to` calls with `dashboard_list` calls

- src/containers/Header/index.jsx
Ticket: [ENT-1823](https://openedx.atlassian.net/browse/ENT-1823)
If a user authenticates with edx-portal but does not have `profileImage` set, we are currently throwing a JS error because we're trying to access a property of `profileImage`, which is `null`. This fix ensures `profileImage` exists before trying to access its properties, and avoids throwing the error.
> Fix for null profileImage value

- src/components/CouponDetails/index.jsx
- src/containers/CouponDetails/CouponDetails.test.jsx
- src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
The purpose of this PR is to add a new column `Assignments Remaining` to Unassigned Table that will display remaining assignments for each voucher code.
[ENT-1706](https://openedx.atlassian.net/browse/ENT-1706)
> Add `Assignments Remaining` column to Unassigned Table

- src/components/Admin/Admin.test.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
On Admin Dashboard, if no analytics data is returned by the API, we will show a `404` page. 
This handles both the scenarios where an invalid enterprise id is supplied in url (slug) or user does not have the access. In both cases, API sends no results in the response, hence a `404` page will be shown to them.
[ENT-1830](https://openedx.atlassian.net/browse/ENT-1830)
> Show 404 page if no data is returned by API

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
Replace the 404 component flash with a loading component instead. This does create a situation where 2 loading screens are show in a row if the root url of the portal is hit and the user is only authorized for a single enterprise.
> Replace 404 with loading component

- src/components/ActionButtonWithModal/index.jsx
- src/components/CodeManagement/CodeManagement.scss
- src/components/CodeManagement/index.jsx
- src/components/CodeReminderModal/index.jsx
- src/components/CodeRevokeModal/index.jsx
- src/components/CodeSearchResults/CodeSearchResults.scss
- src/components/CodeSearchResults/CodeSearchResults.test.jsx
- src/components/CodeSearchResults/CodeSearchResultsHeading.jsx
- src/components/CodeSearchResults/CodeSearchResultsTable.jsx
- src/components/CodeSearchResults/__snapshots__/CodeSearchResults.test.jsx.snap
- src/components/CodeSearchResults/index.jsx
- src/components/CouponDetails/index.jsx
- src/components/RemindButton/index.jsx
- src/components/RevokeButton/index.jsx
- src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap
- src/containers/CouponDetails/CouponDetails.test.jsx
- src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
- src/data/services/EcommerceApiService.js
- src/data/services/__mocks__/codeSearchResultsResponse.json
This PR adds the code search UI functionality as seen in the gif below:
Note: I am currently working on getting the action buttons (remind/revoke) in the search results table, so that a user can take action on the relevant results right from the search results table. I am trying to reuse the same logic as those action buttons from the `CouponDetails` component and will be abstracting those action buttons and their associated logic into their own reusable component. Tests are still to come.
Supporting pagination will be some extra work as our `TableContainer` component does not currently support pagination when there is more than one table on the page, as is the case here when a coupon batch is expanded. We may want to punt on supporting pagination initially, and follow-up with a new …
> Add code search UI functionality

- src/components/CodeSearchResults/index.jsx
If you revoke a code when it is the only row in the table on page 2, the frontend will attempt to reload the table data for that same page. However, since this the revoked code was the only result for that page, the API then returns a 404. To account for this, we remove the `page` query parameter after a successful revoke, such that the table fetches page 1 of the search results.
> Reset page query param after successfully revoking a code from search results

- config/webpack.prod.config.js
- src/components/Sidebar/index.jsx
- src/containers/Sidebar/index.jsx
- src/data/reducers/portalConfiguration.js
Turns on the feature flag for Reporting configurations in stage + production. If an EnterpriseCustomer does not have this feature enabled, they will not see the page in the sidebar.
> Remove reporting config for enterprises that do not have it activated.

- src/components/RequestCodesPage/RequestCodesForm.jsx
- src/components/RequestCodesPage/index.jsx
- src/data/services/LmsApiService.js
- src/utils.js
This ticket is related to provide a box so that the requestor can write notes & specifications for the codes they're ordering, to streamline the communication. 
**Page URL** = ` /{enterprise-slug}/admin/coupons/request`
**Pre PR: **
When the user will visit this page there will be three fields.
1.Email Address
2.Company
3.Number of codes
**Post PR: **
When the user will visit this page there will be an extra field named notes.
1.Email Address
2.Company
3.Number of codes
4.Notes
Max Length For this field is assumed 512 characters.
**Dependency:**
Backend PR for this ticket is
https://github.com/edx/edx-enterprise/pull/594
[ENT-2213](https://openedx.atlassian.net/browse/ENT-2213)
> Added a notes field so that the requestor can write notes for the codes.

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
Some Enterprise reporting configs have an old reporting data type that we don't want to create more of. We still need to maintain these reports, so they will still show up in the list of configs. You will not be able to change the type of the report, so if a different type of report is needed, you must create a new one.
> Add old progress data type support for reporting configurations

- .travis.yml
- Dockerfile
As part of the upgrade efforts to Node 12, this PR updates this repo from Node 8 to 12. Once this PR lands, we can update the column for this repo with a 🍑 😄- https://openedx.atlassian.net/wiki/spaces/FEDX/pages/931561855/Frontend+Repos.
I'm also removing the `notifications` from .travis.yml.
> fix: upgrade to node 12

- src/components/CodeAssignmentModal/BulkAssignFields.jsx
- src/components/CodeAssignmentModal/index.jsx
Ticket: [ENT-2498](https://openedx.atlassian.net/browse/ENT-2498)
* Ensures the CSV file and the manual entry textarea contents are split on both `\r\n` and `\n`. This ensures we split on blank lines, both at the beginning and end of the file.
* Adds a new function which, given an array of email addresses, will return an object with valid emails and the indices of which emails in the provided array are invalid.
* The validation conditionals now use the valid emails & invalid email indices instead of the non-"parsed" emails.
* An error message is created dynamically to include the line number in the contents of the CSV file or textarea where the first invalid email lives (e.g., "Email address on line 2 is invalid. Please try again.").
> fix email address validation during CSV file upload

- src/components/CodeAssignmentModal/index.jsx
With the recent validation logic changes, we separate invalid emails from valid emails before doing validation checks on those emails. This PR changes the order of validation to check whether there's any invalid emails where a validation message should appear before validating the valid emails.
> Fix order of email validation in code assignment modal

- config/webpack.dev.config.js
- config/webpack.prod.config.js
- src/components/EnterpriseApp/index.jsx
- src/components/Sidebar/index.jsx
- src/config/index.js
- src/containers/EnterpriseApp/EnterpriseApp.test.jsx
- src/containers/EnterpriseApp/index.jsx
- src/containers/Sidebar/Sidebar.test.jsx
- src/containers/Sidebar/index.jsx
- src/data/reducers/portalConfiguration.js
- src/data/reducers/portalConfiguration.test.js
This PR adds a new tab for Subscription Management to the admin dashboard, based on a new feature flag and the enterprise customer configuration from https://github.com/edx/edx-enterprise/pull/724. For now, the route just loads the code management screen component, which will be replaced later.
> ENT-2640 Add new Subscription Management tab to admin dashboard

- src/components/Footer/Footer.scss
- src/components/Header/Header.scss
- src/components/Header/index.jsx
- src/containers/Header/__snapshots__/Header.test.jsx.snap
Currently, the logo images for the Admin Dash can take up a lot of space in the header and footer, creating a lot of unnecessary whitespace. 
**Current:**
This PR sets a `max-height` on the logos in the header/footer so the image sizes are more constrained for less unnecessary whitespace.
**Updated:**
> Reduce logo image sizing to reduce unneeded whitespace in header/footer

- src/components/Admin/Admin.scss
- src/components/Admin/AdminCards.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/NumberCard/NumberCard.scss
- src/components/NumberCard/__snapshots__/NumberCard.test.jsx.snap
- src/components/NumberCard/index.jsx
IE11/Edge does not currently support the row of number cards. This PR uses Boostrap classes to ensure cross-browser compatibility.
> Refactor number cards layout for IE11/Edge support

- src/components/ActionButtonWithModal/index.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/LicenseRemindModal/index.jsx
- src/components/LicenseRevokeModal/index.jsx
- src/components/Sidebar/index.jsx
- src/components/subscriptions/LicenseActions.jsx
- src/components/subscriptions/RemindUsersButton.jsx
- src/components/subscriptions/SubscriptionData.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
- src/components/subscriptions/TabContentTable.jsx
- src/components/subscriptions/constants.js
- src/components/subscriptions/data/service.js
- src/containers/LicenseRemindModal/LicenseRemindModal.test.jsx
- src/containers/LicenseRevokeModal/LicenseRevokeModal.test.jsx
- src/data/actions/licenseRevoke.js
Always show the "Add Users" button and conditionally render the "Remind all" button for just the "Pending Users" tab. Also, adds a count to the "Remind all" button:
More importantly (and what adds most of the complexity of this PR), using the fake data available on the page, the "Revoke" action for a user now changes the status of their license from activated/assigned to deactivated.
Then, we make (mocked) API calls to refresh the data for the page now that an action was performed to remove a user:
1. Upon successful revocation, we re-fetch the `SubscriptionPlan` details to get the new number of licenses allotted. This allow us to update the "X of Y licenses allotted" message.
1. We also need to re-fetch the [`overview` endpoint](https://github.com/edx/frontend-app-admin-portal/blob/master …
> Always show "Add Users" button but conditionally render "Remind all"; refresh subscription data after revoking a user

- src/components/EnterpriseApp/index.jsx
* If an enterprise is logged into the portal, users can access the support page at 'admin/support'
* Without the flag enabled, the support page shows the old page (MailtoLink instead of a form)
ENT-2732
> Always generate route to support form

- src/components/SupportPage/SupportForm.jsx
- src/components/SupportPage/index.jsx
- src/data/services/ZendeskApiService.js
Submitting the support form creates a post request to the Zendesk proxy that currently resides in edx-platform. This way, users can submit a request without exposing API secrets. The Zendesk proxy takes the fields that the user enters and creates a ticket.
- https://github.com/edx/edx-platform/tree/master/openedx/core/djangoapps/zendesk_proxy
The ticket is created with the inputted form fields. The tag "enterprise_admin_support" is associated with a trigger within the Zendesk Help Desk so that any ticket with that tag is sent to the edX for Business brand. Currently, ECS processes tickets that are in the edX for Business brand in Zendesk.
- Utilized the Zendesk sandbox workflow and observed that tickets created with the "enterprise_admin_support" tag get routed to a specific brand
- …
> ENT-3166: Support form creates Zendesk ticket

- src/components/LicenseRevokeModal/index.jsx
- src/components/subscriptions/LicenseActions.jsx
- src/components/subscriptions/data/service.js
- src/containers/LicenseRevokeModal/LicenseRevokeModal.test.jsx
- src/containers/LicenseRevokeModal/index.jsx
- src/data/actions/licenseRevoke.js
When revoking licenses in the admin dash subscriptions page, the expected data is sent to the license manager service via API call.
Verify that the “Revoke” submit button in the modal has a spinner while the API call is pending, and the modal closes after successful revoke.
Verify that when the revoke endpoint errors, an error alert is shown in the “Revoke” modal.
> ENT-2955-Admin Dash: Connect revoke endpoint for subscriptions frontend

- src/components/LicenseRemindModal/index.jsx
- src/components/subscriptions/LicenseActions.jsx
- src/components/subscriptions/RemindUsersButton.jsx
- src/components/subscriptions/TabContentTable.jsx
- src/components/subscriptions/data/service.js
- src/containers/LicenseRemindModal/LicenseRemindModal.test.jsx
- src/containers/LicenseRemindModal/index.jsx
- src/data/actions/LicenseReminder.js
- When reminding users in the admin dash subscriptions page, the expected data is sent to the license manager service via API call.
- The “Remind” submit button in the modal has a spinner while the API call is pending, and the modal closes after successful reminder (logic should already be in place, just need to verify).
- The “remind” endpoint errors, an error alert is shown in the “Remind” modal (logic should already be in place, just need to verify).
> ENT-2954: Connect remind endpoint for subscriptions frontend

- src/components/subscriptions/LicenseAllocationNavigation.jsx
- src/components/subscriptions/SubscriptionData.jsx
- src/components/subscriptions/TabContentTable.jsx
- src/components/subscriptions/constants.js
**JIRA**: https://openedx.atlassian.net/browse/ENT-3150
**Issues Fixed:**
-  Assignments in the grid do not appear to be correct in ALL USERS TAB, it shows unassigned licenses
- The search results should gracefully handle the scenario if no results are found and display an appropriate message. Same goes for the all 4 filters at the left Licensed, Pending, Deactivated..etc.
- All Users count in LicenseAllocationNavigation should be equal to assigned+activated+deactivated licenses, currently it is showing total licenses
_Note: This PR requires backend changes made in this PR: https://github.com/edx/license-manager/pull/78_
> ENT-3150:Fix UI/UX issues related to integration of subscriptions backend

- src/components/AddUsersModal/index.jsx
The backend expects to receive the custom greeting and closing
variables as ``greeting`` and ``closing``.
ENT-3193
> Fix custom greeting/closing for subscriptions add

- src/components/subscriptions/SubscriptionData.jsx
- src/components/subscriptions/hooks/licenseManagerHooks.js
Admin Dash Subscriptions page briefly displays empty/error state before loading all the data
> ENT-3177 Show the error message only once the api call is completed.

- src/components/SamlConfiguration/SamlProviderConfigForm.jsx
- src/components/SamlConfiguration/index.test.jsx
Related [backend PR](https://github.com/edx/edx-platform/pull/24560) -- **Merged**
Saml config [ground work PR]( https://github.com/edx/frontend-app-admin-portal/commit/49e2cfd2e7da36b01db3e210a3da2ee8f6205d22)    -- **Merged** 
We want an end user to have the ability to include their IDP's country attr URN along with the rest of their SAML config data and have the country be included in the backend Django Admin config creation. The linked backend PR above has backwards compatibly added country as a new field in the model. This PR adds country as an additional text input to the config form. 
Additionally added state change tests and slightly padded out the unit tests for Saml configs.
> ENH- adding country attr to SAML config form

- src/components/SamlConfiguration/index.jsx
- src/components/SamlConfiguration/index.test.jsx
While testing changes when fixing another bug, I realized provider config was not displaying if data was 404'ing. This is due to using promise.all instead of promise.settled.
Switching to promise.settled allows us to still resolve providerConfig and providerData gets simultaneously, but ensures we can display config even if the data call fails.
- Have latest master branch of edx-platform
- Make sure LMS is running.
- Make sure you have an enterprise user associated with an enterprise customer and that user has an operator or admin enterprise system wide role configured.
- Enable the saml portal in LMS admin:
- `localhost:18000/admin/enterprise/enterprisecustomer`
- Click on the name of an enterprise customer (thus navigating to the enterprise customer details).
- Scroll towards the bottom …
> BUG: Fix saml response display

- package-lock.json
- package.json
- src/components/Admin/Admin.scss
- src/components/Admin/AdminSearchForm.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/DownloadCsvButton/index.jsx
- src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
- src/utils.js
This adds a course title and a date filter to the admin portal. 
MIRO Board: https://miro.com/app/board/o9J_kp-7aks=/?moveToWidget=3074457348864300777&cot=13
**Notes for review**
The backend has been updated but not merged, so you will need to be on the `ENT-3086` filters branch of `edx-enterprise-data` (installed into `edx-analytics-data-api`, similarly to how we installed `edx-enterprise` into `edx-platform`) in order to review this properly.
I created courses and learners by using the EnterpriseEnrollmentFactory in the django shell.
The date field is disabled until a course title has been selected.
There are plans for a form reset button and some help text in a pop-over, but I'm going to open another ticket for those because the design has not been finalized.
> Add more filters to learners screen

- src/components/subscriptions/hooks/licenseManagerHooks.js
Sends the search query parameter to the license-manager overview
endpoint to correctly filter results. Also ensures that we always start
from a correct initial count of 0 for each license status.
ENT-3191
Behavior:
> Update the count of licenses when searching

- src/components/subscriptions/AddUsersButton.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
[ENT-3197](https://openedx.atlassian.net/browse/ENT-3197)
This PR aligns the "Add Users" button to the left for small screens, and to the right for large screens. Also noticed that some elements were not wrapped in a `.container-fluid` class, so there was some minor misalignment between everything above and below the "License Allocation" heading.
> fix Subscription Mgmt layout issues and align "Add Users" button to left for small screens

- src/index.jsx
Fixes a bug where the enterprise customers weren't routing us to their portal and broke routing around different admin actions.
> Put the JwtAuthenticationRefresh wrapper outside of the ConnectedRouter.

- src/components/TemplateSourceFields/TemplateSourceFields.scss
- src/components/TemplateSourceFields/index.jsx
**Description:** Show tooltips for `New Email` and `From Template` buttons to reduce confusion in email template creation for code assignments.
**JIRA:** [ENT-3425](https://openedx.atlassian.net/browse/ENT-3425)
> show tooltips for New Email and From Template buttons

- src/components/CodeAssignmentModal/index.jsx
- src/components/CodeReminderModal/index.jsx
- src/components/CodeRevokeModal/index.jsx
As a part of ENT-3148, this PR covers the part to add `template_id` in request data for Assign, Remind and Revoke endpoints.
JIRA: https://openedx.atlassian.net/browse/ENT-3148
> ENT-3148: Add template_id in request data for Assign, Remind and Revoke

- src/components/Admin/AdminSearchForm.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
Course search filter was not properly resetting because it's value was undefined
This changes it to the empty string which is the default option of 'All courses'
> Reset course search filter label

- package-lock.json
- package.json
- src/components/subscriptions/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/SubscriptionExpirationBanner.test.jsx
- src/components/subscriptions/SubscriptionExpirationModal.jsx
- src/components/subscriptions/SubscriptionExpirationModal.test.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
- src/components/subscriptions/constants.js
- src/components/subscriptions/styles/_SubscriptionExpirationModal.scss
- src/components/subscriptions/test-utils.js
- src/index.scss
Note that this doesn't provide any sort of post-expiration experience
and there isn't any backend validation preventing admins from doing
things once their subscription expires. That will come later.
ENT-3504
**Pre-expiration modal**
**Post-expiration modal**
**<= 120 day banner:**
**<= 60 day banner:**
**<= 30 day banner:**
> Add subscription expiration experience for admins

- src/components/CodeAssignmentModal/CodeAssignmentModal.scss
- src/components/CodeAssignmentModal/index.jsx
- src/containers/CodeAssignmentModal/index.jsx
**Description:** Add a checkbox to enable/disable auto reminder emails. Frontend will send `email_auto_reminder` field in assign data to backend. The value (`true/false`) of this field will tell whether we need to enable or disable the automatic reminder emails for the assigned learners.
**JIRA:** [ENT-3488](https://openedx.atlassian.net/browse/ENT-3488)
> add auto remind email checkbox

- src/components/CodeRevokeModal/index.jsx
The UI glitch appeared by following these steps 
1. On the code revoke modal, scroll down the bottom and select the "Do Not Email" checkbox, this will disable email template fields
2. Scroll up and switch between "New Email" and "From Template" tab
3. Scroll down and you will see "Do Not Email" checkbox is not checked, even though the template fields are still disabled.
This PR makes sure that "Do Not Email" checkbox retains its state when switching between "New Email" and "From Template" tab.
> ENT-3657: Fixed a small UI glitch

- src/components/NumberCard/index.jsx
A change introduced in the rebrand PR caused undesirable toggle behavior in the number cards, this fixes it.
> Fix toggle on number card

- src/containers/EnterpriseApp/index.jsx
I added the expected backend-passed portal configuration flag in my previous [PR](https://github.com/edx/frontend-app-admin-portal/pull/357), but because the backend had not been done yet, I didn't get a chance to test this flag working and thus missed a spot where it needed to be added to one of the jsx files.
This PR adds it to the missing spot. I've verified it works with the backend changes as well.
> missed a portal parameter in previous pr

- src/components/subscriptions/AddUsersButton.jsx
- src/components/subscriptions/LicenseAllocationNavigation.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
- src/components/subscriptions/SubscriptionManagementPage.test.jsx
- src/components/subscriptions/TabContentTable.jsx
Add getting started messaging for when admins view All Users on a subscription that has no allocated licenses on it.
> Add zero state for subscription with no allocations

- package-lock.json
- src/components/AdminRegisterPage/index.jsx
- src/containers/AdminRegisterPage/AdminRegisterPage.test.jsx
- src/data/constants/index.js
- src/utils.js
https://openedx.atlassian.net/browse/ENT-3884
The previous implementation of the logic for admin registration broke down when a user is authenticated but without any JWT roles, causing a danger alert to be rendered.
The issue is that we need their JWT to refresh to bring in the new JWT roles they were assigned through the pending admin user configured in Django Admin. To get around this, we now force a logout with a redirect to the branded logistration page. When they login again, they will have the correct JWT roles added and be able to continue with their admin registration.
Related PR: https://github.com/edx/edx-enterprise/pull/1093
> fix: force logout to refresh JWT roles for admin registration

- README.md
- config/webpack.dev.config.js
- src/index.scss
Modify paragon scss imports so that webpack resolves them properly when a local version of paragon is being used
Update README with an explanation of how to use local libraries.
Removes outdated section about demo data.
> Update webpack config for use of local libraries

- src/components/EnterpriseApp/index.jsx
- src/components/Sidebar/index.jsx
Added flags so that Bulk Enrollment depends on same subscription management screen, with the idea being that if your enterprise can manage subscriptions it should be able to enroll learners.
> ENT-3883 Disable bulk enrollment when the subscription is invalid

- package-lock.json
- package.json
- src/components/LmsConfigurations/BlackboardIntegrationConfigForm.jsx
- src/components/LmsConfigurations/BlackboardIntegrationConfigForm.test.jsx
- src/components/LmsConfigurations/CanvasIntegrationConfigForm.jsx
- src/components/LmsConfigurations/CanvasIntegrationConfigForm.test.jsx
- src/components/LmsConfigurations/DegreedIntegrationConfigForm.jsx
- src/components/LmsConfigurations/DegreedIntegrationConfigForm.test.jsx
- src/components/LmsConfigurations/MoodleIntegrationConfigForm.jsx
- src/components/LmsConfigurations/MoodleIntegrationConfigForm.test.jsx
- src/components/LmsConfigurations/SuccessFactorsIntegrationConfigForm.jsx
- src/components/LmsConfigurations/SuccessFactorsIntegrationConfigForm.test.jsx
- src/components/LmsConfigurations/common.jsx
- src/components/LmsConfigurations/index.jsx
- src/components/LmsConfigurations/index.test.jsx
- src/data/services/LmsApiService.js
This adds the new form for Degreed Customer Configuration.
This also attempts to set some precedent in this repo with the following:
- Moving the error alert to the top of the form and triggering focus on it to align with Accessibility guidelines.
- Uses React Testing Library on every test on the form component
- Instantiates the form component as a functional component and utilizes `useState` and `useReducer`
This also moves 2 functions we were word for word reusing across LmsConfiguration forms into a common.jsx file (those are `handleErrors` and `validate[LMSName]ConfigForm` (which has been renamed `validateLmsConfigForm`))
Oh it also fixes 2 visual bugs:
- Blackboard was labeled as Canvas
- Success Factors wasn't properly wrapped in a div.
What this does ***not*** do:
- Update …
> Degreed Configuration Form

- src/components/LmsConfigurations/BlackboardIntegrationConfigForm.jsx
- src/components/LmsConfigurations/CanvasIntegrationConfigForm.jsx
- src/components/LmsConfigurations/DegreedIntegrationConfigForm.jsx
- src/components/LmsConfigurations/MoodleIntegrationConfigForm.jsx
- src/components/LmsConfigurations/SuccessFactorsIntegrationConfigForm.jsx
- src/components/LmsConfigurations/common.jsx
- src/data/services/LmsApiService.js
This just cleans up some graphical issues and backend bugs:
- fixed active flag in some of the config forms was being sent as "undefined" which was causing an error in backend validation (field is boolean and does not support undefined)
- fixed error state not clearing after resubmission.
- moved Active box to top for Canvas form for ~ consistency ~
- used put instead of patch, because form value was being interpreted as no change instead of "false"
- Fixed the error format of the error we send to NewRelic as it wasn't matching the actual NR method logic.
> minor UI/bug fixes for LMS config forms

- config/webpack.prod.config.js
This is for ENT-3418.
This now enables the LMS Configuration screen such that [**if enabled in LMS admin**] an enterprise customer can now access the sidebar item without the feature flag query string.
> Allow access to LMS Configuration screen without feature flag

- src/components/subscriptions/data/hooks.js
The SubscriptionViewSet that returns subscriptions to admins did not previously filter for `is_active=True`, so we had to filter for active plans client-side.
Despite this, we were referencing the total count of plans returned by the API rather than the filtered count. This is causing a bug on Subscriptions page where we'll show the "Back to subscriptions" button when the Enterprise has 2 subscription plans, one of which is inactive.
Related: https://github.com/edx/license-manager/pull/177
> fix: remove client-side filtering of `isActive` subscription plans as API now only returns active plans

- config/webpack.dev.config.js
- config/webpack.prod.config.js
it seems that terser may be trying to minify some non-es5 code when `npm run build` is run in GoCD for the past 3 build attempts.
im hoping that adding the @babel/preset-env preset option to our webpack config's babel-loader will ensure babel is correctly using that preset to ensure everything is transpiled :crossed_fingers:
> fix: attempting to fix build error on deploy

- config/webpack.dev.config.js
- config/webpack.prod.config.js
This reverts commit a6525451094a58a8974d6e8007cf7552c8cb6037 as it did not fix the build error.
> Revert "fix: attempting to fix build error on deploy (#459)"

- src/components/EnterpriseApp/index.jsx
- src/containers/EnterpriseApp/EnterpriseApp.test.jsx
- src/containers/EnterpriseApp/index.jsx
- src/data/reducers/portalConfiguration.js
- src/data/reducers/portalConfiguration.test.js
When the admin portal first refreshes/loads, we fetch the configurations for each potential tab the user/enterprise has setup. These configurations are setup so that if none are loaded, we default to the `NotFound` base component, which has created the situation where there is the small amount of time between the initial loading of the page and the fetching of the configurations where nothing is set, so we flash the `Not Found` page. 
The fix here is pretty straight forward- change the default loading state of fetch configurations redux to `true` and render in a loading component to the Enterprise App until that loading prop is `false`. This way we still have a not found page if the user is somewhere weird, but don't flash it to the user if they refresh the page.
**What we don't want:** …
> Adding loading to the base Enterprise App

- package-lock.json
- package.json
Reverts the installation of @edx/brand-edx.org in favor of @edx/brand-openedx. 
@edx/brand-edx.org is installed at build time in GoCD via an npm alias, but is often installed during local development to make sure what we're doing will look good with the new theme. It's too easy to miss reverting the install of @edx/brand-edx.org, though.
> fix: revert to openedx theme in package.json

- src/index.scss
JIRA: ENT-4205
Tested locally by:
* changing above import
* [1] verified openedx style applies by default (blue buttons, rounded corners etc)
* [2] did a `npm install --save @edx/brand@npm:@edx/brand-edx.org` to get overriden theme and verified new style (black-ish buttons with flat corners) now show
will file another ticket for a slightly more future-proof frontend-enterprise change, but this change will suffice to address this issue for now
> feat: fix brand style issue by only importing course-search styles

- src/components/App/index.jsx
- src/data/history.js
- src/utils.js
Based on observation and doc at https://github.com/edx/frontend-platform/blob/master/src/initialize.js#L81
there is an extra Router now in the component tree, and also history should be used from frontend-platform to avoid cross-talk
https://github.com/edx/frontend-platform/blob/master/src/initialize.js#L81
Testing:
Locally navigated through app and tested back button etc.
If any more testing needed , can try those.
> ENT-4307 : remote extra Router element and replace local history with one from platform

- webpack.prod.config.js
Description: This PR enables the Analytics feature in production for those enterprises who have this feature enabled in their django admin configurations.
> ENT-4268: Analytics feature enabled

- .gitignore
- src/components/BulkEnrollmentModal/index.jsx
- src/components/CodeReminderModal/index.jsx
- src/utils.js
Changes included to improve error messaging:
Another round of improvements will come once the new backend is in place since then we can make more 'intelligent' error messages (there is another ticket to decide error messages)
> feat: ENT-4197: improve error messaging formatting, and also report to NewRelic/console on errors

- src/data/services/LmsApiService.js
I should have removed this when swapping our endpoints to use the bulk enrollment endpoint via License Manager, but I forgot!
(See this pr: https://github.com/edx/frontend-app-admin-portal/pull/510)
PS: If you CTRL+F (or CMD+F) through the codebase you may think we're still using this API call but I assure you we aren't. We just named everything exactly the same! 😑
> refactor: remove unused endpoint.

- src/components/LicenseRemindModal/index.jsx
- src/data/validation/email.js
- src/data/validation/email.test.js
When consolidating validation (done as a side effect of this pr: https://github.com/edx/frontend-app-admin-portal/pull/510) I missed a call site in the LicenseRemindModal that actually passed the `isSubjectRequired=false` flag.
As this validation function is used in 2 other Code related modals that *do* require subject, I just created a passthrough parameter to the field validation function.
> fix: license reminder email doesn't need subject

- .eslintrc
- package-lock.json
- package.json
- src/components/BulkEnrollmentModal/index.jsx
- src/components/LicenseRemindModal/index.jsx
Devs locally are getting errors and having MFEs actually just crash due to the webpack hot reload dev server in Frontend-build version 5.6.10. Frontend-build was updated to include a necessary config flag to fix this. This PR just updates to the latest frontend-build (5.6.11) to get that change.
This also has linter workarounds as frontend-build also updates some babel packages which are broken on Template Literals.
If you are here because of this error: `TypeError: Cannot read property 'range' of null` you can see the linter rules updated in eslintrc below to address this issue (hopefully temporarily). I believe a new version of babel/parser needs to come out for this to be fixed. 
There are a lot of old issues that reference this error, so I'm not going to link to any particular one as …
> fix: Frontend Build + Linting workarounds

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
- src/components/ReportingConfig/index.jsx
- src/data/services/LmsApiService.js
As an enterprise customer, I may receive multiple reports and consume different types of data, including course metadata and course run metadata. 
In the admin dashboard today, it is possible for customers to configure catalog reports to be sent to them. However, they do not have the ability to select specific catalogs they would like to receive. See the pied piper admin dashboard for an example: https://portal.edx.org/pied-piper-non-integrated-test/admin/reporting
It would be helpful if there was a way for customers to select which catalog's metadata they would like to receive when configuring a report.
> ENT-4310: Allow Enterprise Customers to Select Catalogs to receive content metadata reports

- src/components/BulkEnrollmentModal/index.jsx
- src/components/BulkEnrollmentModal/index.test.jsx
- src/components/ReduxFormCheckbox/ReduxFormCheckbox.test.jsx
- src/components/ReduxFormCheckbox/__snapshots__/ReduxFormCheckbox.test.jsx.snap
- src/components/ReduxFormCheckbox/index.jsx
- src/data/constants/addUsers.js
[Jira](https://openedx.atlassian.net/browse/ENT-4340)
Default state of modal upon opening:
Goals: Add a checkbox to the bulk enrollment modal that allows the user to enable or disable the option to notify the learners who are being enrolled. Functionally, dictate the `notify` parameter sent to the License manager's validation endpoint from the value by the new checkbox.
> Adding notify learners checkbox to the bulk enrollment modal

- src/components/BulkEnrollmentPage/CourseSearch.jsx
- src/components/BulkEnrollmentPage/index.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/Sidebar/index.jsx
- src/components/subscriptions/MultipleSubscriptionPicker.jsx
- src/components/subscriptions/MultipleSubscriptionsPage.jsx
- src/components/subscriptions/SubscriptionCard.jsx
- src/components/subscriptions/SubscriptionData.jsx
- src/components/subscriptions/SubscriptionDetailPage.jsx
- src/components/subscriptions/data/constants.js
- src/components/subscriptions/data/contextHooks.jsx
- src/components/subscriptions/expiration/SubscriptionExpiration.jsx
- src/components/subscriptions/index.js
- src/components/subscriptions/licenses/LicenseAllocationDetails.jsx
- src/components/subscriptions/licenses/LicenseManagementTabContentTable.jsx
- src/components/subscriptions/tests/MultipleSubscriptionsPage.test.jsx
- src/components/subscriptions/tests/MultipleSubscriptionsPicker.test.jsx
- src/components/subscriptions/tests/SubscriptionCard.test.jsx
This feature refactors and uses the MultipleSubscriptionPage that is used for subscription management and uses it on the bulk enrollment page.
With one subscription, users will be redirected automatically. 
With multiple subscriptions, users will be directed to the the page below that allows them to choose their subscription.
The table of courses that users are directed to after redirect / choosing a subscription will now be filtered by that enterprise's subscription.
**Note**: The functionality / text of the original subscription picker (accessed through "Subscription Management" in the nav, should remain unchanged.
Mobile:
> feat: Add subscription selection for bulk enrollment

- src/components/BulkEnrollmentPage/CourseSearch.jsx
- src/components/BulkEnrollmentPage/CourseSearch.test.jsx
- src/components/BulkEnrollmentPage/index.jsx
- src/components/EnterpriseApp/constants.js
- src/components/EnterpriseApp/index.jsx
- src/components/Sidebar/index.jsx
- src/components/subscriptions/MultipleSubscriptionPicker.jsx
- src/components/subscriptions/MultipleSubscriptionsPage.jsx
- src/components/subscriptions/SubscriptionCard.jsx
- src/components/subscriptions/SubscriptionData.jsx
- src/components/subscriptions/SubscriptionDetailPage.jsx
- src/components/subscriptions/SubscriptionDetailsSkeleton.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
- src/components/subscriptions/data/constants.js
- src/components/subscriptions/data/contextHooks.jsx
- src/components/subscriptions/data/hooks.js
- src/components/subscriptions/tests/MultipleSubscriptionsPage.test.jsx
- src/components/subscriptions/tests/MultipleSubscriptionsPicker.test.jsx
- src/components/subscriptions/tests/SubscriptionCard.test.jsx
- src/components/subscriptions/tests/SubscriptionDetailPage.test.jsx
Instead of flashing a 404 while we are loading data, this adds a loading state and loading skeleton to the CourseSearch and SubscriptionDetailsPage
In addition, instead of showing a 404 when the subscription cannot be found, the user is redirected back to the subscription picker (or to their one subscription if they only have one.)
Also changes the route names for these two routes to constants because my constant misspelling of `managment` made my tests fail until I got frustrated enough to make it never happen again.
Skeleton catalog management mobile:
Skeleton subs management mobile:
Desktop catalog management:
Desktop subs management:
> feat: add loading state and redirect to pages that depend on the subscription picker

- src/components/BulkEnrollmentPage/index.jsx
- src/components/EnterpriseApp/constants.js
- src/components/Sidebar/index.jsx
- Renames the bulk enrollment endpoint path from `catalog-management` to `enrollment`
- Renames the titles in a few spots (ie wherever it was present) from "Catalog Management" to "Subscription Enrollment"
> style: rename Bulk Enrollment titles and endpoints

- src/components/BulkEnrollmentPage/CourseSearchResults.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.test.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.test.jsx
- src/components/BulkEnrollmentPage/stepper/constants.jsx
[Jira ticket](https://openedx.atlassian.net/browse/ENT-4423)
Changes:
- new bulk enrollment submit component added to the stepper
- the stepper now calls the license manager API on final submit  
- success and error responses from the Licence Manager are handled according to ticket AC 
- success cases take the user back to the first step and displays a success Toast
- error cases open up a modal alert with a link to support
- closing the modal should keep the user in the current final step
**Bulk Enrollment Submit component**   
- Desktop
- Mobile
**Success Toast**
- Desktop
- Mobile
**Error Alert Modal**
- Desktop
- Mobile
> maint: adding success and failure handling to the new bulk enrollment

- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.test.jsx
- src/components/BulkEnrollmentPage/stepper/constants.jsx
Due to completion of ENT-4451, the support form no longer exists, thus we needed to update this.
We decided on a mailTo link for now (eventually support's help center will have a new form and we may want to link directly to that, but that is completely out of scope for anything Bulk Enrollment related)
*NOTE:* I am waiting on confirmation of the language used in the support email to ensure it is useful to the support team.
- Swaps HyperLink to MailtoLink component in BulkEnrollmentAlertModal.
- As part of this we now pass in the actual error message so that support gets context in the email automatically.
- Fixes an issue with the `ALERT_MODAL_BODY_TEXT` constant as the multiline format was not actually compatible with web browsers so it was displaying as just `NaN`
> fix: swap support form link to mailTo

- src/components/BulkEnrollmentPage/BulkEnrollment.scss
- src/components/BulkEnrollmentPage/stepper/ReviewStep.jsx
Using 2+ columns on mobile is not best for the mobile user experience.
This PR swaps to a single column and displays the boxes/cards on top of each other.
> fix: change rows to column view for mobile on Review step of stepper

- src/components/ReportingConfig/ReportingConfigForm.jsx
**Jira Ticket:** [ENT-4481](https://openedx.atlassian.net/browse/ENT-4481)
Password field on Reporting Configurations screen on portal.edx.org is disabled by default. Enabling/selecting the field and updating the password causes an error. This error is coming for both the email and SFTP delivery report configurations. Please see the attached video to reproduce the issue.
**Acceptance Criteria:**
- Admins can successfully update the password.
**Testing Instructions:**
1. Go to the reporting configuration page of some enterprise customer at `/<enterprise-customer>/admin/reporting`
2. Add/update reporting configuration
3. Select the `Change Password ` checkbox
4. Try to update the password
5. Password should update without any error.
> ENT-4481: Admin Portal: Fix reporting config password field error

- src/components/ReportingConfig/ReportingConfigForm.jsx
Reverts edx/frontend-app-admin-portal#557
Need to revert it as deployment pipeline is failing for some reason, I do not think that this change is causing but need to be sure.
> Revert "ENT-4481: Admin Portal: Fix reporting config password field error"

- src/components/CodeAssignmentModal/BulkAssignFields.jsx
- src/components/CodeAssignmentModal/CodeAssignmentModal.test.jsx
- src/components/CodeAssignmentModal/IndividualAssignFields.jsx
- src/components/CodeAssignmentModal/constants.jsx
- src/components/CodeAssignmentModal/index.jsx
[Jira](https://openedx.atlassian.net/browse/ENT-4476)
**Notify learners checked:**
**Desktop**
**Mobile**
**Notify learners unchecked**
**Desktop**
**Mobile**
This PR:
- Changes wording of modal from `Users` to `Learners`
- Adds a checkbox that toggles the visibility of the email template part of the component
- Checkbox also controls a new boolean `option` parameter fed into the API call to ecommerce on the modal submit
- Unit test to check that the checkbox is rendering
NOTE: discussed with the team and due to the current setup, the modal's submitHandler is untestable so it's currently impossible to test the checkbox's functionality of altering the options used within the handler function. There is currently a jira ticket that is going to deal with this issue and the need for this test …
> feat: allowing users to disable coupon code assignment emails

- src/components/BulkEnrollmentPage/index.test.jsx
- src/containers/Sidebar/Sidebar.test.jsx
Fixes some skipped tests as well as updates the Sidebar to ensure we can correctly test when bulk enrollment _isn't_ present.
> Update & Add Bulk Enrollment Page/Sidebar Tests

- src/components/BulkEnrollmentPage/BulkEnrollment.scss
- src/components/BulkEnrollmentPage/CourseSearchResults.test.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.jsx
- src/components/BulkEnrollmentPage/table/CourseSearchResultsCells.test.jsx
- src/components/EnterpriseApp/_EnterpriseApp.scss
- src/components/EnterpriseApp/index.jsx
- src/components/subscriptions/styles/_SubscriptionManagementPage.scss
[jira](https://openedx.atlassian.net/browse/ENT-4548)
Notes for reviewers:
I've tried to include as many screenshots as possible but best way to fully test is fetching the branch and messing with the screen/window to ensure behaviors are as expected
**Screenshots:**
Desktop scrollable table filling screen, footer at bottom of page
Desktop table filling partial screen, footer at bottom of page
Desktop screen window resized smaller, footer at bottom of page
Mobile step one scrollable table top of page, footer at bottom of page
Mobile step one scrollable table bottom of page, footer at bottom of page
Mobile step two scrollable table top of page, foot at bottom of page
Note:
Tests altered to work for both PST and EST timezones
> feat: making bulk enrollment stepper footer sticky

- src/components/BulkEnrollmentPage/CourseSearchResults.jsx
- src/components/BulkEnrollmentPage/CourseSearchResults.test.jsx
Decision per UX sync meeting:
When more than one partner in algolia data, just display first one, for now
ENT-4608
looks like this with change:
> feat: Add partner column, show first partner only, for now

- src/components/BulkEnrollmentPage/CourseSearchResults.jsx
- src/components/BulkEnrollmentPage/CourseSearchResults.test.jsx
- src/components/BulkEnrollmentPage/helpers.js
- src/components/BulkEnrollmentPage/helpers.test.jsx
- src/components/BulkEnrollmentPage/stepper/AddLearnersStep.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.test.jsx
Selecting a course on the course selection step of the Bulk Enrollment stepper was not triggering the selection options/buttons/tool tip (what are we calling this?). It only triggered when clicking "Next" and then clicking Back to go back to the Course step. It also then would show "0 of N selected" which is not how the rest of the data tables behave.
We believe it is doing this because the underlying react-tables' selection is not refreshing the data until reload because of the way we are partially using selection props here and partially using our overrides.
This PR fixes the following:
- Fixes the selection behaviour by manually specifying selectedFlatRows in CourseSearchResults (this was already present in the AddLearner data table options).
- Removes unnecessary/duplicated props from …
> fix: Bulk Enrollment Selection Option Consistency

- src/components/EnterpriseApp/index.jsx
- src/components/FeatureAnnouncementBanner/FeatureAnnouncementBanner.test.jsx
- src/components/FeatureAnnouncementBanner/index.jsx
- src/data/services/LmsApiService.js
**JIRA Ticket:** [ENT-4507](https://openedx.atlassian.net/browse/ENT-4507)
As an enterprise admin, I want to see relevant product updates pop up in an informational message when I log into my Admin Portal in order that I may receive 'in-application notification' of new developments on edX.
__Acceptance Criteria:__
1. Front end: the ability to see that banner pop up when the admin logs in on the home page of the Admin Portal.
__Testing Instructions:__
1. Install the latest version of  edx-enterprise (note: backend was added in  `edx-enterprise==3.26.0` you need this version to test this PR)
2. Go to the django admin page for admin notification manager `/admin/enterprise/adminnotification/`
2. Add a new notification.
3. Now open admin portal and select any enterprise …
> ENT-4507: feat: Front end work for showing Notification banner in Admin Portal

- src/components/Sidebar/index.jsx
put subscription related items next to each other in sidebar
ENT-4678
> feat: Ordering change of sidebar menu items

- package-lock.json
- package.json
Upgrades `@edx/frontend-build` to v6.0.0 to pull in an upgrade to a NewRelic plugin such that we should now get the "Core web vitals" metrics for this MFE.
> build: upgrade frontend-build to v6

- src/components/CodeAssignmentModal/constants.jsx
- src/components/ReduxFormCheckbox/__snapshots__/ReduxFormCheckbox.test.jsx.snap
- src/components/ReduxFormCheckbox/index.jsx
This PR fixes a frontend bug regarding checkbox not being checked by default even though the value being passed on backend is true. More details on the ticket: https://openedx.atlassian.net/browse/ENT-4569
> fix: nudge reminder checkbox is not checked by default

- src/components/CouponDetails/CouponBulkActions.jsx
- src/components/CouponDetails/CouponBulkActions.test.jsx
- src/components/CouponDetails/FilterBulkActionRow.jsx
- src/components/CouponDetails/helpers.test.jsx
- src/components/CouponDetails/index.jsx
Component is responsible for it's value and options instead of the parent
Allows for easier testing and debugging
There are no visual changes. This fixes a bug I introduced where when you were clicking back to "Remind" from "Redeemed", the value of the BulkAction select did not update as it ought to.
> Move bulk action functionality to bulk action component

- src/components/BulkEnrollmentPage/stepper/ReviewItem.jsx
- src/components/BulkEnrollmentPage/stepper/ReviewItem.test.jsx
- src/components/BulkEnrollmentPage/stepper/ReviewList.jsx
- src/components/BulkEnrollmentPage/stepper/ReviewList.test.jsx
- src/components/BulkEnrollmentPage/stepper/ReviewStep.jsx
We want to add hover text for the delete icon on the Review Step of the Bulk Enrollment Stepper.
I also wanted to make the Aria label text more descriptive to benefit screenreaders better, so I added prop/parameters to differentiate course and learner ReviewItems at least in the context of Aria & title texts.
- removal, altText props
- Update existing `alt=` field on IconButton to use the altText prop.
- Add `title=` attribute to IconButton (it accepts attr passthroughs)
- Add a test for the title (while aria labels show in the dom tree, they aren't actually visible so react testing library's docs state they aren't accessible to screen, but I at least wanted to verify one of these was showing properly and thus the prop passing was working as intended)
**Note:** There are no before/after …
> style: Bulk Enrollment: Review Step: Add title & aria label variables

- src/components/subscriptions/licenses/LicenseAllocationBanner.jsx
- src/components/subscriptions/licenses/LicenseAllocationHeader.jsx
- src/components/subscriptions/tests/licenses/LicenseAllocationBanner.test.jsx
Closes [ENT-4457](https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=628&modal=detail&selectedIssue=ENT-4457)
Adds dismissible alert.
> feat: banner reminding admins to allocate licenses

- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/expiration/SubscriptionExpirationModals.jsx
- src/components/subscriptions/expiration/SubscriptionExpiredModal.jsx
- src/components/subscriptions/expiration/SubscriptionExpiringModal.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationBanner.test.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationModals.test.jsx
When a subscription plan nears its expiration date, admin users are presented warnings in the form of modals and alerts, (some of) which have actions to dismiss them or contact customer support. Example:
Event names:
- `edx.admin_portal.subscriptions.expiration.modal.dismissed`
- `edx.admin_portal.subscriptions.expiration.modal.support_cta.clicked`
- `edx.admin_portal.subscriptions.expiration.alert.dismissed`
- `edx.admin_portal.subscriptions.expiration.alert.support_cta.clicked`
Event Properties:
- `expiration_threshold`: 30/60/120
- `days_until_expiration`: \<some_integer\>
> Adds event tracking for licensee expiration actions in modal and alert

- src/components/BulkEnrollmentPage/index.test.jsx
- src/components/subscriptions/data/hooks.js
- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/expiration/SubscriptionExpirationModals.jsx
- src/components/subscriptions/tests/MultipleSubscriptionsPage.test.jsx
- src/components/subscriptions/tests/TestUtilities.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationBanner.test.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationModals.test.jsx
- src/data/services/LicenseManagerAPIService.js
ENT-4531. This PR: 
Commits can be reviewed separately:
feat(admin_portal): 🚧 Swap use of subscription API for customer-agreement API since it's a superset of the subscription data. 
feat(admin_portal): ✨ Apply customer agreement 'disable_expiration_notification' setting to portal messages
> feat(admin_portal): ENT-4531 Apply customer agreement 'disable_expiration_notification' setting to portal messages

- src/components/subscriptions/SubscriptionDetailContextProvider.jsx
- src/components/subscriptions/SubscriptionDetails.jsx
- src/components/subscriptions/data/hooks.js
- src/components/subscriptions/tests/TestUtilities.jsx
...when there are no allocated licenses but there are revoked licenses.
ENT-4804
This also fixes a defect I noticed, where "Invite Learners" wasn't rendering in the All Users tab after inviting a learner - you'd have to do a full page refresh to see it.  I fixed this by adding a `forceRefresh()` function to the `SubscriptionDetailContext` context, which is now called by the `InviteLearnersButton.onSuccess()` handler (in addition to the forceRefresh of the subscription context for the entire agreement).
Testing:
* Create a new subscription plan
* Assign and then revoke a single license.
* On the plan details page, the "Invite Learners" button should still render at the top of the page when you're on the "All Users" tab (this is the fix).
> feat: the invite learners button should render in the plan detail page

- src/components/subscriptions/data/hooks.js
- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/expiration/SubscriptionExpirationModals.jsx
- src/components/subscriptions/expiration/SubscriptionExpiringModal.jsx
- src/components/subscriptions/tests/TestUtilities.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationBanner.test.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationModals.test.jsx
The purpose of this change is to make our subscription expiration modal/alert reminders to use a new field `netDaysUntilExpiration` coming from `/api/v1/customer-agreement/`, to better alert our users. 
Users will no longer be alerted if they have an upcoming/pending  subscription. They will only be notified about expiration when when the the last expiration date is within the expiration notification threshold (120 days).
Screenshot below show two plans, named `expired sub plan` and `expires later`. 
If we navigate to `expired sub plan` detail view you will see no alert is being showed because we still have an ongoing plan `expires later`.
If both plans were expired or close to expiration however, a warning would be shown.
> Subscription Management now using customer-agreement api

- src/components/subscriptions/SubscriptionDetails.jsx
- src/components/subscriptions/tests/SubscriptionDetails.test.jsx
- src/components/subscriptions/tests/TestUtilities.jsx
[Link to the associated ticket
](https://openedx.atlassian.net/browse/ENT-3957)
Adding purchase date on subscription details as shown in miro.
Adding purchase date to subscription plan details (if needed).
> feat: add purchase date to plan details

- src/components/subscriptions/SubscriptionDetails.jsx
- src/components/subscriptions/data/constants.js
- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/licenses/LicenseActions.jsx
- src/components/subscriptions/tests/SubscriptionDetails.test.jsx
- src/components/subscriptions/tests/TestUtilities.jsx
- src/components/subscriptions/tests/licenses/LicenseActions.test.jsx
Ticket: [ENT-4837](https://openedx.atlassian.net/browse/ENT-4837)
Reads the `is_locked_for_renewal_processing` field from license-manager's `SubscriptionPlanSerializer` to determine whether admin actions (i.e., inviting learners, revoking license) are disabled/present.
1. Ensure `is_locked_for_renewal_processing` is returned by the `subscriptions` API endpoint in license-manager.
2. In license-manager, create a subscription plan that expires within a couple hours and an associated subscription plan renewal that has an effective date of shortly after the existing subscription plan (within the next 12 hours).
3. Load the subscription detail route; observe the "Invite learners" button is disabled and the "Revoke" action is removed from rows of users who have an assigned license. Related, see …
> fix: disable admin actions on Subscription Plan locked for renewal processing

- src/components/LicenseRevokeModal/index.jsx
- src/containers/LicenseRevokeModal/LicenseRevokeModal.test.jsx
- src/data/actions/licenseRevoke.js
- src/data/services/LicenseManagerAPIService.js
Deprecating the /revoke and moving towards /bulk-revoke to remove redundancy. New endpoint will be used for the new table as well.
https://openedx.atlassian.net/browse/ENT-4737
> chore: use bulk-revoke endpoint to revoke licenses

- src/components/CodeRevokeModal/index.jsx
- src/containers/CodeRevokeModal/CodeRevokeModal.test.jsx
- src/containers/CodeRevokeModal/index.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-4886
Actual: Revoke emails do not redirect to learner portal if learner portal is enabled in enterprise configuration.
Expected: It should redirect to learner portal if learner portal is enabled, otherwise to B2B search page.
> fix: revoke emails should also redirect to learner portal

- .github/workflows/ci.yml
- README.md
- package-lock.json
- package.json
"The majority of the edX micro-frontends and JS libraries are using Codecov instead of Coveralls these days. Coveralls has been down all morning today (blocking the release of a patch version in this repository), which was inspiration for getting Paragon to use Codecov instead." - Adam Stanckiewicz
> chore: switch to codecov

- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/expiration/SubscriptionExpiringModal.jsx
- src/components/subscriptions/tests/expiration/SubscriptionExpirationBanner.test.jsx
https://openedx.atlassian.net/browse/ENT-4883
- Fix banner behavior to match https://miro.com/app/board/o9J_kglry8E=/?moveToWidget=3074457359742106696&cot=14
on subscription details
- Fix typo in expiration modal
> fix: show correct expiration banner on subscription details page

- src/components/BulkEnrollmentPage/stepper/AddCoursesStep.jsx
- src/components/BulkEnrollmentPage/stepper/AddCoursesStep.test.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.test.jsx
- src/components/BulkEnrollmentPage/stepper/DismissibleCourseWarning.jsx
- src/components/BulkEnrollmentPage/stepper/constants.jsx
For ticket number [ENT-5005](https://openedx.atlassian.net/browse/ENT-5005), adding in a warning message for admins who are attempting to enroll in courses over the recommended course limit
> feat: add course limit warning to admins

- package-lock.json
- package.json
- src/components/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap
- src/components/ForbiddenPage/__snapshots__/ForbiddenPage.test.jsx.snap
- src/components/SupportPage/__snapshots__/SupportPage.test.jsx.snap
- src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementModalHook.js
- src/components/subscriptions/licenses/LicenseManagementTable/LicenseManagementTableActionColumn.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/LicenseManagementTableBulkActions.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/index.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/tests/LicenseManagementTableActionColumn.test.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/tests/LicenseManagementTableBulkActions.test.jsx
- src/containers/SaveTemplateButton/__snapshots__/SaveTemplateButton.test.jsx.snap
This change contains no visual changes. 
In the subscription detail page, if admins selected users on the table and clicked reminded or revoked user licenses actions, their selection would be remain. This change:
1. Updates paragon library dependency
2. Rearranges components so that they are under the `DataTable` context umbrella allowing them to use the `clearSelection` function of the `DataTableContext` provider. 
3. Updated some tests and added new tests to cover some of the modal state management that shifted around.
Now revoking and reminding users will clear the table selection the user may have had.
Cloeses [ENT-5060](https://openedx.atlassian.net/browse/ENT-5060)
- [] Ensure to attach screenshots
- [] Ensure to have UX team confirm screenshots
> Table Actions Clear Selection

- src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementRemindModal.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementRevokeModal.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRemindModal.test.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRevokeModal.test.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/LicenseManagementTableActionColumn.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/LicenseManagementTableBulkActions.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/index.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/tests/LicenseManagementTableActionColumn.test.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/tests/LicenseManagementTableBulkActions.test.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/tests/index.test.jsx
- src/eventTracking.js
[Close ENT-5062](https://openedx.atlassian.net/browse/ENT-5062) 
This PR includes no visual changes.
Adds segment events to the subscription management table and put event names all in one place.
All bulk action events have this payload: 
`{ selected_users: <num>, all_users_selected: <bool> }`
Clicking on bulk remind or revoke buttons after selecting users sends:
* `edx.ui.admin_portal.subscriptions.table.remind.bulk.click`
OR
* `edx.ui.admin_portal.subscriptions.table.revoke.bulk.click`
Clicking bulk actions brings up the corresponding action modal with two buttons, cancel and submit. These buttons map to the fallowing event names:
* `edx.ui.admin_portal.subscriptions.table.remind.bulk.submit`
* `edx.ui.admin_portal.subscriptions.table.remind.bulk.cancel`
OR
* …
> Subscription management table events

- src/components/LmsConfigurations/BlackboardIntegrationConfigForm.jsx
When available, display an OAuth Client Authorization link in the Blackboard self-service screen of the admin portal. 
Relies on https://github.com/edx/edx-enterprise/pull/1425
[ENT-4389](https://openedx.atlassian.net/browse/ENT-4389)
> feat: OAuth Auth link for Blackboard Self-Service

- package-lock.json
- package.json
- src/components/settings/SettingsAccessTab/SettingsAccessLinkManagement.jsx
- src/components/settings/SettingsAccessTab/tests/DateCreatedTableCell.test.jsx
- src/components/settings/SettingsAccessTab/tests/LinkTableCell.test.jsx
- src/components/settings/SettingsAccessTab/tests/StatusTableCell.test.jsx
- src/components/settings/SettingsAccessTab/tests/UsageTableCell.test.jsx
- src/components/settings/SettingsAccessTab/tests/__snapshots__/DateCreatedTableCell.test.jsx.snap
- src/components/settings/SettingsAccessTab/tests/__snapshots__/LinkTableCell.test.jsx.snap
- src/components/settings/SettingsAccessTab/tests/__snapshots__/StatusTableCell.test.jsx.snap
- src/components/settings/SettingsAccessTab/tests/__snapshots__/UsageTableCell.test.jsx.snap
- src/components/subscriptions/licenses/LicenseManagementTable/index.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/tests/index.test.jsx
- src/components/subscriptions/tests/TestUtilities.jsx
Upgrades Paragon to 17.5.0 and adds `isLoading` prop to `DataTable` for universal link loading and subscription management detail page loading.
> fix: add isLoading prop to DataTable

- src/components/SamlProviderConfiguration/index.jsx
- src/components/SamlProviderConfiguration/index.test.jsx
ENT-4286
Once SAML Provider Config is saved: shows the two urls: SP Metadata url (including tpa_hint), and Test link ( either the learner portal url or the dashboard, with tpa_hint)
I did not invest in adding tests other than manual test because we are going to rewrite the UIs in short order.
I also did not invest in CSS and layout for the new links added since this will change/be redone soon
> feat: add SP metadata url and test link on SAML provider config form

- src/components/SamlProviderConfiguration/index.jsx
- src/components/SamlProviderConfiguration/utils.js
- src/components/SamlProviderConfiguration/utils.test.js
When forming metadata url, the tpa_hint parameter need not contain the saml- prefix, unlike what we do for the SSO link like test link.
This is because [the backend](https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/common/djangoapps/third_party_auth/views.py#L60) simply use tpa_hint as the saml idp slug, and does not expect a saml- prefix.
Added automated test for util function that generates the urls: which is used as such
```
const { testLink, spMetadataLink } = createSAMLURLs({
configuration,
idpSlug,
enterpriseSlug,
learnerPortalEnabled,
});
```
After this change, verified in admin portal the metadata url works
> fix: don't need saml- prefix for metadata url

- src/components/CodeAssignmentModal/index.jsx
fixes ENT-5194 - an issue where learners assigned codes
are not getting linked as pending learners to an enterprise.
https://openedx.atlassian.net/browse/ENT-5194
Also see https://openedx.atlassian.net/wiki/spaces/SOL/pages/3311730754/ENT-5194+Learners+not+linked for investigation that led to this change.
> fix: check if list length is truthy before creating pending users.

- .github/workflows/ci.yml
This allows github workflow to honor the nvmrc when choosing node/npm versions
if .nvmrc has `12` for example, it basically runs `nvm use` and fetches the correct (latest minor release of) nodejs and npm version running the rest of the github action workflow
To verify, check the 'checks' screen for this PR it will show
```
Computing checksum with sha256sum
Checksums matched!
Now using node v12.22.9 (npm v6.14.15)
Creating default alias: default -> 12.22.9 (-> v12.22.9 *)
```
or similar
> ci: add nvmrc detection/use to github workflow ENT-4178

- src/components/Admin/Admin.test.jsx
- src/components/Admin/index.jsx
- src/components/settings/index.jsx
https://user-images.githubusercontent.com/49611774/152346357-3a4674b5-07c7-4bb9-8cb0-dc9ab7aaa8c9.mov
> fix: add logic to not display reset filter on ordering

- src/components/subscriptions/data/hooks.js
- src/components/subscriptions/tests/hooks.test.jsx
Only pass `search` query parameter to API requests when there is a valid search query. This avoids passing `?search=null` to the request, which returns an empty list despite having licenses associated with the subscription plan.
> fix: only pass search param to API if has value

- package-lock.json
- src/components/SubsidyRequestManagementTable/tests/__snapshots__/SubsidyRequestManagementTable.test.jsx.snap
- src/components/settings/SettingsLMSTab/ConfigError.jsx
- src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx
- src/components/settings/SettingsLMSTab/LMSCard.jsx
- src/components/settings/SettingsLMSTab/LMSConfigPage.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx
- src/components/settings/SettingsLMSTab/index.jsx
- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/ConfigError.test.jsx
- src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx
- src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx
- src/components/settings/SettingsLMSTab/tests/LmsConfigPage.test.jsx
- src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx
- src/components/settings/SettingsTabs.jsx
- src/components/settings/data/constants.js
- src/components/settings/settings.scss
- src/components/settings/tests/SettingsTabs.test.jsx
- src/data/services/LmsApiService.js
- src/utils.js
- src/utils.test.js
New features:
- LMS config settings page now fetches customer config data on load
- submitting a config or toggling a config will trigger a re-fetch 
- existing configurations are displayed as cards above the creation cards
- if and only if configs exists, creation cards are hidden behind a button
- navigating from a config form back to the landing page, will reset the show create cards buttons (if there are existing configs) 
- existing configuration cards display 1) channel type 2) display name 3) config status
- user is able to toggle completed configs from active to inactive
- basic error handling added to toggle API call
- user is able to edit existing config information
- clicking edit will bring the user to the config form with all existing fields automatically filled out
- if the …
> FEAT: LMS config page now displays existing configs

- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/index.jsx
Adds missing `data-hj-suppress` to the email column in the `LicenseManagementTable` component such that the email PII gets masked in Hotjar.
> fix: add data-hj-suppress to email in license data table

- src/components/CodeSearchResults/CodeSearchResultsTable.jsx
No longer passing `page: null` in the options for `fetchCodeSearchResults`.
> Only pass page option if param exists

- src/components/settings/SettingsLMSTab/LMSCard.jsx
- src/components/settings/SettingsLMSTab/index.jsx
- src/components/settings/SettingsLMSTab/tests/LmsConfigPage.test.jsx
- src/components/settings/SettingsTabs.jsx
- src/components/settings/settings.scss
- src/data/reducers/portalConfiguration.js
NEEDED BACKEND PR/BRANCH IN ORDER TO TEST:
https://github.com/openedx/edx-enterprise/pull/1465
This PR adds:
- a new LMS api service fetch method to a new backend endpoint that returns if a customer still needs to set up an IDP config.
- If the api fetch method returns `True`, 
- renders an alert modal at the top of the LMS config settings page that has a redirect to the SSO settings tab
- disables creation cards and display creation cards button on the LMS config page
> feat: LMS config settings page checks for IDP configs

- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx
Issue: when authorize is clicked on the LMS config settings page form, a custom hook starts making API calls ever second to the enterprise backend to validate that the user has completed the oauth process. Tests were flaky because it wasn't guaranteed that the hook would be called or not in the test, and the result of that hook running would change the state of the page. I've added a delay each time we initiate the authorization process in the tests and updated the expected state to be the expected results post hook run.
> fix: properly waiting for and validating effects of custom hooks in lms tests

- src/components/CodeManagement/ManageRequestsTab.jsx
- src/components/settings/SettingsAccessTab/SettingsAccessLinkManagement.jsx
- src/components/settings/SettingsAccessTab/index.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessLinkManagement.test.jsx
- src/components/settings/SettingsAccessTab/tests/TestUtils.jsx
- src/components/settings/data/hooks.js
- src/components/subscriptions/SubscriptionSubsidyRequests.jsx
- src/components/subsidy-request-management-alerts/NoAvailableCodesBanner.jsx
- src/components/subsidy-request-management-alerts/NoAvailableLicensesBanner.jsx
- src/components/subsidy-request-management-alerts/tests/NoAvailableCodesBanner.test.jsx
- src/components/subsidy-request-management-alerts/tests/NoAvailableLicensesBanner.test.jsx
- We want to account for only active plans in these places
- Clean ups
> fix: use subscription expirate date instead of agreement net days

- src/components/EnterpriseApp/index.jsx
- src/components/settings/SettingsTabs.jsx
- src/components/settings/tests/SettingsTabs.test.jsx
- We need to show the settings page for bnr, shuffled the logic to show settings page but hide tabs based on feature flags
> feat: hide settings tab based only on feature flag

- src/components/settings/SettingsLMSTab/ConfigError.jsx
- src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx
- src/components/settings/SettingsLMSTab/tests/ConfigError.test.jsx
- src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx
- src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx
- src/components/settings/SettingsLMSTab/utils.js
- SAP config’s Company ID field needs to not validate numbers only and instead should allow strings
- All string fields need to have a char limit validation similar to display name’s with a 255 limit
- Moodle’s password field needs to be obscured like other password fields
- Degreed2 config forms need to include an optional token fetch base url with a tool tip stating that if one isn’t supplied then we will use the degreed base url provided
- Degreed2 backend should not require the config to have the optional token fetch base url 
- Toggle and Delete error message should read configuration instead of config, and remove “later”
- “Try Again” button should also be removed from error modals
> ENT-5573: Config bug bash fixes

- src/components/settings/SettingsLMSTab/ConfigError.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx
- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx
- src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx
- src/components/settings/data/constants.js
- src/data/services/LmsApiService.js
- Error modal’s contact support buttons (for both modals related to existing config kebab menu usage and config form usage) should link to   and open in a new tab
- The url used for deleting Canvas configs needs to be fixed /Canvas/ => /canvas/
- For all channels, config forms should only set the config to inactive when creating a new config    
- currently `active=false` is being appended to all payloads
> fix: bug fixes

- package-lock.json
- package.json
- src/components/SubsidyRequestManagementTable/tests/CourseTitleCell.test.jsx
- src/components/subsidy-request-configuration/SubsidyRequestConfigurationContextProvider.jsx
- src/components/subsidy-request-configuration/data/hooks.js
- src/components/subsidy-request-configuration/data/tests/hooks.test.js
- src/data/services/EnterpriseAccessApiService.js
- src/data/services/tests/EnterpriseAccessApiService.test.js
- invalidate cache after updating subsidy request configuration
- relies on fix in https://github.com/openedx/frontend-platform/pull/311
- fix test that was using waitFor without await
> fix: invalidate cached subsidy request configuration after toggle

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
- src/components/ReportingConfig/index.jsx
> fix: pass enterprise customer uuid to backend when we create a new report configuration

- src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx
- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx
- src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx
- LMS config settings page now validates existing configs when editing on load
> chore: validating existing LMS configs on load in the settings page

- src/components/settings/SettingsAccessTab/index.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessTab.test.jsx
https://openedx.atlassian.net/browse/ENT-5655
When B&R is enabled for a customer configuration, show a danger banner _on the settings page_ if no subsidies of the configured type are available:
> WIP feat: Add no available license/code banner to the settings page

- src/components/settings/SettingsAccessTab/SettingsAccessSubsidyRequestManagement.jsx
- src/components/settings/SettingsAccessTab/index.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessSubsidyRequestManagement.test.jsx
Right now admins have no way of turning off subsidy requests since it auto-toggles every time the setting page loads.
This fixes that by turning on subsidy requests automatically only if disabled becomes false (when an access channel gets turned on).
Removed unneeded subsidyRequestsEnabled check.
> fix: fix auto toggling subsidy requests everytime page is loaded

- src/components/ConfirmationModal/ConfirmationModal.test.jsx
- src/components/ConfirmationModal/index.jsx
- src/components/EnterpriseApp/EnterpriseApp.test.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/ProductTours/BrowseAndRequestTour.jsx
- src/components/ProductTours/tests/BrowseAndRequestTour.test.jsx
- src/components/Sidebar/index.jsx
- src/components/settings/SettingsAccessTab/SettingsAccessConfiguredSubsidyType.jsx
- src/components/settings/SettingsAccessTab/SettingsAccessSubsidyTypeSelection.jsx
- src/components/settings/SettingsAccessTab/index.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessConfiguredSubsidyType.test.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessSubsidyTypeSelection.test.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessTab.test.jsx
- src/components/settings/SettingsContext.jsx
- src/components/settings/SettingsTabs.jsx
- src/components/settings/data/constants.js
- src/components/settings/tests/SettingsContext.test.jsx
- src/components/settings/tests/SettingsTabs.test.jsx
- src/components/subsidy-requests/data/hooks.js
- src/containers/EnterpriseApp/index.jsx
- src/containers/Sidebar/Sidebar.test.jsx
- src/containers/Sidebar/index.jsx
https://openedx.atlassian.net/browse/ENT-5730
- Allow enterprises to configure subsidy type for browse and request **once**
- Hide settings page if there are no visible tabs
> feat: allow enterprise to select subsidy type for bnr

- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- we no longer using enterprise uuid so we can disambiguate which config is used in the case the customer has more than 1 configured
- [ENT-5610](https://2u-internal.atlassian.net/browse/ENT-5610)
> fix: use config uuid for canvas oauth state

- src/components/settings/SettingsAccessTab/data/utils.js
- src/components/settings/SettingsAccessTab/index.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessTab.test.jsx
- src/components/settings/SettingsTabs.jsx
https://2u-internal.atlassian.net/browse/ENT-5851
Replaces"subsidy" with "code"/"subscription license" and links to the appropriate "Manage Requests" route based on the configured request subsidy type.
> feat: replace subsidy with more descriptive labels for code/subs mgmt 

- package-lock.json
- package.json
- src/components/settings/SettingsAccessTab/index.jsx
Column size adjustment so customers don't correlate the contact support button with turning B&R on.
Upgrade paragon to fix dropdown menu icon.
> fix: shrink header column in settings access tab

- package-lock.json
- src/components/EnterpriseApp/index.jsx
- src/components/Sidebar/IconLink.jsx
- src/components/Sidebar/IconLink.test.jsx
- src/components/Sidebar/_Sidebar.scss
- src/components/Sidebar/index.jsx
- src/components/learner-credit-management/LearnerCreditManagement.jsx
- src/components/learner-credit-management/index.js
- src/containers/Sidebar/Sidebar.test.jsx
- src/containers/Sidebar/__snapshots__/Sidebar.test.jsx.snap
Adds a "Learner Credit Management" tab to the sidebar navigation that links to a new shell page with the hero/title. It is behind the `FEATURE_LEARNER_CREDIT_MANAGEMENT` feature flag.
Also ran `npx browserslist --update-db` which updated package-lock.json.
> feat: add Learner Credit Management tab and page

- src/components/settings/SettingsSSOTab/NewSSOConfigForm.jsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
> fix: adding base error handling

- src/components/settings/SettingsSSOTab/SSOStepper.jsx
- src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.jsx
- src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.test.jsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
- src/components/settings/data/constants.js
Fixing dual entry for SSO bug, along with fixing a bug that still allows for advancement tot he next page after incorrectly entering fields. 
https://2u-internal.atlassian.net/browse/ENT-5904
> fix: fixing config info entry bug

- src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- src/components/settings/SettingsLMSTab/index.jsx
- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx
- src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx
- src/components/settings/SettingsLMSTab/tests/LmsConfigPage.test.jsx
- src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx
- src/components/settings/SettingsLMSTab/utils.js
- Removing automatic form submission if config has a refresh token (I don't know why this was thing in the first place)
- fixing canvas config id being used instead of uuid for auth completion urls
- requiring re-authorization if blackboard or canvas fields are changed
- fixing util function bug
> fix: cleaning up self serve integration config settings page

- src/components/ContactCustomerSupportButton/index.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/learner-credit-management/LearnerCreditAggregateCards.jsx
- src/components/learner-credit-management/LearnerCreditManagement.jsx
- src/components/learner-credit-management/OfferUtilizationAlerts.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/OfferUtilizationAlerts.test.jsx
- src/data/services/EnterpriseDataApiService.js
* Includes warning alert for low remaining balance (> 75% utilization AND > $100 remaining)
* Includes error alert for no remaining balance (<= $100 remaining)
* Adds color variants for annotated progress bar depending on utilization.
* Note: copy/alert behavior/etc. is subject to change pending review with UX.
* TODO:
> feat: alerts and color variants for low/no funds remaining in Learner Credit Mgmt

- src/components/settings/SettingsLMSTab/LMSConfigPage.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx
- src/components/settings/SettingsLMSTab/index.jsx
- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx
Bug fix on current config data after a config is created during the authorization step. Clicking the authorization button triggers a creation of an LMS integration config on the backend. Since the page doesn't trigger a success signal until confirming the config has a refresh token, and the process of retrieving the refresh token can potentially fail, the current config data needs to be set between the time the new config is created and the page has confirmed the refresh token exists and triggers the success signal.
> chore: current config status during auth

- src/components/settings/SettingsSSOTab/SSOConfigConfiguredCard.jsx
- src/components/settings/SettingsSSOTab/SSOStepper.jsx
- src/components/settings/SettingsSSOTab/steps/SSOConfigIDPStep.jsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6050"
- methods in the SSO stepper that used the `sendData` function were not properly waiting for the function to return, causing the page to think an error had occurred / causing the current provider config state to be lost
- editing fields in the configure step causes the backend to set configs to inactive
- bug with polling the backend to check for a validated config was erroneously returning true when false
- types with the IDP step
> fix: configure step bug fixes and typo fixes

- src/components/settings/SettingsSSOTab/SSOStepper.jsx
- src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.jsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
- src/components/settings/SettingsSSOTab/testutils.js
- src/components/settings/data/constants.js
https://2u-internal.atlassian.net/browse/ENT-6065
If the user is using SAP as an IDP, we require specific custom configure attributes + have to designate the config as a SAP IDP config on the backend. This PR adds the ability to designate SAP as the IDP in the third, configure step of the SSO self service settings flow.
> feat: adding SAP IDP support to self service settings

- src/components/settings/SettingsSSOTab/SSOStepper.jsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6207
adding default values
```* Debug Mode
* Skip hinted dialog
* Skip registration form
* Skip email verfication
* Send to registration first
* Automatic metadata refresh with metadata URL specified
```
to form data when creating/updating provider config forms in the self service settings page
Tested locally that both old and new forms update with the new default values
> chore: adding default provider config values to self service

- src/components/EnterpriseApp/EnterpriseApp.test.jsx
- src/components/EnterpriseApp/index.jsx
https://2u-internal.atlassian.net/browse/ENT-3600
- Add unified logic to redirect to 404 page on bad enterprise slug
- Use pre-existing component to render 404 page
- Checks enterprise existence before provider renders
> feat: Render 404 page on non-existent enterprise-slug

- src/components/learner-credit-management/LearnerCreditDisclaimer.jsx
- src/components/learner-credit-management/LearnerCreditManagement.jsx
- src/components/learner-credit-management/tests/LearnerCreditDisclaimer.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6262
Associated Figma: https://www.figma.com/file/glKHoHBACvTw2oeKs2TO1O/Offers?node-id=378%3A27432
Added disclaimer message along with icon on LCM page
Passes dynamic date to render within the disclaimer
- [ X] Ensure adequate tests are in place (or reviewed existing tests cover changes)
- [ X] Ensure to attach screenshots
- [ X] Ensure to have UX team confirm screenshots
> feat: Learner Credit Disclaimer message added

- src/components/ProductTours/ProductTours.jsx
- src/components/ProductTours/constants.js
- src/components/ProductTours/data/hooks.js
- src/components/ProductTours/portalAppearanceTour.jsx
- src/components/ProductTours/tests/ProductTours.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6100
Added product tour for portal appearance. Placed behind portal appearance feature flag.
Notes for testing locally- if you missed the pop up you will most likely have to remove the `portal appearance seen` cookie which will be listed under localhost cookies. 
(Don't mind the cat logo)
> feat: added new product tour for portal appearance feature

- src/components/ReportingConfig/index.jsx
- src/data/services/EnterpriseCatalogApiService.js
- src/data/services/LmsApiService.js
(2 of 5) for closes https://github.com/openedx/public-engineering/issues/61
Replace this [usage](https://github.com/openedx/frontend-app-admin-portal/blob/master/src/data/services/LmsApiService.js#L254-L256) with corresponding to the **enterprise-catalog** service
> FC-0001: Replace usages enterprise_catalog Enterprise API V1

- src/data/validation/email.js
- src/data/validation/email.test.js
On the Admin portal Subscription management screen, entering a list of emails with any whitespace around individual emails will show errors.  This change disregards the extraneous whitespace, while still validating proper email structure.
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-4739)
> fix: Bulk email validator handles whitespace padding

- src/components/analytics/AnalyticsCharts.jsx
- src/components/analytics/AnalyticsPage.test.jsx
We are switching from Tableau to Plotly and this PR adds a maintenance page. This page will be shown when the license expires for Tableau.
> feat: add maintenance page for tableau analytics

- src/components/settings/SettingsSSOTab/NewSSOConfigForm.jsx
- src/components/settings/SettingsSSOTab/SSOStepper.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-6012)
After inputting incorrect Identity Provider information, a warning panel pops up with a non-functional dismiss button.  The 'Next' button can no longer be clicked, even if the user corrects the information
https://user-images.githubusercontent.com/322346/197076145-f547cf30-9062-49ea-a985-31b70d0b0e1e.mov
After inputting incorrect Identity Provider information, a warning panel pops up (with no dismiss button).  The 'Next' button can be clicked, and the workflow will progress if the user corrects the information.
https://user-images.githubusercontent.com/322346/197075955-6856daf4-6d9c-4bc9-bb43-96253f765259.mov
> SSO Config: Can hit Next after inputting incorrect idP

- src/components/EnterpriseApp/EnterpriseAppContextProvider.test.jsx
- src/components/EnterpriseApp/data/hooks/useEnterpriseCuration.js
- src/components/EnterpriseApp/data/hooks/useEnterpriseCuration.test.js
> fix: only get/create enterprise curation config if feature flag enabled

- src/components/EnterpriseApp/data/hooks/useEnterpriseCuration.js
Ensures the loading state gets reset to `false` if `FEATURE_CONTENT_HIGHLIGHT` is disabled.
> fix: ensure enterprise curation config loading state is set to false if feature is disabled

- package-lock.json
- package.json
- src/components/NewFeatureAlertBrowseAndRequest/NewFeatureAlertBrowseAndRequest.test.jsx
- src/components/NewFeatureAlertBrowseAndRequest/index.jsx
- src/components/ProductTours/ProductTours.jsx
- src/components/ProductTours/browseAndRequestTour.jsx
- src/components/ProductTours/data/hooks.js
- src/components/ProductTours/data/utils.js
- src/components/ProductTours/highlightsTour.jsx
- src/components/ProductTours/learnerCreditTour.jsx
- src/components/ProductTours/portalAppearanceTour.jsx
- src/components/ProductTours/tests/ProductTours.test.jsx
- src/components/subscriptions/expiration/SubscriptionExpiringModal.jsx
- src/data/constants/index.js
- src/setupTest.js
https://2u-internal.atlassian.net/browse/ENT-6529
Replaces cookies with `localStorage` so it doesn't need to have an explicit expiration, as is required by cookies.
> Replace cookies with `localStorage` for alerts and product tour dismissal

- src/components/ContentHighlights/ContentHighlightCardContainer.jsx
- src/components/ContentHighlights/ContentHighlightsCardItemsContainer.jsx
- src/components/ContentHighlights/HighlightSetSection.jsx
Add image card cap object data reference to highlight set card (previously hardcoded picsum image)
> fix: Highlight set card image cap fixed

- src/components/ContentHighlights/HighlightStepper/ContentConfirmContentCard.jsx
- src/components/ContentHighlights/HighlightStepper/HighlightStepperConfirmContent.jsx
- src/components/ContentHighlights/HighlightStepper/tests/HighlightStepperConfirmContent.test.jsx
- src/components/ContentHighlights/data/constants.js
Adam:
Added ability to sort returned Algolia search results based on the user selection order
Hamzah:
Added a test to verify expected behavior
> fix: persist selection ordering for highlights

- src/components/ContentHighlights/ContentHighlightCardItem.jsx
- src/components/ContentHighlights/HighlightStepper/HighlightStepperSelectContentSearch.jsx
- src/components/ContentHighlights/HighlightStepper/SelectContentSearchPagination.jsx
Quick fix that moves datatable format into a single component in preparation for the paragon pagination fix
Also adds conditional for variant in card items to account for programs and pathway card styling.
> fix: formats datatable footer into single component w/ actionRow

- package-lock.json
- package.json
- src/components/CodeManagement/tests/__snapshots__/ManageCodesTab.test.jsx.snap
- src/components/ContentHighlights/HighlightStepper/HighlightStepperSelectContentSearch.jsx
- src/components/ContentHighlights/data/constants.js
Verified Paragon UI changes for highlights when upgrading from `20.21.1` to `20.24.1`
Updated testEnterpriseId constant to one with a more extensive catalog for a comprehensive dataset for local environments. 
Removed filter criteria from algolia search to return values that represent programs and pathways, not just courses.
> chore: upgrade to latest paragon, removed filter criteria and updated test Id constant

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
***Description***
The report configuration UI asks for a Password even when PGP key is provided.  See the screenshot attached. 
The expected behavior is that if a PGP is provided the password should not be mandatory in the UI.
***Solution***
Make the PGP key field required. if the PGP key or password is present and all other requirements are fulfilled the form will be submitted successfully. Also, write a test case for it.
***After Changing***
> fix: password is required when PGP is provided and test

- __mocks__/react-instantsearch-dom.jsx
- src/components/BulkEnrollmentPage/CourseSearchResults.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.jsx
- src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.test.jsx
- src/components/BulkEnrollmentPage/stepper/ReviewStepCourseList.jsx
- src/components/BulkEnrollmentPage/stepper/ReviewStepCourseList.test.jsx
For bulk enrollment, ensure the course run ID is passed instead of the course key. To do this, we take the Algolia results from the "Review step" and mutate the `selectedCourses` array in the `BulkEnrollContext` reducer to include the Algolia metadata such that `BulkEnrollmentSubmit` has access to `advertisedCourseRun` to get its course run key.
> fix: pass course run id instead of key for bulk enroll

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
Adding file compression option on Reporting Form. Initially, that option was only enabled by the Django admin. But now users will be able to Enable compression from UI.
Additionally, validation on the compression box is done from the backend to make it secure.
> feat: add file compression check and test

- src/components/ReportingConfig/ReportingConfigForm.jsx
***Description***
when someone creates an EnterpriseCustomerReportingConfiguration (ECRC) using the delivery_method email and tries to update the delivery_method to sftp then sftp password is not required due to which that report could save in DB without that password. So when someone tried to inactivate that report from Django admin then 500 error occurred.
***Solution***
I disable the deliveryMethod field and applied validation on delivery_method in the backend. When someone tries to bypass this field, a proper message will be shown to the user that you cannot update the delivery method. 
here is the ticket [ENT-1689](https://2u-internal.atlassian.net/browse/ENT-1689)
> fix: disable delivery_method while updating report

- src/components/ContentHighlights/HighlightStepper/tests/ContentHighlightStepper.test.jsx
- src/components/ContentHighlights/data/hooks.js
Ticket: https://2u-internal.atlassian.net/browse/ENT-6729
Resets title validation flag when user exits the create content highlights stepper.
> fix: reset title validation

- src/components/settings/SettingsAccessTab/SettingsAccessGenerateLinkButton.jsx
- src/components/settings/SettingsAccessTab/SettingsAccessLinkManagement.jsx
- src/components/settings/SettingsAccessTab/index.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessGenerateLinkButton.test.jsx
- src/components/settings/SettingsAccessTab/tests/SettingsAccessLinkManagement.test.jsx
- src/components/settings/data/constants.js
The expiration date for a Universal Link was formerly tied to the expiration date of a coupon. This change removes that logic, and corresponds to the new default expiration date on the back-end ([EnterpriseCustomerInviteKey](https://github.com/openedx/edx-enterprise/pull/1769) will expire in 365 days). There is also now a limit of 100 links per enterprise customer. 
An alert is shown if the customer has reached 100 links, and the `Generate Link` button is disabled:
> chore: remove logic to set expiration date on universal link

- src/components/settings/SettingsAccessTab/index.jsx
Remove the sentence "Browsing on demand will expire at the end of your latest purchase" from the `Settings` page.
Before:
After:
> chore: remove browsing on demand expiration statement

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
***Problem***: 
When we try to update a configuration report then the password is required even if I did not want to update it.
***Solution***: 
I make the password field conditionally required while updating a report.
> fix: do not require change password to change reporting configuration

- src/components/settings/SettingsTabs.jsx
- src/components/settings/data/constants.js
- src/components/settings/tests/SettingsPage.test.jsx
When clicking Settings, the "Portal Appearance" tab is now the default, and the corresponding tab is furthest to the left.
> chore: portal appearance tab appears by default

- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/LearnerCreditAllocationTable.jsx
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/components/learner-credit-management/tests/LearnerCreditAllocationTable.test.jsx
- src/utils.js
> feat: added default product line filter for budget

- package.json
This step is needed for openedx-translations repo to extract source files.
This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
This fixes the error below:
- https://github.com/openedx/openedx-translations/actions/runs/5721017099/job/15502202718
```
make extract_translations
....
npm run-script i18n_extract
npm ERR! Missing script: "i18n_extract"
make: *** [Makefile:48: i18n.extract] Error 1
Error: Process completed with exit code 2.
```
> chore: add i18n_extract to package.json for openedx-translations

- src/components/EnterpriseSubsidiesContext/data/hooks.js
- src/components/EnterpriseSubsidiesContext/data/tests/hooks.test.js
**Description**: This PR adds support for picking the first active subsidy when multiple are available.
**JIRA**: [ENT-7445](https://2u-internal.atlassian.net/browse/ENT-7445)
> feat: ENT-7445 Added support for picking first active subsidy when multiple available

- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
> feat: Show exec-ed learner credit only for exec ed offers

- .gitignore
- src/components/subsidy-requests/data/hooks.js
- src/components/subsidy-requests/data/tests/hooks.test.js
- src/data/services/EnterpriseAccessApiService.js
- src/data/services/tests/EnterpriseAccessApiService.test.js
Fixes an issue where updates to course requests settings weren't reflected in the Settings/Access page.  We were previously setting `useCache` to always be true in the call to fetch subsidy request configs.
Broken behavior was possibly related to this change? https://github.com/openedx/frontend-platform/pull/361
> fix: remove broken usage of useCache from getSubsidyRequestConfiguration

- src/components/learner-credit-management/MultipleBudgetsPage.jsx
- src/data/actions/portalConfiguration.js
- src/data/actions/portalConfiguration.test.js
- src/data/reducers/portalConfiguration.js
- src/data/reducers/portalConfiguration.test.js
- src/data/services/LmsApiService.js
Stores `enterpriseFeatures` from existing API integration in the `portalConfiguration` reducer within the application's Redux store. To retrieve the `enterpriseFeatures` within one of the child components of `EnterprisePage`:
```jsx
const mapStateToProps = state => ({
// existing
enterpriseId: state.portalConfiguration.enterpriseId,
enterpriseSlug: state.portalConfiguration.enterpriseSlug,
// new
enterpriseFeatures: state.portalConfiguration.enterpriseFeatures,
});
MyComponent.propTypes = {
enterpriseId: PropTypes.string.isRequired,
enterpriseSlug: PropTypes.STRING.isRequired,
enterpriseFeatures: PropTypes.shape().isRequired,
};
export default connect(mapStateToProps)(MyComponent);
```
**Example `enterpriseFeatures` object**
https://courses.stage.edx.org/enterprise/api/v1/enterprise-custom …
> feat: expose `enterpriseFeatures` from API in `portalConfiguration`

- src/components/forms/FormContextWrapper.tsx
- src/components/forms/FormWorkflow.tsx
- src/components/forms/ValidatedFormControl.tsx
- src/components/forms/ValidatedFormRadio.tsx
- src/components/settings/SettingsLMSTab/LMSConfigPage.jsx
- src/components/settings/SettingsLMSTab/LMSConfigs/SAP/SAPConfigEnablePage.tsx
- src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.tsx
- src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.tsx
- src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.tsx
- src/components/settings/SettingsSSOTab/NewSSOStepper.jsx
- src/components/settings/SettingsSSOTab/SSOFormWorkflowConfig.tsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigAuthorizeStep.tsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigConfigureStep.tsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigConfirmStep.tsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigConnectStep.tsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
- src/components/test/testUtils.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7585)
Placeholder screens for the new SSO Integration workflow.
> feat: New SSO workflow skeleton

- src/components/settings/SettingsApiCredentialsTab/APICredentialsPage.jsx
- src/components/settings/SettingsApiCredentialsTab/CopyButton.jsx
- src/components/settings/SettingsApiCredentialsTab/ZeroStateCard.jsx
- src/components/settings/SettingsApiCredentialsTab/index.jsx
- src/components/settings/SettingsApiCredentialsTab/tests/SettingsAPICredentialsPage.test.jsx
https://2u-internal.atlassian.net/browse/ENT-7682
> fix: Bug bash fixes

- src/components/InviteLearnersModal/index.jsx
- src/data/validation/email.js
- src/data/validation/email.test.js
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-7642
> add support for optional salesforce ids in csv upload

- src/components/EnterpriseApp/EnterpriseAppRoutes.jsx
- src/components/EnterpriseApp/data/constants.js
- src/components/EnterpriseSubsidiesContext/data/hooks.js
- src/components/EnterpriseSubsidiesContext/data/tests/BudgetDetailPage.test.jsx
- src/components/EnterpriseSubsidiesContext/data/tests/hooks.test.js
- src/components/learner-credit-management/BudgetCard-V2.jsx
- src/components/learner-credit-management/BudgetDetailPage.jsx
- src/components/learner-credit-management/MultipleBudgetsPage.jsx
- src/components/learner-credit-management/MultipleBudgetsPicker.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/data/hooks.js
- src/components/learner-credit-management/data/tests/hooks.test.js
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/index.js
- src/components/learner-credit-management/index.jsx
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
This PR covers up the following points
- All budgets of ecommerce offers and learner-credit offers are showing regardless of plan.
- View Budget button takes the learner to the detail page along with offerId/budgetId
- Create two new routes  
- for e-commerce /:enterpriseSlug/admin/learner-credit/:offerId 
- for learner_credit budget  /:enterpriseSlug/admin/learner-credit/:budgetId
- Fetch the enrollments on the basis of budget_id if present otherwise, fetch enrollments on the base of offer_id on the detail page
- The “Budgets” link in the breadcrumbs on the LCM UI relies on react-router’s Link component and avoids a full-page refresh.
- Ensure dollar amounts are displayed as monetary (e.g., $18,500.25) rather than just floats without any formatting.
- Ensure LCM is …
> feat: show all enterprise budgets regardless of plan and route correctly

- src/components/EnterpriseApp/EnterpriseAppRoutes.jsx
- src/components/learner-credit-management/index.jsx
https://2u-internal.atlassian.net/browse/ENT-7759
The direct children of `Switch` must be `Route`. Previously, the `LearnerCreditManagementRoutes` component was rendered as the direct child instead of a `Route`, causing all `Route` definitions after `LearnerCreditManagementRoutes` to not work, which happened to only be `ContentHighlights` / `NotFoundPage`.
> fix: ensure highlights routes appear when learner credit is available

- renovate.json
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
Add `@openedx` in renovate automate configuration. 
[Create common renovate config that automates @edx and @openedx namespaced minor/patch version upgrades](https://github.com/openedx/wg-frontend/issues/116#event-10495007446)
> refactor: add @openedx in renovate automate configuration

- src/components/EnterpriseApp/data/constants.js
- src/components/learner-credit-management/MultipleBudgetsPicker.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/components/learner-credit-management/tests/MultipleBudgetsPage.test.jsx
1.  Label and order budgets
- How to label each budget:
- Budgets that have a start date in the future are labeled upcoming.
- Budgets that are currently active have an Active label (within the date range and active
- Budgets that have been marked inactive and/or are expired have an Expired label
- What will be the order of these budget representations?
- All active budgets first; followed by all upcoming budgets; followed by all expired budgets 
- Then within each status, order by showing budget(s) expiring soonest (or most recently) first; 
- Then if there are multiple budgets with the same end date, show them in alphabetical order
2. Update term date range to show only key date info for easier comprehension at a glance: 
- Active: “Expires [date]” 
- Expired: “Expired …
> feat: label and order each budget card on lCM page

- src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
> fix: handle additional case when not viewing assignable budget

- src/components/learner-credit-management/assignments-status-chips/BaseModalPopup.jsx
Resolves `ModalPopup` arrow placement issue by enforcing it to always open on top of trigger element, which will place the arrow at the bottom.
> fix: use top placement, not auto

- src/components/learner-credit-management/AssignmentsTableRefreshAction.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/LearnerCreditAllocationTable.jsx
- src/components/learner-credit-management/search/CatalogSearchResults.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/utils.js
[ENT-7902](https://2u-internal.atlassian.net/browse/ENT-7902)
* Adds "Refresh" CTA interaction to the "Assigned" table. Refreshes whatever the current table is displaying.
* Removes the existing "Product" column from the "Spent" table (confirmed with UX).
https://github.com/openedx/frontend-app-admin-portal/assets/2828721/b93cbc6d-ae3d-4736-9f2d-33f13033bd9f
> feat: add "Refresh" CTA to the "Assigned" table; remove "Product" column from "Spent" table

- src/components/learner-credit-management/AssignmentRowActionTableCell.jsx
- src/components/learner-credit-management/AssignmentTableCancel.jsx
- src/components/learner-credit-management/AssignmentTableRemind.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Assigned selected:
Assigned and not assigned selected:
Not assigned selected:
https://2u-internal.atlassian.net/browse/ENT-7813
> feat: adding cancel and remind actions to the budget assignment table

- src/components/EnterpriseApp/EnterpriseAppRoutes.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/learner-credit-management/AssignmentStatusTableCell.jsx
- src/components/learner-credit-management/BudgetDetailPage.jsx
- src/components/learner-credit-management/BudgetDetailTabsAndRoutes.jsx
- src/components/learner-credit-management/cards/Collapsibles.jsx
- src/components/learner-credit-management/search/CatalogSearchResults.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Related PR: https://github.com/openedx/enterprise-access/pull/314
Removes some business logic in the frontend in favor of relying on data returned by the API explicitly. That is, when an Assignment is an `errored` state, the API now returns the most recent `error_reason` from the associated Actions such that the frontend doesn't have to iterate through the list of Actions itself.
> fix: rely on new `error_reason` field to determine failed `learner_state` reason

- src/components/App/index.jsx
- src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx
- src/components/learner-credit-management/BudgetDetailPage.jsx
- src/components/learner-credit-management/BudgetDetailPageWrapper.jsx
- src/components/learner-credit-management/cards/AssignmentModalContent.jsx
- src/components/learner-credit-management/cards/BaseCourseCard.jsx
- src/components/learner-credit-management/cards/CourseCard.jsx
- src/components/learner-credit-management/cards/CourseCard.test.jsx
- src/components/learner-credit-management/cards/NewAssignmentModalButton.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailActivityOverview.test.jsx
- src/components/learner-credit-management/data/hooks/useSubsidyAccessPolicy.test.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/components/learner-credit-management/tests/CatalogSearch.test.jsx
- src/components/learner-credit-management/tests/CatalogSearchResults.test.jsx
- src/components/settings/SettingsSSOTab/tests/NewExistingSSOConfigs.test.jsx
- src/components/settings/SettingsSSOTab/tests/SettingsSSOTab.test.jsx
- src/components/test/testUtils.jsx
- src/data/services/EnterpriseAccessApiService.js
- src/data/services/tests/EnterpriseAccessApiService.test.js
- src/utils.js
- src/utils.test.js
First of at least two PRs for [ENT-7826](https://2u-internal.atlassian.net/browse/ENT-7826)
Includes:
* Integrates with the `allocate` POST API endpoint in enterprise-access. **Happy path only**, using whatever email(s) are input in the assignment modal.
* Modifies the global retry behavior for `@tanstack/react-query` to avoid retries when the query has thrown max 3 errors in a row (default behavior) or returns a 404 once.
* Displays skeleton loading state when doing background refetches of the budget detail activity overview data (spent table + assigned table, if applicable).
* This is necessary for when an admin creates their first assignment(s) when the "Activity" tab previously displayed "No budget activity?" empty state such that the empty state doesn't briefly show immediately after …
> fix: integrate with `allocate` API for creating assignments, update global retry behavior on queries, handle 404 subsidy access policy

- src/components/settings/SettingsSSOTab/NewExistingSSOConfigs.jsx
- src/components/settings/SettingsSSOTab/index.jsx
- src/components/settings/SettingsSSOTab/utils.js
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7919)
> fix: disable creating new SSO config while configuring prior config in progress 

- src/components/learner-credit-management/AssignmentRowActionTableCell.jsx
- src/components/learner-credit-management/cards/BaseCourseCard.jsx
- src/components/learner-credit-management/cards/CourseCard.test.jsx
- src/components/learner-credit-management/cards/CreateAllocationErrorAlertModals.jsx
- src/components/learner-credit-management/cards/NewAssignmentModalButton.jsx
- src/components/learner-credit-management/cards/data/constants.js
- src/components/learner-credit-management/cards/data/index.js
- src/components/learner-credit-management/cards/data/utils.js
- src/components/learner-credit-management/cards/status-modals/ContentNotInCatalogErrorAlertModal.jsx
- src/components/learner-credit-management/cards/status-modals/NotEnoughBalanceAlertModal.jsx
- src/components/learner-credit-management/cards/status-modals/SystemErrorAlertModal.jsx
- src/components/learner-credit-management/tests/CatalogSearchResults.test.jsx
Ticket: [ENT-7826](https://2u-internal.atlassian.net/browse/ENT-7826)
Adds error handling in the UX around the `allocate` POST API. Displays one of three `AlertModal` components with relevant messaging when the `allocate` POST API returns a non-200 HTTP status code.
https://github.com/openedx/frontend-app-admin-portal/assets/2828721/0ff3615a-7f15-4e50-914a-5acca1f54b53
> feat: assignment error AlertModal variants

- src/components/learner-credit-management/BudgetDetailPageWrapper.jsx
- src/components/learner-credit-management/cards/CourseCard.test.jsx
- src/components/learner-credit-management/cards/CreateAllocationErrorAlertModals.jsx
- src/components/learner-credit-management/cards/NewAssignmentModalButton.jsx
- src/components/learner-credit-management/data/hooks/index.js
- src/components/learner-credit-management/data/hooks/useSuccessfulAssignmentToastContextValue.js
- src/components/learner-credit-management/tests/BudgetDetailPageWrapper.test.jsx
- src/components/learner-credit-management/tests/CatalogSearchResults.test.jsx
Successful assignment allocation `Toast` notification after submitting the assignment modal with a valid 200 response.
https://github.com/openedx/frontend-app-admin-portal/assets/2828721/57cfb450-073d-43fe-96e8-91a6f0b8be4e
> feat: display success toast on assignment allocation

- src/data/services/EnterpriseSubsidyApiService.js
- src/data/services/tests/EnterpriseSubsidyApiService.test.js
ENT-7999
This PR https://github.com/openedx/frontend-app-admin-portal/pull/1087/files#diff-89082fcf3fbc9b339141578405314256fc4f1ae0210dab880414add817619ef7  pulls from the learner view, not the admin view.  So it tries to fetch only the transactions associated with the requesting user.  We want the admin-portal to pull from the admin view.
> fix: list transactions from the admin-tx view

- src/data/services/EnterpriseSubsidyApiService.js
- src/data/services/tests/EnterpriseSubsidyApiService.test.js
> fix: only request committed transactions for spent table

- src/components/learner-credit-management/AssignmentRowActionTableCell.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8048
Ensures "Select all..." functions as expected, with exception of the Paragon bug related to the row count shown in the "Select all..." label (see [this Paragon bug](https://github.com/openedx/paragon/issues/2872) describing the issue with the "Select all..." label's count). Also, does not update the counts shown in the bulk actions or call a "full table selected" specific API endpoint.
https://github.com/openedx/frontend-app-admin-portal/assets/2828721/80cc5599-34db-4545-b982-674089da67ae
> fix: use controlled selection components from DataTable for BudgetAssigmentsTable

- src/components/settings/SettingsSSOTab/SsoErrorPage.jsx
- src/components/settings/settings.scss
https://2u-internal.atlassian.net/browse/ENT-8052
I used the figma mocks dimensions when defining the css class
old: 
new:
> fix: cleaning up sso network error page

- src/components/settings/SettingsSSOTab/NewSSOConfigAlerts.jsx
- src/components/settings/SettingsSSOTab/tests/NewSSOConfigAlerts.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8050
nice and straight forward
> feat: dynamically using enterprise slug when displaying sso informational alerts

- src/components/EnterpriseSubsidiesContext/index.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/cards/NewAssignmentModalButton.jsx
- src/components/learner-credit-management/cards/tests/CourseCard.test.jsx
- src/components/learner-credit-management/data/hooks/useSuccessfulAssignmentToastContextValue.js
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/components/learner-credit-management/tests/BudgetDetailPageWrapper.test.jsx
Introduces a background refetching loading state for the budget cards on the Learner Credit Management budgets list page. This is necessary to give the user immediate feedback that the budgets' metadata is refetching (e.g., after assignments were successfully allocated) as opposed to the current state where there is a delay between seeing the original budget aggregates vs. the updated budget aggregates after taking action on the budget (e.g., allocating assignments).
Considered using optimistic updates, where we manually update the query client cache instead of refetching the API, which would improve the perceived performance of the application. However, this preferred approach requires performing calculation(s) around remaining balance, etc. after successful assignment allocation that …
> feat: background refetching loading state on budgets cards

- src/data/services/EnterpriseAccessApiService.js
- src/data/services/tests/EnterpriseAccessApiService.test.js
Updates API for subsidy access policy list view to include the optional `active` query parameter
> feat: display only active budgets from subsidy-access-policy

- src/components/EnterpriseSubsidiesContext/data/hooks.js
- src/components/EnterpriseSubsidiesContext/data/tests/hooks.test.jsx
- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/data/hooks/useSubsidyAccessPolicy.js
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/utils.js
Previously, if an assignable budget had no assignments yet, the "Pending" balance would not show on the budget card on the Budgets list page route. With this PR, the "Pending" balance will always display for assignable budgets, regardless of having any assignments allocated yet:
> fix: ensure pending balance is shown on budget cards even if 0

- src/components/EnterpriseSubsidiesContext/data/hooks.js
- src/components/ProductTours/data/hooks.js
Sets `refetchOnWindowFocus` to false specifically on the useEnterpriseBudgets hook call as its the only component on the top level context that is implemented using `useQuery` and has `ProductTours` as a child component.
> fix: disables refetch on window focus for useEnterpriseBudgets useQuery hook call

- src/components/learner-credit-management/AssignmentStatusTableCell.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Returns a generalized failed system chip if no error reason exist and the learnerState is 'failed'.
Also refactors return string (capitalize first letter) using and existing utilities function
> fix: adds sane fallback to if learnerState is failed and no error reason exist

- .env.development-stage
- src/components/learner-credit-management/BudgetDetailPage.jsx
- src/components/learner-credit-management/BudgetDetailPageHeader.jsx
- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
- src/components/learner-credit-management/BudgetDetailPageOverviewUtilization.jsx
- src/components/learner-credit-management/BudgetDetailPageWrapper.jsx
- src/components/learner-credit-management/BudgetDetailRedemptions.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailHeaderData.js
- src/components/learner-credit-management/data/hooks/useBudgetRedemptions.js
- src/components/learner-credit-management/data/tests/constants.js
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Follow-up patch applied after merging the PR (https://github.com/openedx/frontend-app-admin-portal/pull/1110) to resolve the following:
1. When viewing an enterprise offer in the budget detail page and the analytics API errors/doesn't return data, there are a few JS errors thrown.
2. Incorrect field names were being associated for the `spendAvailableUsd ` and `amountRedeemedUsd ` fields within `transformSubsidySummaryToPolicy`.
TODO Screenshot
> fix: use correct aggregates properties and resolve JS error

- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
Updates UI components to match figma output for scheduled, expired, and a centered 'view budget' button.
Figma:
Previous UI:
Updated UI:
> fix: update UI padding

- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
Based on feedback from Jenn (UX), changing the assignable budget cards to say "Assigned" instead of "Pending" in the balances card section to be consistent with the language used on the budget detail page.
> fix: replace pending with assigned in budget cards

- src/components/learner-credit-management/AssignmentStatusTableCell.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedRedemption.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
This is the frontend component corresponding to:
https://github.com/openedx/enterprise-access/pull/364
Before this change, failed redemptions would result in the frontend displaying a "Failed: System" chip, which is a generic fallback.  After this change, an explicit "Failed: Redemption" chip is displayed.
ENT-8105
> feat: add assignment status chip for a failed redemption

- README.md
- package.json
- src/components/learner-credit-management/AssignmentTableCancel.jsx
- src/components/learner-credit-management/AssignmentTableRemind.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/data/hooks/useCancelContentAssignments.js
- src/components/learner-credit-management/data/hooks/useRemindContentAssignments.js
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/data/services/EnterpriseAccessApiService.js
- src/data/services/tests/EnterpriseAccessApiService.test.js
Makes use of the `remind-all` and `cancel-all` endpoints to cancel/remind all assignments when the "all" checkbox is selected on the assignments table.
Selected, but not "select all"
Now all are selected, but one of the assignments is errored (not in waiting state), so it's not remindable
Click the Cancel button, the cancel modal has all 27 as the number to cancel
Go back, check out the remind modal:
Now do the remind-all action - only 26 reminders sent, b/c only 26 are remindable
Now select all and do the cancel-all action:
> fix: support remind/cancel-all

- src/components/ContentHighlights/HighlightStepper/ContentHighlightStepper.jsx
- src/components/learner-credit-management/AssignmentStatusTableCell.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedCancellation.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedReminder.jsx
- src/components/learner-credit-management/cards/NewAssignmentModalButton.jsx
- src/components/settings/data/hooks.js
- src/components/settings/settings.scss
- src/index.scss
_(Note: Illustrative only; keeping the button as primary variant in practice)_
> fix: dynamic theme fixes for outline buttons and fullscreen steppers

- src/components/learner-credit-management/AssignmentTableCancel.jsx
- src/components/learner-credit-management/AssignmentTableRemind.jsx
- src/components/subscriptions/data/utils.js
- src/components/subscriptions/licenses/LicenseManagementTable/bulk-actions/RemindBulkAction.jsx
- src/components/subscriptions/licenses/LicenseManagementTable/bulk-actions/RevokeBulkAction.jsx
- src/utils.js
Ticket: [ENT-8155](https://2u-internal.atlassian.net/browse/ENT-8155)
If filters are applied to the "Assigned" table, continue to call the standard bulk action API endpoints. Only call the `{remind/cancel}-all` API endpoints when the entire table is selected with NO filters applied.
In the below screenshot, note the 32 rows selected, but only the 25 rows on current page will be applicable (and shown in the count). This avoids unexpectedly applying bulk actions to non-filtered rows, but is still not quite the right behavior (i.e., the expected behavior would be performing the action on only on all _filtered_ rows). It's at least a short term fix to prevent unexpected cancelations and reminders, until something like [ENT-8156](https://2u-internal.atlassian.net/browse/ENT-8156) is …
> fix: account for filters in select all bulk actions assigned table

- src/components/forms/FormWorkflow.tsx
- src/components/learner-credit-management/AssignmentTableCancel.jsx
- src/components/learner-credit-management/AssignmentTableRemind.jsx
- src/components/learner-credit-management/PendingAssignmentCancelButton.jsx
- src/components/learner-credit-management/PendingAssignmentRemindButton.jsx
- src/components/learner-credit-management/data/hooks/useCancelContentAssignments.js
- src/components/learner-credit-management/data/hooks/useCancelContentAssignments.test.jsx
- src/components/learner-credit-management/data/hooks/useRemindContentAssignments.js
- src/components/learner-credit-management/data/hooks/useRemindContentAssignments.test.jsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigConfigureStep.tsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigConnectStep.tsx
- src/data/services/EnterpriseAccessApiService.js
- src/data/services/tests/EnterpriseAccessApiService.test.js
ENT-8156 | Pass the appropriate content assignment filter state to the `cancel-all` and `remind-all` endpoints.
Here's a recording of me canceling all "notifying" assignments, then reminding all "waiting" assignments.
https://github.com/openedx/frontend-app-admin-portal/assets/2307986/05cb8605-a496-4a0d-9254-4a564af2c15b
> feat: apply filters to cancel/remind all

- src/components/ContentHighlights/ContentHighlightCardItem.jsx
Part of QAing react 17 upgrade in stage resulted in the discovery of a trailing comma in the highlights card component.
Before Fix:
With fix updating  element type of truncate component to a `span` on card titles as hyperlinks
With fix testing ellipses on course card.
> fix: remove comma from hyperlinked titles

- src/components/App/index.jsx
- src/components/settings/index.jsx
Fixes regression where given a url path includes the `pathname` from `useLocation`, a trailing forward slash may or may not exist in the url pathname.  Ex.  URL: `portal.edx.org/test-slug/` , pathname: `/test-slug/`
If a pathname is used with a trailing slash to construct a URL without using the `generatePath` method, an edge case arises where the user may navigate to  `portal.edx.org/test-slug/` and be redirected to `portal.edx.org/test-slug//admin/learners` due to the trailing forward slash.
See video for example.
Before fix:
https://github.com/openedx/frontend-app-admin-portal/assets/82611798/c5a1733c-f4df-46dd-b127-41338fa82eed
Post fix:
https://github.com/openedx/frontend-app-admin-portal/assets/82611798/8877fd2d-92b8-4611-8f7d-04323b63ff9a
> fix: update path generation to use generatePath

- src/components/App/index.jsx
- src/components/EnterpriseApp/EnterpriseAppContextProvider.jsx
- src/components/EnterpriseApp/EnterpriseAppContextProvider.test.jsx
- src/components/EnterpriseApp/data/hooks/index.js
- src/components/EnterpriseApp/data/hooks/useUpdateActiveEnterpriseForUser.js
- src/components/EnterpriseApp/data/hooks/useUpdateActiveEnterpriseForUser.test.jsx
- src/components/test/testUtils.jsx
- src/data/services/LmsApiService.js
- src/data/services/tests/LmsApiService.test.js
- src/utils.js
- src/utils.test.js
https://2u-internal.atlassian.net/browse/ENT-8038
> feat: auto setting active linked enterprise

- src/components/ContentHighlights/ContentHighlightCardItem.jsx
- src/components/EnterpriseApp/data/constants.js
- src/components/EnterpriseSubsidiesContext/data/hooks.js
- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/BudgetDetailPageHeader.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailHeaderData.js
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
Ticket: https://2u-internal.atlassian.net/browse/ENT-8303
* Retired budgets have an `info` variant `Badge` on the budget cards in the overview page route and no date displayed. The CTA is using the `outline-primary` button variant.
* Retired budgets have an `info` variant `Badge` on the budget detail page and no date displayed.
* Retired budgets display last in the sort order.
> feat: display retired badge on retired budgets

- src/components/EnterpriseApp/data/hooks/useUpdateActiveEnterpriseForUser.js
- src/components/EnterpriseApp/data/hooks/useUpdateActiveEnterpriseForUser.test.jsx
- src/data/services/LmsApiService.js
- src/data/services/tests/LmsApiService.test.js
- src/utils.js
> fix: not throwing errors if user isn't linked to enterprise while setting active

- src/components/subscriptions/data/utils.js
- src/components/subscriptions/tests/data/utils.test.js
Ensures subscription plans in the Subscription Management feature list page route are ordered as follows:
1. First by subscription plan status (active/current, scheduled/upcoming, expired).
2. Then, break ties between same-status plans with plan expiration dates (plans expiring first, shown first).
3. Then, break ties between same-status and same-expiration plans with alphabetical plan title (ascending).
This update brings the Subscription Management feature to have parity with the ordering logic for budgets displayed in the Learner Credit Management feature.
> fix: ensure subs plans are sorted alphabetically, when appropriate

- src/components/CodeAssignmentModal/index.jsx
- src/components/CodeReminderModal/index.jsx
- src/components/CodeRevokeModal/index.jsx
- src/components/InviteLearnersModal/index.jsx
- src/components/settings/SettingsLMSTab/ErrorReporting/tests/ErrorReporting.test.jsx
- src/components/settings/SettingsLMSTab/ErrorReporting/tests/SyncHistory.test.jsx
A [PR](https://github.com/openedx/frontend-app-admin-portal/pull/872) was merged a few days ago with several linting issues, many of which would result in JS errors. These changes were released to production about 8 hours ago. We are seeing these errors creep up in New Relic reporting, preventing critical user flows.
This PR ensures all linting errors are resolved for this project, resolving those code paths with possible JS bugs due to missing `Spinner` imports.
> fix: linting and JS errors due to paragon modal deprecation pr

- src/components/learner-credit-management/SpendTableEnrollmentDetails.jsx
- src/components/learner-credit-management/data/hooks/tests/useBudgetRedemptions.test.jsx
- src/components/learner-credit-management/data/utils.js
When the spent table was first implemented, it utilized the Analytics API to fetch enrollments, and that data source contained a course key field.  However, when we switched over to real-time fetching of redemptions via the transaction list API for assignable budgets, we erroneously treated the `content_key` field as a course key, breaking the course about page link in the spent table.
The following two PRs implment a `parent_content_key` field in the transaction list API, which we can now utilize for the real-time spent table implmentation:
* https://github.com/openedx/openedx-ledger/pull/60
* https://github.com/openedx/enterprise-subsidy/pull/209
ENT-8389
> fix: course about URL should use course key, not course run key.

- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/MultipleBudgetsPicker.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/components/learner-credit-management/tests/MultipleBudgetsPage.test.jsx
Adds filtering and search functionality to the budget landing page by putting the budget cards into a `DataTable`. 
https://2u-internal.atlassian.net/browse/ENT-8502
|before|after|
|-------|-----|
|![Screenshot 2024-03-07 at 11 20 24 AM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/a42fb416-93fa-4bb7-953a-bfa2dc860e6a)|![Screenshot 2024-03-07 at 11 16 23 AM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/15e2fe1f-f283-4190-a4dc-223d3b9d9dfd)|
https://github.com/openedx/frontend-app-admin-portal/assets/71999631/b7f3b68f-13b5-4843-8ef5-45e6d75a7b39
> feat: add filtering and search to budget landing page

- src/components/Admin/SubscriptionDetailPage.jsx
- src/components/Admin/SubscriptionDetailPage.test.jsx
**Description:** Subscriptions UI component was not showing on the LPR page. Subscription UUID was parsed incorrectly.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-8600
> fix: extract subscription uuid correctly

- src/components/ContentHighlights/ContentHighlights.jsx
- src/components/ContentHighlights/tests/ContentHighlights.test.jsx
- src/components/Sidebar/index.jsx
- src/components/learner-credit-management/BudgetDetailPageHeader.jsx
- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
- src/containers/Sidebar/Sidebar.test.jsx
We are not going to be hiding highlights for staff, but they will have the alert pictured below so we can inform them. Also, this hides something for groups [from this PR](https://github.com/openedx/frontend-app-admin-portal/pull/1195) behind a feature flag to preserve the previous behavior until we roll out groups.
> fix: don't hide highlights for staff and alert 

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/BudgetExpiryAlertAndModal/data/utils.js
fix: code styling issues mentioned in the previous PR https://github.com/openedx/frontend-app-admin-portal/pull/1177
> fix: code styling issues for expiry logic

- src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementRemindModal.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRemindModal.test.jsx
The license-manager [remind view](https://github.com/openedx/license-manager/blob/217d3c67874287c1c544095d0f5ebf0bb1ba02c8/license_manager/apps/api/v1/views.py#L941-L992) already supports bulk operations - a caller can provide filters on either a `user_email` or set of statuses, via `status_in`, with that view’s [serializer.](https://github.com/openedx/license-manager/blob/217d3c67874287c1c544095d0f5ebf0bb1ba02c8/license_manager/apps/api/serializers.py#L400)
Here in the admin portal, the remind modal already makes use of that bulk behavior.
The problem is that selecting all rows in the table causes `usersToRemind` to be populated with the first page of user email addresses, and the logic gives preference to the presence of those emails over the presence of any `activeFilters`.
This PR …
> fix: pass filters, not emails, when remindAllUsers is selected

- src/components/learner-credit-management/data/hooks/useEnterpriseGroupMembersTableData.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/members-tab/BudgetDetailMembersTabContents.jsx
- src/components/learner-credit-management/members-tab/GroupMembersCsvDownloadTableAction.jsx
- src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx
- src/components/learner-credit-management/members-tab/MembersTableSwitchFilter.jsx
- src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/data/services/EnterpriseAccessApiService.js
https://2u-internal.atlassian.net/browse/ENT-8562
With the new usage of the subisdy access API for group member data, we can implement both csv download as a table action and enrollment count for both csv downloads and displayed table.
CSV download data will apply any filter and sorting currently applied to the table, but will traverse all pages of data.
> feat: subsidy group members download csv functionality

- src/components/BudgetExpiryAlertAndModal/data/hooks/useExpiry.jsx
- src/components/BudgetExpiryAlertAndModal/data/hooks/useExpiry.test.jsx
- src/components/BudgetExpiryAlertAndModal/data/utils.js
When determining budget expiry thresholds/modals, We need to consider the special case where there are a mix of expired and non-expired budgets.  In that case, we only want to determine the expiry threshold from the set of *non-expired* budgets, so that the expiry alert and modal below do not falsely indicate that *all* budgets are expired.
Note: this change leaves in place the current preference that we alert on the *earliest* expiring budget (now drawn from the set of only non-expired budgets).
ENT-8834
> fix: consider mixed state of budget expiries when rendering expiry modal

- patches/@edx+paragon+20.46.3.patch
- src/components/learner-credit-management/BudgetStatusSubtitle.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-8893)
[Local Stage Example](https://localhost.stage.edx.org:1991/pawnee-parks/admin/learner-credit/6acd1860-d0a5-4e35-a529-5b3dd589c1db)
This patches a bug in the ManageAccounts icon svg that has been fixed in Paragon, and also make some positional adjustments to icons.
> fix: Headless ManageAccounts icon

- package-lock.json
- package.json
Removes `react-dev-utils` as a dev dependency since it is unused in the repo and the version of `react-dev-utils` is displaying dependabot warnings.
> chore: dependency cleanup for dependabot warnings

- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
- src/components/learner-credit-management/MultipleBudgetsPicker.jsx
- src/components/learner-credit-management/tests/MultipleBudgetsPage.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8948
|description|before|after|
|-----------|-------|-----|
|Checking multiple budget status filters hides the budgets|![Screenshot 2024-05-16 at 12 47 51 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/1cb4476a-5cce-48a8-bda6-74fcb2faae48)|![Screenshot 2024-05-16 at 12 48 36 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/28b71d1b-d725-45c7-88e8-fdffcc02eef3)|
|fix configure access tab to load|<img width="1165" alt="Screenshot 2024-05-15 at 11 43 38 AM" src="https://github.com/openedx/frontend-app-admin-portal/assets/71999631/d7ad4aba-27b6-45c1-a8ff-08979893b3ba">|https://github.com/openedx/frontend-app-admin-portal/assets/71999631/4ca3d899-18cd-455b-9abf-6f360d6f94da|
> fix: lms access link and budget filter

- src/components/Admin/AdminSearchForm.jsx
- src/components/Admin/AdminSearchForm.test.jsx
- src/components/Admin/EmbeddedSubscription.jsx
- src/components/Admin/SubscriptionDetailPage.jsx
- src/components/Admin/SubscriptionDetails.jsx
- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/index.jsx
- src/components/Admin/licenses/LicenseAllocationHeader.jsx
- src/components/Admin/licenses/LicenseAllocationHeader.test.jsx
- src/components/Admin/licenses/LicenseManagementTable/index.jsx
- src/components/Admin/licenses/__snapshots__/LicenseAllocationHeader.test.jsx.snap
- src/components/CompletedLearnersTable/CompletedLearnersTable.test.jsx
- src/components/CompletedLearnersTable/index.jsx
- src/components/EnrolledLearnersForInactiveCoursesTable/EnrolledLearnersForInactiveCoursesTable.test.jsx
- src/components/EnrolledLearnersForInactiveCoursesTable/index.jsx
- src/components/EnrolledLearnersTable/EnrolledLearnersTable.test.jsx
- src/components/EnrolledLearnersTable/index.jsx
- src/components/EnrollmentsTable/index.jsx
- src/components/LearnerActivityTable/LearnerActivityTable.test.jsx
- src/components/LearnerActivityTable/index.jsx
- src/components/PastWeekPassedLearnersTable/PastWeekPassedLearnersTable.test.jsx
- src/components/PastWeekPassedLearnersTable/index.jsx
- src/components/RegisteredLearnersTable/RegisteredLearnersTable.test.jsx
- src/components/RegisteredLearnersTable/index.jsx
- src/utils.js
- src/utils.test.js
> feat: mark strings for i18n on lpr page

- src/components/learner-credit-management/members-tab/GroupMembersCsvDownloadTableAction.jsx
- src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx
- src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
- src/data/services/EnterpriseAccessApiService.js
https://2u-internal.atlassian.net/browse/ENT-8974
> feat: allowing group data download button to apply to selected rows

- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/index.scss
> feat: Retired workflow on the list policy screens

- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
In the budget card, there is an extraneous comma after the 'Configure access' button that is removed.
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/boards/630?assignee=712020%3A008f4187-4536-4e5b-ae31-b8cd7792730c&selectedIssue=ENT-9012 
#UI changes
|before|after|
|------|----
|![Screenshot 2024-05-23 at 3 44 13 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/4c93578f-ee24-4546-ad27-f28307e2b266)|![Screenshot 2024-05-23 at 3 48 21 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/a87ad8ef-b96e-4846-b35a-1dba0097d849)|
> fix: remove extraneous comma in budget card

- src/components/learner-credit-management/invite-modal/InviteModalSummaryDuplicate.jsx
Update info icon color to darker blue to match figma mocks.
https://2u-internal.atlassian.net/browse/ENT-9013
|figma|before|after|
|-----|------|-----|
|![Screenshot 2024-05-24 at 1 18 41 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/5c528ce6-bba4-45b0-a8cc-672d8589593a)|![Screenshot 2024-05-24 at 1 13 16 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/8eeedcbb-3ef8-40f4-b050-646aae6f08bb)|![Screenshot 2024-05-24 at 1 20 21 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/27b6a47d-3599-4868-9a0d-d3c0ebdba906)|
> fix: update info icon color

- src/components/learner-credit-management/invite-modal/InviteModalBudgetCard.jsx
- src/components/learner-credit-management/styles/index.scss
Fixed styling issue around container width in Invite members modal and added danger color "Members can't be invited as entered" warning.
https://2u-internal.atlassian.net/browse/ENT-9018
|description|figma|before|after|
|-----------|------|------|-----|
|Fixed card alignment|<img width="762" alt="Screenshot 2024-05-28 at 4 31 57 PM" src="https://github.com/openedx/frontend-app-admin-portal/assets/71999631/878c418a-21f1-447d-b88f-c85303dd1e17">|<img width="1141" alt="Screenshot 2024-05-28 at 4 24 35 PM" src="https://github.com/openedx/frontend-app-admin-portal/assets/71999631/a7192a8b-7ea8-4a4d-8a5e-ef7fb34acc3e">|<img width="1148" alt="Screenshot 2024-05-28 at 3 55 05 PM" src="https://github.com/openedx/frontend-app-admin-portal/assets/71999631/aab0503f-e6b4-4ace-940f-773d3bb6dc98">| …
> fix: removed margin and added danger color

- src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx
- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
- src/components/learner-credit-management/data/tests/constants.js
- src/components/learner-credit-management/invite-modal/InviteMembersModalWrapper.jsx
- src/components/learner-credit-management/members-tab/MemberStatusTableCell.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/components/settings/data/constants.js
https://2u-internal.atlassian.net/browse/ENT-9042
This ticket changes all the help center links from placeholders to the correct groups link and adds an additional check to make sure the org has a groups association before showing groups content.
> fix: Update help center and hide groups content

- src/components/BudgetExpiryAlertAndModal/data/expiryThresholds.js
- src/components/BudgetExpiryAlertAndModal/data/hooks/useExpiry.jsx
- src/components/BudgetExpiryAlertAndModal/data/hooks/useExpiry.test.jsx
- src/components/BudgetExpiryAlertAndModal/data/utils.js
- src/components/learner-credit-management/BudgetOverviewContent.jsx
- src/components/learner-credit-management/MultipleBudgetsPicker.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailHeaderData.js
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/invite-modal/InviteModalBudgetCard.jsx
- src/components/subscriptions/expiration/SubscriptionExpiredModal.jsx
JIRA -> [ENT-8748](https://2u-internal.atlassian.net/browse/ENT-8748)
> feat: mark static strings for flash messages on login

- src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailTabs.jsx
- src/components/learner-credit-management/invite-modal/InviteModalSummaryLearnerList.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
1. For groups that apply to all contexts, we will hide the zero state card with the "Get started" or "invite new members" button, we also shouldn't show this card to budgets that are expired.
2. For the invite modal email address overflow, set the limit to 15 instead of 14 email addresses. 
https://2u-internal.atlassian.net/browse/ENT-9022
|before|after|
|-------|----|
|![Screenshot 2024-06-05 at 1 36 44 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/e5a5280a-c22c-4403-b4e1-2207a9b60dce)|<img width="1469" alt="Screenshot 2024-05-29 at 10 20 10 AM" src="https://github.com/openedx/frontend-app-admin-portal/assets/71999631/32971b92-4781-4b32-848e-4dd462d63e31">|
|![Screenshot 2024-06-05 at 1 41 24 PM](https://github.com/openedx/frontend-app-admin-portal/assets/719996 …
> fix: zero state card and invite modal

- src/components/BudgetExpiryAlertAndModal/data/expiryThresholds.js
- src/components/ContentHighlights/DeleteArchivedHighlightsDialogs.jsx
- src/components/ContentHighlights/DeleteHighlightSet.jsx
- src/components/ContentHighlights/HighlightStepper/HighlightStepperTitle.jsx
- src/components/NotFoundPage/index.jsx
- src/components/learner-credit-management/AssignmentEnrollByDateCell.jsx
- src/components/learner-credit-management/AssignmentEnrollByDateHeader.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
- src/components/learner-credit-management/BudgetStatusSubtitle.jsx
- src/components/learner-credit-management/CancelAssignmentModal.jsx
- src/components/learner-credit-management/RemindAssignmentModal.jsx
- src/components/learner-credit-management/assignment-modal/AssignmentAllocationHelpCollapsibles.jsx
- src/components/learner-credit-management/assignment-modal/AssignmentModalSummaryEmptyState.jsx
- src/components/learner-credit-management/assignment-modal/AssignmentModalSummaryErrorState.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/members-tab/MemberEnrollmentsTableColumnHeader.jsx
- src/components/learner-credit-management/members-tab/MemberStatusTableColumnHeader.jsx
- src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/components/learner-credit-management/utils.js
- src/components/settings/SettingsAppearanceTab/index.jsx
- src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx
- src/components/subscriptions/expiration/SubscriptionExpiringModal.jsx
- src/utils.js
Adds a net new column to the learner credit management budget detail page on the assignments table called "Enroll-by date".
The column component determines if the date should render a "Warning" icon if the enroll by date is within 10 days of expiration.
https://github.com/openedx/frontend-app-admin-portal/assets/82611798/3dc10c33-7e69-4bc2-a2f7-70b31a02da79
> feat: Add enroll-by date to the assignment table

- src/components/EnterpriseSubsidiesContext/data/tests/hooks.test.jsx
- src/components/learner-credit-management/AssignmentAmountTableCell.jsx
- src/components/learner-credit-management/AssignmentStatusTableCell.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/BudgetCard.jsx
- src/components/learner-credit-management/BudgetDetailAssignments.jsx
- src/components/learner-credit-management/BudgetDetailRedemptions.jsx
- src/components/learner-credit-management/BudgetStatusSubtitle.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/SubBudgetCardUtilization.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailTabs.jsx
- src/components/learner-credit-management/data/tests/constants.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/BudgetCard.test.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Ticket: [ENT-9047](https://2u-internal.atlassian.net/browse/ENT-9047)
Figma: https://www.figma.com/design/gm4yVDt3TixtEi7aD6LETz/Learner-Credit-Expiration?node-id=489-19375&m=dev
> feat: UI updates expired workflow

- src/components/ContentHighlights/HighlightStepper/HighlightStepperSelectContentSearch.jsx
Filters out `content_type` of video in content highlights. This is due to inconsistent data formats between `content_types` in Algolia.
> fix: filter out video content types

- src/components/learner-credit-management/assignment-modal/AssignmentModalContent.jsx
Updates track event name used in segment events to an existing track event name. Issue derived from the following DD error. 
The event name has [always existed](https://github.com/openedx/frontend-app-admin-portal/blob/67f42b70c27d561d8c79f09f77654ed46f1ff449/src/eventTracking.js#L176) but was incorrectly referenced.
> fix: reference correct track event name

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/data/hooks/index.js
- src/components/Admin/index.jsx
- src/components/Admin/tabs/DownloadCSVButton.jsx
- src/components/Admin/tabs/DownloadCsvButton.test.jsx
- src/components/Admin/tabs/ModuleActivityReport.jsx
- src/components/Admin/tabs/ModuleActivityReport.test.jsx
- src/data/services/EnterpriseDataApiService.js
__Jira Ticket:__ [ENT-8186](https://2u-internal.atlassian.net/browse/ENT-8186)
This PR adds the UI components (DataTable) for module activity report on admin portal. 
**Note**: This PR depends on the presence of `/enterprise/api/v1/enterprise/<enterprise-customer-uui>/module-performance` and that in turn requires `exec_ed_lc_module_performance` on Aurora. So, this PR will only be merged and deployed when the table is present and the endpoint is returning correct data.
**Screenshots:**
When REST endpoint returns empty data set.
> ENT-8186: Added a new data table to show user module performance data.

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/DownloadCSV.jsx
- src/components/AdvanceAnalyticsV2/Header.jsx
- src/components/AdvanceAnalyticsV2/data/constants.js
- src/components/AdvanceAnalyticsV2/data/utils.js
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
- src/components/AdvanceAnalyticsV2/tests/AnalyticsV2Page.test.jsx
- src/components/AdvanceAnalyticsV2/tests/DownloadCSV.test.jsx
- src/components/EnterpriseApp/EnterpriseAppRoutes.jsx
- src/data/services/EnterpriseDataApiService.js
> feat: integrate csv download button on all plotly v2 charts and tables

- src/components/AdvanceAnalyticsV2/ProgressOverlay.jsx
- src/components/AdvanceAnalyticsV2/charts/EmptyChart.jsx
- src/components/AdvanceAnalyticsV2/charts/EmptyChart.test.jsx
- src/components/AdvanceAnalyticsV2/charts/ScatterChart.jsx
- src/components/AdvanceAnalyticsV2/charts/ScatterChart.test.jsx
- src/components/AdvanceAnalyticsV2/data/constants.js
- src/components/AdvanceAnalyticsV2/data/hooks.js
- src/components/AdvanceAnalyticsV2/data/hooks.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.test.jsx
- src/components/AdvanceAnalyticsV2/tests/AnalyticsV2Page.test.jsx
- src/data/services/EnterpriseDataApiService.js
- src/data/services/tests/EnterpriseDataApiService.test.js
**Description:** Integrate skills tab charts with API
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-9241
**Skills Tab Charts Screenshot**
> feat: integrate skills charts

- src/components/ReportingConfig/ReportingConfigForm.jsx
https://2u-internal.atlassian.net/browse/ENT-9413
Tested with https://localhost.stage.edx.org:1991/aj-test-co/admin/reporting
Prior to change - catalog selections were not persisting upon saving after reloading the page. After adding back the missing name attribute, the catalog selections are now persisting.
> fix: allow catalog selection in reporting config form

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/ProgressOverlay.jsx
- src/components/AdvanceAnalyticsV2/charts/ChartWrapper.jsx
- src/components/AdvanceAnalyticsV2/data/constants.js
- src/components/AdvanceAnalyticsV2/data/hooks.js
- src/components/AdvanceAnalyticsV2/data/hooks.test.jsx
- src/components/AdvanceAnalyticsV2/styles/index.scss
- src/components/AdvanceAnalyticsV2/tabs/AnalyticsTable.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.jsx
- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.test.jsx
- src/data/services/EnterpriseDataApiService.js
- src/data/services/tests/EnterpriseDataApiService.test.js
- src/setupTest.js
**Description:** 
* Integrate all advance analytics plotly charts 
* Refactor to create reusable table and chart components
**JIRA:**
* https://2u-internal.atlassian.net/browse/ENT-9237
* https://2u-internal.atlassian.net/browse/ENT-9238
* https://2u-internal.atlassian.net/browse/ENT-9239
> feat: integrate advance analytics charts

- src/components/subsidy-request-modals/ApproveCouponCodeRequestModal.jsx
- src/components/subsidy-request-modals/ApproveLicenseRequestModal.jsx
> fix: memoized the course run ids passed to useApplicableCatalogs

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/Stats.jsx
- src/components/AdvanceAnalyticsV2/data/constants.js
- src/components/AdvanceAnalyticsV2/data/hooks.js
- src/components/AdvanceAnalyticsV2/styles/index.scss
- src/components/AdvanceAnalyticsV2/tests/Stats.test.jsx
- src/data/services/EnterpriseDataApiService.js
> feat: integrate initial aggregates data on analytics v2 page

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/DownloadCSVButton.jsx
- src/components/AdvanceAnalyticsV2/DownloadCSVButton.test.jsx
- src/components/AdvanceAnalyticsV2/Header.jsx
- src/components/AdvanceAnalyticsV2/charts/ChartWrapper.jsx
- src/components/AdvanceAnalyticsV2/data/constants.js
- src/components/AdvanceAnalyticsV2/data/hooks/index.js
- src/components/AdvanceAnalyticsV2/data/hooks/useEnterpriseEnrollmentsData.js
- src/components/AdvanceAnalyticsV2/data/utils.js
- src/components/AdvanceAnalyticsV2/data/utils.test.js
- src/components/AdvanceAnalyticsV2/tabs/AnalyticsTable.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
- src/components/AdvanceAnalyticsV2/tests/AnalyticsV2Page.test.jsx
- src/data/services/EnterpriseDataApiService.js
__Jira Ticket:__ [ENT-9420](https://2u-internal.atlassian.net/browse/ENT-9420)
Updated frontend logic according to the backend changes made in https://github.com/openedx/edx-enterprise-data/pull/489
> feat: Moved enrollments charts to new API endpoint.

- src/components/learner-credit-management/assignment-modal/AssignmentAllocationHelpCollapsibles.jsx
- src/components/learner-credit-management/assignment-modal/AssignmentModalContent.jsx
- src/components/learner-credit-management/assignment-modal/AssignmentModalSummary.jsx
- src/components/learner-credit-management/assignment-modal/AssignmentModalSummaryLearnerList.jsx
- src/components/learner-credit-management/data/utils.js
> fix: bugs related to variant release

- src/components/learner-credit-management/AssignmentEnrollByDateCell.jsx
- src/components/learner-credit-management/AssignmentEnrollByDateHeader.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Surfaces the enroll by date time within the learner credit allocation table.
Updates the text within the enroll by tool tip to remove any indication of time.
> feat: surface time in the enroll-by date column

- src/components/learner-credit-management/cards/tests/CourseCard.test.jsx
- src/components/learner-credit-management/data/utils.js
> fix: don't consider elapsed enrollBy in assignable course runs

- src/components/AdvanceAnalyticsV2/charts/ChartWrapper.jsx
- src/components/AdvanceAnalyticsV2/charts/ScatterChart.jsx
- src/components/AdvanceAnalyticsV2/charts/ScatterChart.test.jsx
- src/components/AdvanceAnalyticsV2/data/utils.js
- src/components/AdvanceAnalyticsV2/data/utils.test.js
- src/components/AdvanceAnalyticsV2/messages.js
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.test.jsx
- src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
**Description:** 
* Translate hover template for all charts.
* Translate legend for scatter chart.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-9399
> feat: translate chart hover template and legend

- src/components/AdvanceAnalyticsV2/data/hooks/index.js
- src/components/AdvanceAnalyticsV2/data/hooks/useEnterpriseCompletionsData.js
- src/components/AdvanceAnalyticsV2/data/hooks/useEnterpriseEngagementData.js
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.test.jsx
__Jira Tickets:__ [ENT-9433](https://2u-internal.atlassian.net/browse/ENT-9433), [ENT-9434](https://2u-internal.atlassian.net/browse/ENT-9434)
Updated completions and engagements tabs in analytics according to performance enhancement updates on the backend.
> feat: Updated completions and engagements tabs in analytics according to performance enhancement updates on the backend.

- __mocks__/react-instantsearch-dom.jsx
- src/components/learner-credit-management/assignment-modal/NewAssignmentModalButton.jsx
- src/components/learner-credit-management/assignment-modal/NewAssignmentModalDropdown.jsx
- src/components/learner-credit-management/cards/tests/CourseCard.test.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/utils.js
Updates the logic which determines the course runs displayed in the learner credit assignment dropdown.
Ensures the following logic:
- Given an existing `enrollBy` date for a course run, the `enrollBy` date is after today's date. If late enrollment is allowed, the `enrollBy` date is after today - `LATE_ENROLLMENTS_BUFFER_DAYS`
- Given an existing `enrollmentStart` and `start` date for a course run, the minimum date between an enrollmentStart and start date must be before the `subsidyExpirationDate` - `MAX_ALLOWABLE_REFUND_THRESHOLD_DAYS`
> fix: Update threshold dates for displaying course runs

- src/components/learner-credit-management/assignments-status-chips/FailedBadEmail.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedCancellation.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedRedemption.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedReminder.jsx
- src/components/learner-credit-management/assignments-status-chips/FailedSystem.jsx
- src/components/learner-credit-management/assignments-status-chips/IncompleteAssignment.jsx
- src/components/learner-credit-management/assignments-status-chips/NotifyingLearner.jsx
- src/components/learner-credit-management/assignments-status-chips/WaitingForLearner.jsx
- src/components/learner-credit-management/data/hooks/index.js
- src/components/learner-credit-management/data/hooks/useStatusChip.jsx
- src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx
- src/components/learner-credit-management/members-tab/MemberStatusTableCell.jsx
- src/components/learner-credit-management/members-tab/status-chips/Accepted.jsx
- src/components/learner-credit-management/members-tab/status-chips/BaseStatusChip.jsx
- src/components/learner-credit-management/members-tab/status-chips/FailedBadEmail.jsx
- src/components/learner-credit-management/members-tab/status-chips/FailedSystem.jsx
- src/components/learner-credit-management/members-tab/status-chips/Pending.jsx
- src/components/learner-credit-management/members-tab/status-chips/Removed.jsx
- src/eventTracking.js
[Jira Ticket ](https://2u-internal.atlassian.net/browse/ENT-9431)- quick change from a click trigger to hover on the status component 
https://github.com/user-attachments/assets/b2529b23-9888-47cc-92cc-48dc25573b23
> fix: changing the trigger of member status

- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/utils.js
When doing comparisons of date using dates and timestamp, use the milliseconds conversion to increase precision. With this change the start date logic comparison of "Is the earliest of 2 start dates (enrollStart OR  start) before the subsidy expiration date minus 14 day threshold.", the resolved logic is now correct.
> fix: switch to valueof when doing unix conversion

- src/components/settings/SettingsAccessTab/ActionsTableCell.jsx
- src/components/settings/SettingsAccessTab/LinkTableCell.jsx
- src/components/settings/SettingsAccessTab/SettingsAccessLinkManagement.jsx
- src/components/settings/SettingsAccessTab/tests/ActionsTableCell.test.jsx
- src/components/settings/SettingsAccessTab/tests/LinkTableCell.test.jsx
- src/components/settings/SettingsAccessTab/tests/__snapshots__/LinkTableCell.test.jsx.snap
- src/components/settings/SettingsAccessTab/utils.js
We want the universal link to get people into the B2B logistration flow.  Including the enterprise slug as part of the learner-portal link will do this for us. Depends on https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1200
The "copy" button now produces: `http://localhost:8734/test-enterprise/invite/8506d723-9a02-4650-bdcd-e3d1c45d6f8a`
ENT-9428
> feat: generate a universal link that includes the enterprise slug

- src/components/AdvanceAnalyticsV2/charts/ChartWrapper.jsx
- src/components/AdvanceAnalyticsV2/charts/ScatterChart.jsx
- src/components/AdvanceAnalyticsV2/charts/ScatterChart.test.jsx
- src/components/AdvanceAnalyticsV2/data/utils.js
- src/components/AdvanceAnalyticsV2/data/utils.test.js
- src/components/AdvanceAnalyticsV2/tabs/Skills.jsx
**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9538
In Analytics V2, the marker size for skills scatter chart is not similar to what we have in scatter chart in V1. 
This PR addresses this issues and incorporates changes to make the bubble marker size consistent with V1.
**Screenshots**
**APSCHE V2 Before**
**APSCHE V2 After**
**5CA V2 Before**
**5CA V2 After**
**PP V2 Before**
**PP V2 After**
> [ENT-9538]: Make analytics V2 skills scatter chart bubble marker size consistent with V1

- src/components/AdvanceAnalyticsV2/charts/ScatterChart.jsx
**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9538
Fixed index mapping for scatter chart. Updated the method to derive the index from the original `data` array instead of `filteredData` to ensure correct marker sizes.
> [ENT-9538] Fixed index mapping for scatter chart

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- I disable the startDate, endDate, Granularity, and Calculation dropdowns while loading aggregates data. 
- Added currentDate as a default date for `Data Updated on`
JIRA -> [ENT-9590](https://2u-internal.atlassian.net/browse/ENT-9590)
> fix: disabale dropdowns while loading data on analyticsV2

- src/components/Admin/__snapshots__/Admin.test.jsx.snap
- src/components/Admin/tabs/DownloadCSVButton.jsx
- src/components/Admin/tabs/ModuleActivityReport.jsx
**Description:** Add a new column(`Extension Requests`) in Module Activity (Executive Education) table on Learner Progress Report page.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-9566
**Screenshot**
> feat: add extension requests column in exec ed module table

- src/components/EnterpriseApp/EnterpriseAppRoutes.jsx
- src/components/EnterpriseApp/index.jsx
- src/components/PeopleManagement/DeleteGroupModal.jsx
- src/components/PeopleManagement/EditGroupNameModal.jsx
- src/components/PeopleManagement/GeneralErrorModal.jsx
- src/components/PeopleManagement/GroupDetailPage.jsx
- src/components/PeopleManagement/constants.js
- src/components/PeopleManagement/index.jsx
- src/components/PeopleManagement/tests/GroupDetailPage.test.jsx
- src/components/PeopleManagement/utils.js
- src/components/learner-credit-management/data/hooks/index.js
- src/components/learner-credit-management/data/hooks/useEnterpriseGroup.js
- src/components/learner-credit-management/data/hooks/useEnterpriseGroupUuid.js
- src/data/services/LmsApiService.js
Creates the card for the groups detail page. Includes functionality for editing the group name and deleting the group. 
https://2u-internal.atlassian.net/browse/ENT-9506
- npm run start:stage
- because we don't actually have the button that will open it, just navigate straight to https://localhost.stage.edx.org:1991/exec-ed-2u-integration-qa/admin/people-management/89e6451c-b187-44b2-b546-ad4511fc34ea
- open up edit and delete modals
> feat: Create group base detail page 

- src/components/PeopleManagement/GroupCardGrid.jsx
- src/components/PeopleManagement/GroupDetailCard.jsx
- src/components/PeopleManagement/ZeroState.jsx
- src/components/PeopleManagement/_PeopleManagement.scss
- src/components/PeopleManagement/index.jsx
- src/components/PeopleManagement/tests/PeopleManagementPage.test.jsx
- src/components/learner-credit-management/data/hooks/index.js
- src/components/learner-credit-management/data/hooks/useAllEnterpriseGroups.js
- src/components/learner-credit-management/data/hooks/useEnterpriseGroupUuid.js
- src/data/services/LmsApiService.js
- src/index.scss
https://github.com/user-attachments/assets/e732e457-4e6c-485f-bd88-3fd6dd063367
> Creating flex group cards for People Management tab

- src/components/learner-credit-management/data/utils.js
> temp: hide restricted runs before we're ready to show them

- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
Helps protect against a case where late redemption is enabled for a budget and a restricted course run's enroll-by date is within the 30 day late enrollment offset. Without this change, we'd potentially surface a restricted run to a customer without a restricted run allowed by any of the customer's catalogs.
> temp: move restrictionType check prior to check for late redemption

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/Stats.jsx
- src/components/AdvanceAnalyticsV2/tabs/AnalyticsTable.jsx
- src/components/AdvanceAnalyticsV2/tests/Stats.test.jsx
Issues:
- Currently on Engagements, Completions, and Leaderboard tabs. The label for the CSV download button for the table is incorrect. All labels have the same text `Download Enrollments CSV`
- By default, Data Granularity is Daily which is not match with currently working analytics.
- Numbers on Stats are not compacting as per original analytics
Fix:
- we change the labels for each tab.
- Engagements:` Download Engagements CSV`
- Completions: `Download Completions CSV`
- Leaderboard: `Download Leaderboard CSV`
- Set `Week` as the default granularity
- If the integer count is more than four then compact that number otherwise show it as is
> fix: download csv button text for data tables

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/tabs/AnalyticsTable.jsx
- Analytics Tabs were not evenly spaced on analytics V2. So fix that issue.
- The last updated date format did not match with original analytics last updated format for fix that issue.
- Download CSV button styles and alignment did not match with original analytics. So fix that issue.
> fix: resolve some issue on analytics v2

- src/components/AdvanceAnalyticsV2/charts/BarChart.jsx
- src/components/AdvanceAnalyticsV2/charts/LineChart.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
**Description:** 
* Sorted the `audit` and `certificate` enrollment types so that `audit` data always comes first.
* Use the `courseKey` instead of `courseTitle` in top 10 courses charts so that we can compare the charts between V1 and V2. This change is needed because we are not `courseTitle` in V1 and this makes chart comparison difficult and add ambiguity.
> fix: analytics v2 fixes

- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/utils.js
Before change, course starts tomorrow, subsidy expires in two days:
After change, same dates for course and subsidy record:
> feat: no 14-day threshold for allowed refundable time

- src/components/PeopleManagement/CreateGroupModal.jsx
- src/components/PeopleManagement/tests/PeopleManagementPage.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9694)
- Checkout branch mkeating/ENT-9694 and visit link https://localhost.stage.edx.org:1991/alc-general/admin/people-management
- Click 'Create group' and go through the group creation process
-  Verify that after creating group, the new group immediately appears in the group listings page without manually refreshing the page
> fix: refresh group list after adding group

- src/components/PeopleManagement/CreateGroupModal.jsx
- src/components/PeopleManagement/CreateGroupModalContent.jsx
- src/components/PeopleManagement/LearnerNotInOrgErrorState.jsx
- src/components/PeopleManagement/tests/CreateGroupModal.test.jsx
- src/components/learner-credit-management/cards/data/utils.js
- src/components/learner-credit-management/data/hooks/index.js
- src/components/learner-credit-management/data/hooks/tests/useEnterpriseLearners.test.jsx
- src/components/learner-credit-management/data/hooks/useEnterpriseLearners.js
- src/components/learner-credit-management/invite-modal/InviteModalContent.jsx
- src/components/learner-credit-management/invite-modal/InviteModalInputFeedback.jsx
- src/components/learner-credit-management/invite-modal/InviteModalSummary.jsx
- src/components/learner-credit-management/invite-modal/InviteSummaryCount.jsx
Adds a check for csv upload to verify that the emails belong to a learner in the org.
https://2u-internal.atlassian.net/browse/ENT-9695
https://github.com/user-attachments/assets/b1a06dac-09d7-4280-ac58-8abb0f24195f
1. visit link https://localhost.stage.edx.org:1991/alc-general/admin/people-management and create a group
2. upload a csv (you can create your own or use this file [testaccountcsv.csv](https://github.com/user-attachments/files/17824608/testaccountcsv.csv)) and verify that the error text and error card appear.
> feat: verify learner email belongs to org

- src/data/services/LmsApiService.js
- src/data/services/tests/LmsApiService.test.js
These changes are to resolve the issue that NUS is facing. Only 10 reports are showing up on the admin portal. This is a temporary solution, I am working on implementing pagination on the Reporting Configuration page.
Issue: https://2u-internal.atlassian.net/browse/ENT-9728
> feat: update pagination for reporting configurations

- src/components/PeopleManagement/DownloadCSVButton.jsx
- src/components/PeopleManagement/PeopleManagementTable.jsx
- src/components/PeopleManagement/data/hooks/useEnterpriseMembersTableData.js
- src/components/PeopleManagement/tests/DownloadCsvButton.test.jsx
- src/utils.js
- src/utils.test.js
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9467)
This change adds a button for downloading the filtered results of the people table on the People Management tab.
- Check out branch and start with `npm run start:stage`
- Navigate to https://localhost.stage.edx.org:1991/exec-ed-2u-integration-qa/admin/people-management
- Click 'Download all' button on People table, verify all people are exported in csv
- Type in search box to filter people by name
- Click 'Download all' button on People table, verify only filtered people are exported in csv
> feat: Add download csv button to people management

- src/components/Admin/AIAnalyticsSummary.jsx
- src/components/Admin/index.jsx
**Ticket:** 
https://2u-internal.atlassian.net/browse/ENT-8817
**Description:** 
For test enterprises, there is incomplete data in analytics, which was causing the `analytics-summary` API to return a bad request error. A validation check has been added to ensure the `Summarize Analytics` button is only displayed for users with complete insights data, against which the analytics summary can be tailored. 
Additionally, the error message has been improved to provide clearer information in case of any technical issues.
> fix: validate insights before rendering analytics summary & improve error message

- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.jsx
- src/components/AdvanceAnalyticsV2/tabs/Leaderboard.test.jsx
__Jira Ticket: [ENT-9809](https://2u-internal.atlassian.net/browse/ENT-9809)
> ENT-9808:  Updated the text according to customer feedback.

- src/components/TableComponent/index.jsx
- src/components/TableComponent/index.test.jsx
- src/data/actions/table.js
- src/data/actions/table.test.js
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-9879
Added a truthy check for the ordering parameter to ensure the application does not throw runtime errors when the ordering query parameter is temporarily missing or null.
> [ENT-9879] Validate 'ordering' parameter before sorting the data

- src/components/EnrollmentsTable/index.jsx
__Jira Ticket:__ [9308](https://2u-internal.atlassian.net/browse/ENT-9308)
This PR introduces 2 new columns `First Name` and `Last Name` for learner progress report table.
**Screenshot:**
> ENT-9308: Added user first and last name for LPR.

- src/components/PeopleManagement/index.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9851)
This change adds a loading skeleton for the groups cards section while groups are loading.
- Check out branch and start with `npm run start:stage`
- Navigate to https://localhost.stage.edx.org:1991/exec-ed-2u-integration-qa/admin/people-management
- Verify groups cards section has a loading Skeleton, which is replaced by the groups cards when loading finishes
> fix: don't show groups cards zero state while groups data is loading

- src/components/PeopleManagement/index.jsx
- src/components/PeopleManagement/tests/PeopleManagementPage.test.jsx
- src/components/learner-credit-management/data/hooks/index.js
- src/components/learner-credit-management/data/hooks/useAllFlexEnterpriseGroups.js
Fixes bug on the People Management view that is currently displaying all groups (both flex and budget) to all customers. The behavior we want is to only show `flex` groups that were created by that customer.
https://2u-internal.atlassian.net/browse/ENT-9913
1. check out this branch locally and run `npm run start:stage`
2. visit link https://localhost.stage.edx.org:1991/aj-test-co/admin/people-management and confirm that you do not see any group cards displayed. Ensure that you also do not see any results from this endpoint https://courses.stage.edx.org/enterprise/api/v1/enterprise_group/?enterprise_uuids=e035cce5-24dd-4be4-896d-497157c09a39. Lastly, confirm that there are no flex groups for that customer here https://internal.courses.stage.edx.org/admin/enterprise/enterprisegroup/ 
3. …
> feat: updates groups page to show only flex groups for customer

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
JIRA-> [ENT-9927](https://2u-internal.atlassian.net/browse/ENT-9927)
> fix: make the lastUpdatedDate consistent on LPR

- src/components/PeopleManagement/GroupDetailPage/GroupDetailPage.jsx
- src/components/PeopleManagement/tests/GroupDetailPage.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9920)
This change makes the 'View group progress' button on the Group detail page navigate to the Learner Progress Report page with the filter set to the group in question.
- Check out branch and start with npm run start:stage
- Navigate to https://localhost.stage.edx.org:1991/alc-general/admin/people-management/3de34823-664e-4eee-9756-12c25f0172de
- Verify 'View group progress' url has parameter `group_uuid=3de34823-664e-4eee-9756-12c25f0172de`
> feat: View group progress button should link to LPR page filtered by group

- src/components/ReportingConfig/ReportingConfigForm.jsx
- src/components/ReportingConfig/ReportingConfigForm.test.jsx
**Ticket:** [ENT-9945](https://2u-internal.atlassian.net/browse/ENT-9945)
**Description:** Added a checkbox in the reporting configuration page. It is used to enable / disable date suffix inclusion in the report's filename.
> feat: Add Include Date option in enterprise reporting configuration form

- src/components/PeopleManagement/CreateGroupModalContent.jsx
- src/components/PeopleManagement/tests/CreateGroupModal.test.jsx
- src/utils.js
- src/utils.test.js
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-9932)
This change fixes some bugs in the behavior of uploading csv lists of enterprise members to add to a new group.
- Go to the admin-portal repo, pull down branch, and run npm run start:stage
- Upload csv file containing enterprise members
- Click check box next to one of the added members, and click 'Remove'
- Upload same csv file again
- Verify the removed member was re-added
> fix: create group support multiple csv files

- src/components/learner-credit-management/assignment-modal/AssignmentModalContent.jsx
- src/components/learner-credit-management/cards/tests/CourseCard.test.jsx
On the Group assignment modal, when entering email addresses and then deleting them with backspace, the assign button stayed grayed out. This fixes it.
[JIRA ticket](https://2u-internal.atlassian.net/browse/ENT-9934)
[video](https://drive.google.com/file/d/1d7Lk3ueh68xYCxoh1KWsJEX-bqmHBRt8/view?usp=drive_link)
- Go to an enterprise with existing Learner Groups and existing courses
- Go to Leaner Credit Management
- Click on the "catalog" tab
- Click on "Assign" and select a date -> The Assign modal should open
- The Assign button on the bottom should be disabled
- assign a group via the drop down
- The assign button should be enabled
- Enter an email address in the text field
- Delete the email from the text field via backspace again
- The assign button should still be enabled
> fix: assign button grey out

- src/components/PeopleManagement/CreateGroupModalContent.jsx
- src/components/PeopleManagement/tests/CreateGroupModal.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10046)
This change makes it so that when members are repeatedly added to a group from the member table, a duplicate error is not shown.
- Go to the admin-portal repo, pull down branch, and run npm run start:stage
- Check one member and click 'Add' button
- While leaving first member checked, check another member in the table, click 'Add' again
- Verify that both members are shown in the Summary section, and there is no error message indicating duplicate members have been added.
> fix: in group creation don't show duplicate error message when members added again

- src/components/PeopleManagement/CreateGroupModalContent.jsx
- src/components/PeopleManagement/tests/CreateGroupModal.test.jsx
- src/components/learner-credit-management/cards/data/utils.ts
- src/utils.js
- src/utils.test.js
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10024)
This change makes it so that if an invalid email csv file is uploaded, the error will clear once a valid csv file is uploaded.
- Go to the admin-portal repo, pull down branch, and run npm run start:stage
- Upload csv file containing one or more invalid emails
- Verify error message is shown
- Upload csv file containing only valid emails
- Verify error message disappears
> fix: clear errors from invalid group email csv upload

- src/data/services/LmsApiService.ts
- src/data/services/tests/LmsApiService.test.js
This change fixes an issue with group creation introduced in https://github.com/openedx/frontend-app-admin-portal/pull/1426.
- Go to the admin-portal repo, pull down branch, and run npm run start:stage
- Add name, members, and click 'Create'
- Verify group is created with learners populated and no error messages
> fix: createEnterpriseGroup response camelCase

- .eslintrc.js
- .github/workflows/ci.yml
- docs/decisions/0010-algolia-filters-catalog-query-uuids.rst
- src/components/NewFeatureAlertBrowseAndRequest/index.jsx
- src/components/algolia-search/index.ts
- src/components/algolia-search/useAlgoliaSearch.ts
- src/components/algolia-search/withAlgoliaSearch.test.tsx
- src/components/algolia-search/withAlgoliaSearch.tsx
- src/components/settings/SettingsLMSTab/UnsavedChangesModal.tsx
- src/components/settings/SettingsSSOTab/steps/NewSSOConfigConfirmStep.tsx
- src/types.d.ts
- tsconfig.json
[ENT-10080](https://2u-internal.atlassian.net/browse/ENT-10080)
Introduces `withAlgoliaSearch` Higher-Order-Component (HOC) for consuming components to get access to the Algolia search client to serve search results.
The `withAlgoliaSearch` component is connected to the Redux store to get access to the feature flag and the enterprise customer UUID. The rest of the logic is encapsulated within `useAlgoliaSearch`.
Based on the `enterpriseFeatures.catalogQuerySearchFiltersEnabled`, `useAlgoliaSearch` will conditionally make an API call to `<enterprise-catalog>/api/v1/enterprise-customer/<enterprise_id>/secured-algolia-api-key/` to generate a secured Algolia API key and get the mappings of catalog uuids <> catalog query UUIDs for further filtering.
If the feature flag is enabled and a secured …
> feat: introduce `withAlgoliaSearch` and `useAlgoliaSearch`

- src/components/PeopleManagement/tests/AddMembersModal.test.jsx
- src/components/learner-credit-management/cards/data/utils.ts
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10195)
This fixes the issue when creating/adding users to a group via csv upload and getting an error when the email addresses differ from the org registered email in casing alone.
- Go to the admin-portal repo and run `npm run start:stage`
- Create a csv file containing the email of an org member with casing that differs from the People table
- Verify the uploaded user can be added, without any error messages indicating they aren't part of the org
> fix: Email Matching in CSV upload should be case-insensitive

- src/components/PeopleManagement/AddMembersModal/AddMembersModal.jsx
- src/components/PeopleManagement/AddMembersModal/AddMembersModalContent.jsx
- src/components/PeopleManagement/CreateGroupModal.jsx
- src/components/PeopleManagement/CreateGroupModalContent.jsx
- src/components/PeopleManagement/EnterpriseCustomerUserDataTable.jsx
- src/components/PeopleManagement/LearnerDetailPage/CourseEnrollments.jsx
- src/components/PeopleManagement/data/ValidatedEmailsContext.tsx
- src/components/PeopleManagement/data/reducer.ts
- src/components/PeopleManagement/tests/CreateGroupModal.test.jsx
- src/components/learner-credit-management/cards/data/utils.ts
- src/components/learner-credit-management/invite-modal/InviteModalSummary.tsx
- src/components/learner-credit-management/invite-modal/InviteSummaryCount.tsx
- src/utils.js
- src/utils.test.js
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10244)
Fix for issue where attempting to click and add a member whose email address does not have all lowercase letters will result in adding the user to the summary, but:
- The checkbox is not checked
- Clicking checkbox again will add the user multiple times, creating duplicate user errors instead of removing the user
- Go to the admin-portal repo and run `npm run start:stage`
- Navigate to https://localhost.stage.edx.org:1991/aj-test-co/admin/people-management
- Navigate to second page and you will find user that has a capitalized letter in their email address
- Click this user's checkbox and verify their (lowercased) email is added to the summary
- Click user's checkbox again and verify their email is …
> fix: add/remove group member with non-lowercase email

- src/components/AdminV2/AdminCards.jsx
- src/components/AdminV2/AnalyticsOverview.jsx
- src/components/AdminV2/cards/NumberCard/DetailsAction.jsx
- src/components/AdminV2/cards/NumberCard/DetailsAction.test.jsx
- src/components/AdminV2/cards/NumberCard/NumberCard.test.jsx
- src/components/AdminV2/cards/NumberCard/index.jsx
- src/components/AdminV2/tests/Admin.test.jsx
- src/components/AdminV2/tests/AdminCards.test.jsx
- src/containers/AdminCardsV2/index.jsx
__Jira Ticket:__ [ENT-10240](https://2u-internal.atlassian.net/browse/ENT-10281)
This PR adds a new component to use for showing the cards at the top section of Learner Progress Report.
> ENT-10281: Added a new card component for admin portal.

- src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementRemindModal.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementRevokeModal.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRemindModal.test.jsx
- src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRevokeModal.test.jsx
Updated logic behind the bulk revoke logic when selecting all items within a table with filters enabled. We modify to logic to correctly fall into the codepath of passing filters as options to the bulk revoke logic.
> fix: modify bulk revoke logic

- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
Customers noticed that the start date for a run would appear to differ between the admin-portal and learner-portal.  As it turns out, these two frontends have slightly different implementations.  This commit causes admin-portal to mirror the learner-portal implementation:
https://github.com/openedx/frontend-app-learner-portal-enterprise/blob/552babb373deba21e52587b3fd3a306e00bf33a9/src/components/course/data/utils.jsx#L97
ENT-10122
> fix: future courses should never appear to start today

- src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
- src/components/AdvanceAnalyticsV2/constants.js
- src/components/AdvanceAnalyticsV2/data/hooks/index.js
- src/components/AdvanceAnalyticsV2/data/hooks/useEnterpriseCompletionsData.js
- src/components/AdvanceAnalyticsV2/data/hooks/useEnterpriseEngagementData.js
- src/components/AdvanceAnalyticsV2/data/hooks/useEnterpriseEnrollmentsData.js
- src/components/AdvanceAnalyticsV2/tabs/AnalyticsTable.jsx
- src/components/AdvanceAnalyticsV2/tabs/Completions.jsx
- src/components/AdvanceAnalyticsV2/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
- src/components/learner-credit-management/data/hooks/useAllFlexEnterpriseGroups.js
__Jira Ticket:__ [ENT-10130](https://2u-internal.atlassian.net/browse/ENT-10130)
Add a new single select drop down menu to display a list of groups for admin analytics, this will be enabled for enrollments, engagements and completions data only and will not have any affect on skills and leaderboard data. The list can be fetched from enterprise API endpoint [edx-enterprise/enterprise/api/v1/urls.py at master · openedx/edx-enterprise](https://github.com/openedx/edx-enterprise/blob/master/enterprise/api/v1/urls.py#L85) When a user make a selection then we need to pass in the selected group’s uuid via group_uuid named parameter in API calls to the backend.
> feat: Enabled group functionality for groups.

- src/components/learner-credit-management/assignment-modal/NewAssignmentModalDropdown.jsx
Ticket: https://2u-internal.atlassian.net/browse/ENT-10376
Memoizes `dayjs()` with `useMemo` and `getStartLabel` with `useCallback` to ensure its stable between re-renders to prevent "Starts" switching to "Started" on a re-render (e.g., on click) in button text, and vice versa.
See below for examples.
https://github.com/user-attachments/assets/cad20f22-ed58-4892-9426-d0ae88776063
https://github.com/user-attachments/assets/c3924f5b-e9b4-47b0-883b-c790daa3599f
> fix: resolve erroneous start label by memoizing `now`

- src/components/PeopleManagement/AddMembersModal/AddMembersModal.tsx
- src/components/PeopleManagement/CreateGroupModal.tsx
- src/components/PeopleManagement/GroupDetailPage/GroupDetailPage.jsx
- src/components/PeopleManagement/GroupInviteErrorToast.tsx
- src/components/PeopleManagement/constants.js
- src/components/PeopleManagement/index.jsx
- src/components/PeopleManagement/tests/CreateGroupModal.test.jsx
- src/components/PeopleManagement/tests/GroupInviteErrorToast.test.jsx
- src/components/PeopleManagement/utils.ts
- src/data/services/LmsApiService.ts
- src/eventTracking.js
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10243)
https://github.com/user-attachments/assets/c7266bcc-c440-43d4-bfec-330b6e2769d5
This change adds an error toast after an attempt to invite non-org learners to a flex group fails on the backend.
- In Admin Portal, create a new flex Group, populating via csv file that includes at least one learner email from outside the enterprise customer org
- Verify Toast appears with error message
> feat: display toast when non-org group members can't be invited

- src/components/Admin/index.jsx
- src/components/AdminV2/index.jsx
- src/components/LearnerActivityTable/index.jsx
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-10467
When switching between different learner activity tabs (e.g., "active past week" → "inactive past month"), the pagination state `pageIndex` was not resetting. This caused the new tab to load with the previous tab's page number.
To let React treat each instance of `LearnerActivityTable` as unique, I have added a unique `key` prop. This ensures React fully unmounts and remounts the component when switching tabs, allowing the pagination state to reset naturally.
> [ENT-10467] Fix: Pagination Issue in LearnerActivityTable

- src/components/InviteLearnersModal/inviteLearnerModal.test.jsx
- src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx
- src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
- src/components/learner-credit-management/BudgetOverviewContent.jsx
- src/components/learner-credit-management/BudgetStatusSubtitle.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/empty-state/NoBnRBudgetActivity.jsx
- src/components/learner-credit-management/empty-state/messages.js
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
**Ticket:** [ENT-10295](https://2u-internal.atlassian.net/jira/software/c/projects/ENT/boards/868?selectedIssue=ENT-10295)
**Description:** Added an empty state for BnR enabled learner credit budgets. The empty state is dependent on `bnrEnabled` flag on `SubsidyAccessPolicy`, `hasApprovedBnrRequests`, and `hasSpentTransactions` variable.
Other than that,
- I've changed the top left subtitle to `Browse & Request`.
- I've also added the `configure access` button and the relevant text to match the design.
> feat: add empty state on activity tab for BnR budgets

- src/components/learner-credit-management/BudgetDetailRequestsTabContent.jsx
- src/components/learner-credit-management/requests-tab/DeclineBnrSubsidyRequestModal.jsx
- src/data/services/EnterpriseAccessApiService.ts
- src/data/services/tests/EnterpriseAccessApiService.test.js
JIRA- [ENT10355](https://2u-internal.atlassian.net/browse/ENT-10355)
https://github.com/user-attachments/assets/4d88d105-b1b8-45c1-aaee-c04bef47b897
> feat: add and integrated decline modal for BNR requests

- src/components/EnterpriseSubsidiesContext/data/hooks.js
- src/components/EnterpriseSubsidiesContext/data/tests/hooks.test.jsx
- src/components/learner-credit-management/AssignmentAmountTableCell.jsx
- src/components/learner-credit-management/AssignmentStatusTableCell.jsx
- src/components/learner-credit-management/BudgetAssignmentsTable.jsx
- src/components/learner-credit-management/BudgetDetail.jsx
- src/components/learner-credit-management/BudgetDetailAssignments.jsx
- src/components/learner-credit-management/BudgetDetailTabsAndRoutes.jsx
- src/components/learner-credit-management/SubBudgetCard.jsx
- src/components/learner-credit-management/SubBudgetCardUtilization.jsx
- src/components/learner-credit-management/data/hooks/tests/useBudgetDetailTabs.test.jsx
- src/components/learner-credit-management/data/hooks/tests/useSubsidyAccessPolicy.test.jsx
- src/components/learner-credit-management/data/hooks/useBudgetDetailTabs.jsx
- src/components/learner-credit-management/data/hooks/useBudgetId.js
- src/components/learner-credit-management/data/hooks/useEnterpriseFlexGroups.js
- src/components/learner-credit-management/data/hooks/useSubsidyAccessPolicy.ts
- src/components/learner-credit-management/data/types.ts
- src/components/learner-credit-management/data/utils.js
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Ticket: [ENT-10462](https://2u-internal.atlassian.net/browse/ENT-10462)
* Only display the `AssignMoreCoursesEmptyStateMinimal` (if applicable) when the catalog is NOT expired and/or retired.
* If navigating to the Catalog tab's page route directly for an expired and/or retired budget, redirect to the default Activity tab's page route instead.
* Increases the `page_size` for the `enterprise_group` list API to prevent needing to traverse as many paginated API requests to retrieve group memberships.
> fix: prevent access to catalog tab in LCM for expired/retired budgets

- src/components/learner-credit-management/data/hooks/tests/useBnrSubsidyRequests.test.jsx
- src/components/learner-credit-management/data/hooks/useBnrSubsidyRequests.js
- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
- src/data/services/EnterpriseAccessApiService.ts
- src/data/services/tests/EnterpriseAccessApiService.test.js
**Description:** Pass the policy uuid to only get requests for a specific policy.
> fix: fetch requests based on policyUuid

- src/components/learner-credit-management/BudgetDetailApprovedRequestTable.jsx
- src/components/learner-credit-management/requests-tab/RequestsTable.jsx
**Ticket:** [ENT-10729](https://2u-internal.atlassian.net/browse/ENT-10729)
**Description:** Disabled sorting for both (Pending and Requests) table. Also hid the filters on activity tab.
> chore: disable sorting and filtering for bnr

- src/components/learner-credit-management/RequestStatusTableCell.jsx
- src/components/learner-credit-management/data/constants.js
- src/components/learner-credit-management/request-status-chips/FailedRedemption.jsx
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
- src/eventTracking.js
**Ticket:** [ENT-10732](https://2u-internal.atlassian.net/browse/ENT-10732)
**Description:** Added a chip component to display failed redemption error status in approved requests table.
> feat: add failed redemption chip for approved requests table

- src/components/AdvanceAnalyticsV2.0/AnalyticsFilters.jsx
- src/components/AdvanceAnalyticsV2.0/data/constants.js
- src/components/AdvanceAnalyticsV2.0/data/hooks/useEnterpriseEngagementData.js
- src/components/AdvanceAnalyticsV2.0/data/hooks/useEnterpriseEngagementData.test.js
- src/components/AdvanceAnalyticsV2.0/tabs/Engagements.jsx
- src/components/AdvanceAnalyticsV2.0/tabs/Outcomes.jsx
- src/components/AdvanceAnalyticsV2.0/tabs/Progress.jsx
- src/components/AdvanceAnalyticsV2.0/tests/AnalyticsFilters.test.jsx
**Description**: This PR wires the courseType (OCM or EE) to the backend service call and also enables the dropdown for the AnalyticsV2. Some fixes related to start and end dates state management within the respective tabs are also included.
**JIRA**: [ENT-10718](https://2u-internal.atlassian.net/browse/ENT-10718)
**Screenshots**
> feat: Added course type filter for Analytics V2

- src/components/learner-credit-management/search/CatalogSearchResults.jsx
- src/components/subscriptions/SubscriptionDetails.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
- src/components/subscriptions/buttons/DownloadCsvButton.jsx
- src/components/subscriptions/buttons/InviteLearnersButton.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Files to refactor:
- src/components/learner-credit-management/search/CatalogSearchResults.jsx
- src/components/subscriptions/SubscriptionDetails.jsx
- src/components/subscriptions/SubscriptionManagementPage.jsx
- …
> Replace of injectIntl with useIntl() 2/4

- package-lock.json
- package.json
- src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
Follow up to recently merged PR -> https://github.com/openedx/frontend-app-admin-portal/pull/1194 which takes the initiative to optimize the bundled package by removing usage of [faker-js](https://www.npmjs.com/package/@faker-js/faker).
Removes the  faker-js package from the repo. The only remaining usage was a set of fake email addresses that has been hard coded. There are no factories that exist that utilize faker.
> chore: remove the faker package from repo

- src/components/ProductTours/CheckpointOverlay.tsx
- src/components/ProductTours/tests/CheckpointOverlay.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10794)
- Expanded the 'window' over the element that is the focus of the tour step, bringing appearance more in line with [Figma designs](https://www.figma.com/design/QvzeKm2skgshekt88CXsoY/Admin-Portal-Onboarding?node-id=2012-15629&t=HrAKYwO831qhDmll-0)
- Pull down this branch and run `npm run start:stage`
- Navigate to https://localhost.stage.edx.org:1991/exec-ed-2u-integration-qa/admin/subscriptions/manage-learners
- Open Quick Start Guide and select 'Administer Subscriptions'
- Go through subscription tour and verify the highlight window over tour elements has some additional aesthetic spacing around the element
> feat: expand highlight window for tour elements

- src/components/learner-credit-management/data/hooks/useBudgetDetailActivityOverview.js
After I merged [this PR](https://github.com/openedx/frontend-app-admin-portal/pull/1679) and was testing on prod, I noticed that a customer that I know had spent and assigned transactions was showing up as zero state. To test this PR, go to https://localhost.stage.edx.org:1991/pawnee-parks/admin/learner-credit/ and validate that it is not showing up as zero state.
> fix: fixing bug in useBudgetDetailActivityOverview hook

- src/components/AdvanceAnalyticsV2.0/Stats.jsx
- src/components/AdvanceAnalyticsV2.0/tests/Stats.test.jsx
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-10947
This PR integrates the data for following metics:
- Unique Skills Gained
- Upskilled Learners
- New Skills Learned This Year
> [ENT-10947] Integrate Outcomes Metrics Data

- src/components/learner-credit-management/data/tests/utils.test.js
- src/components/learner-credit-management/data/utils.js
This pull request improves the robustness of the `orderBudgets` utility function and its associated tests in the learner credit management module. The main focus is on handling budgets with missing metadata, specifically when `start` or `end` dates are `null`, ensuring that sorting behaves predictably even with incomplete data. Additionally, import statements have been cleaned up for better readability.
**Enhancements to budget sorting:**
* Updated `orderBudgets` in `utils.js` to handle `null` end dates, ensuring that budgets with missing end dates are always sorted to the end of the list.
* Added a new test case in `utils.test.js` to verify that `orderBudgets` correctly sorts budgets when some have missing `start` or `end` metadata.
**Code organization and readability:**
* Cleaned up and …
> fix: handle null values in sort heuristic

- src/components/ProductTours/AdminOnboardingTours/AdminOnboardingTours.tsx
- src/components/ProductTours/AdminOnboardingTours/flows/AdminOnboardingTour.tsx
- src/components/ProductTours/AdminOnboardingTours/flows/LearnerProgressFlow.tsx
- src/components/ProductTours/AdminOnboardingTours/messages.js
- src/components/ProductTours/AdminOnboardingTours/tests/LearnerProgressFlow.test.jsx
Removed the step explaining the AI insights because it was dynamically rendering after the tour and causing errors. Also, since the "Module activity (Executive Education)" tab highlight was at the end, if the customer didn't have it the complete_tour_flow logic never triggered, so customer's without it couldn't complete the flow. Moved it to the middle, so if it doesn't render it doesn't effect the overall experience. 
[Jira ticket
](https://2u-internal.atlassian.net/browse/ENT-10968)
To test locally, replace your EntepriseDataApiService with this file with mocked data. 
[MockEnterpriseDataApiService.txt](https://github.com/user-attachments/files/22542751/MockEnterpriseDataApiService.txt)
> fix: fixing bug in Track Learner Progress onboarding flow
