__mocks__/fileMock.js, src/components/Courseware/CoursewareContent/CoursewareContent.test.jsx, src/components/Courseware/CoursewareContent/__snapshots__/CoursewareContent.test.jsx.snap, src/components/Courseware/CoursewareContent/index.jsx, src/components/Courseware/CoursewareNav/CoursewareNav.mocks.js, src/components/Courseware/CoursewareNav/CoursewareNav.test.jsx, src/components/Courseware/CoursewareNav/__snapshots__/CoursewareNav.test.jsx.snap, src/components/Courseware/CoursewareNav/index.jsx, src/containers/App/App.test.jsx, src/containers/App/__snapshots__/App.test.jsx.snap, src/containers/CoursewarePage/CoursewarePage.test.jsx, src/containers/CoursewarePage/index.jsx, src/data/actions/index.test.js, src/data/reducers/courseOutline.test.js
=> Add tests for components and actions

package.json, src/components/Courseware/CoursewareContent/UnitNav/index.jsx, src/components/Courseware/CoursewareContent/index.jsx, src/components/Courseware/CoursewareNav/index.jsx, src/components/Courseware/index.jsx, src/components/Footer/index.jsx, src/components/Header/index.jsx, src/containers/App/__snapshots__/App.test.jsx.snap, src/containers/FAQSupportPage/index.jsx, src/containers/HomePage/index.jsx, src/containers/NotFoundPage/index.jsx, src/data/actions/courseOutline.js, src/data/actions/courseOutline.test.js
* Removes instances of `container-fluid` in favor of just using `container`;
* Fixes several linting issues I had when committing;
* Updates the `name`, `repository`, and `description` fields in `package.json`;
* Removes the `--passWithNoTests` flag for `npm run test`;
* Updates the snapshots.
=> Remove container-fluid, fix linting, and other misc fixes

src/components/Admin/Admin.test.jsx, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx, src/containers/AdminPage/index.jsx, src/containers/LogoutHandler/index.jsx, src/data/reducers/dashboardAnalytics.js, src/data/reducers/dashboardAnalytics.test.js
This is currently based on the csv download PR (https://github.com/edx/edx-portal/pull/24)
=> ENT-1073 Add last updated date to the admin dashboard

package-lock.json, package.json
https://github.com/edx/paragon/pull/308
=> Upgrades paragon to 3.3.5 to fix react-dom issue

package-lock.json, package.json, src/components/Admin/Admin.scss, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx, src/components/EnterpriseList/EnterpriseList.test.jsx, src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap, src/components/EnterpriseList/index.jsx, src/components/Header/Header.scss, src/components/Header/index.jsx, src/components/LinkWrapper/index.jsx, src/components/LoadingMessage/LoadingMessage.scss, src/components/LoadingSpinner/index.jsx, src/components/LoginForm/LoginForm.scss, src/components/LoginForm/__snapshots__/LoginForm.test.jsx.snap, src/components/LoginForm/index.jsx, src/containers/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap, src/containers/ErrorPage/index.jsx, src/containers/Footer/Footer.scss, src/containers/Header/__snapshots__/Header.test.jsx.snap, src/index.scss
Fixes/updates the following:
* Does not clear login form on submit (e.g., input stays on error);
* Use `Icon` from Paragon in download CSV button;
* Fixes the position of the download CSV button and last updated date;
* Fixes minor spacing issues throughout;
* Removes `tableSortable` from enterprise list table since sorting is not supported (yet);
* Uses `LinkWrapper` instead of `Link` in `Dropdown` menu items;
* Sets a smaller `max-width` size of 100px on the enterprise logos in the `Header`/`Footer`;
* Upgrades Paragon to latest version;
* Set a height on the loading message for enterprise list;
* Ensure all `button` elements use pointer cursor on hover;
* Adds beta badge back into the `Header`;
* Updates snapshots/tests.
=> UI & dropdown fixes

src/containers/EnterpriseApp/index.jsx, src/containers/ErrorPage/ErrorPage.test.jsx, src/containers/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap, src/containers/ErrorPage/index.jsx, src/index.jsx
Redirecting to /404 and /error wasn't a great experience. You lost
your original URL. You couldn't use the back button or you'd just be
redirected again. This PR renders the same content, but renders it as
components instead of all the redirect madness.
=> Uses NotFound and Error components instead of redirects

src/components/TableWithPagination/TableWithPagination.scss, src/data/actions/authentication.test.js, src/data/actions/courseEnrollments.test.js, src/data/services/EnterpriseDataApiService.js, src/data/services/LmsApiService.js
* Adds trailing slashes to all API calls to resolve the issue where API response would get a 500 in Firefox/Safari.
* Removes white background on sortable buttons in column headers in `TableWithPagination` component.
=> Minor UI fix and fixing trailing slash issue

src/data/history.js, src/data/store.js, src/index.jsx
Two issues:
- Missing routerMiddleware
- Had two routers defined, one from react-router-redux as well as the default BrowserRouter from react-router-dom
=> ENT-1179. Fix react router / redux to dispatch LOCATION_CHANGE events

src/components/CourseEnrollments/CourseEnrollments.test.jsx, src/components/CourseEnrollments/index.jsx, src/components/EnterpriseList/EnterpriseList.test.jsx, src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap, src/components/EnterpriseList/index.jsx, src/components/TableWithPagination/TableWithPagination.test.jsx, src/components/TableWithPagination/index.jsx
This reverts commit 90cf52c11db69127a70f139f5c3bc832f4d02a42, reversing
changes made to 653d75810c6ab38df87d372cfd1a086393c23576.
=> Revert "Merge branch 'astankiewicz/client-table-sorting'"

src/demo/data.js, src/demo/rewireEnterpriseDataApiService.js, src/demo/rewireEnterpriseDataApiService.test.js
This adds support for sorting to the demoDataLoader.js script. Also a small change to only pull
in the english locale for faker, as that library is quite large
=> Add support for sorting of demo data

src/components/Admin/index.jsx, src/components/CompletedLearnersTable/CompletedLearnersTable.test.jsx, src/components/CompletedLearnersTable/__snapshots__/CompletedLearnersTable.test.jsx.snap, src/components/CompletedLearnersTable/index.jsx, src/data/services/EnterpriseDataApiService.js
This PR adds front-end functionality for getting number of completed courses against each learner.
Related enterprise-data PR: https://github.com/edx/edx-enterprise-data/pull/61
[ENT-1167](https://openedx.atlassian.net/browse/ENT-1167)
[ENT-1216](https://openedx.atlassian.net/browse/ENT-1216)
=> Learner completed courses

README.md
This README update makes sense with a small update to edx-analytics-data-api README (which I will open soon/potentially with updates related to a management command)
=> Updating the README with some more detailed instructions.

src/components/CompletedLearnersTable/index.jsx, src/components/EnrolledLearnersTable/index.jsx, src/components/LearnerActivityTable/index.jsx, src/components/PastWeekPassedLearnersTable/PastWeekPassedLearnersTable.test.jsx, src/components/PastWeekPassedLearnersTable/__snapshots__/PastWeekPassedLearnersTable.test.jsx.snap, src/components/PastWeekPassedLearnersTable/index.jsx, src/components/RegisteredLearnersTable/index.jsx
While working on [ENT-1227 - Demo data for M2](https://openedx.atlassian.net/browse/ENT-1227), I  found that some tables were having issues related to pagination and sorting. This PR fixes the issues and the tests.
=> Fix pagination and sorting

src/components/Admin/Admin.test.jsx, src/components/Admin/AdminCards.jsx, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx, src/components/EnrolledLearnersForInactiveCoursesTable/EnrolledLearnersForInactiveCoursesTable.test.jsx, src/components/EnrolledLearnersForInactiveCoursesTable/__snapshots__/EnrolledLearnersForInactiveCoursesTable.test.jsx.snap, src/components/EnrolledLearnersForInactiveCoursesTable/index.jsx, src/data/services/EnterpriseDataApiService.js
Show learners with inactive courses with following columns:
- `Email`
-  `Total Course Enrollment Count`
- `Total Completed Courses Count`
- `Last Activity Date`
**Related backend changes in data API:** https://github.com/edx/edx-enterprise-data/pull/66
=> ENT-1189 Show learners with inactive courses

src/demo/data.js, src/demo/data.test.js, src/demo/rewireEnterpriseDataApiService.js, src/demo/rewireEnterpriseDataApiService.test.js
This PR adds demo data for M2.
[ENT-1227](https://openedx.atlassian.net/browse/ENT-1227)
=> Demo data for M2

config/webpack.dev.config.js, config/webpack.prod.config.js, src/components/Admin/Admin.test.jsx, src/components/Admin/AdminCards.jsx, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/config/index.js, src/containers/EnterpriseApp/index.jsx
This PR removes the `DASHBOARD_V2` feature flag to officially roll out Milestone 2 of the admin dashboard.
=> ENT-1329. Remove DASHBOARD_V2 feature flag

config/webpack.dev.config.js, config/webpack.prod.config.js, package-lock.json, package.json, src/config/index.js, src/data/apiClient.js, src/index.jsx, src/utils.js
See https://github.com/edx/frontend-auth/pull/6 for details.
=> Fix login redirect loop.

.eslintrc, package-lock.json, package.json, src/components/CodeAssignmentModal/BulkAssignFields.jsx, src/components/CodeAssignmentModal/CodeAssignmentModal.scss, src/components/CodeAssignmentModal/FileInput.jsx, src/components/CodeAssignmentModal/FileInput.scss, src/components/CodeAssignmentModal/IndividualAssignFields.jsx, src/components/CodeAssignmentModal/TextAreaAutoSize.jsx, src/components/CodeAssignmentModal/emailTemplate.js, src/components/CodeAssignmentModal/index.jsx, src/components/Coupon/index.jsx, src/components/CouponDetails/index.jsx, src/components/EnterpriseApp/index.jsx, src/components/NumberCard/NumberCard.scss, src/components/RenderField/index.jsx, src/components/RequestCodesPage/RequestCodesForm.jsx, src/components/Sidebar/Sidebar.scss, src/containers/EnterpriseApp/EnterpriseApp.test.jsx, src/index.scss, src/utils.js
This PR contains the `CodeAssignmentModal` for individual & bulk assign. 
_**NOTE:**  This PR should be reverted once the demo is over._
=> [DEMO] Admin Portal with Assignment Modals

src/components/CodeAssignmentModal/BulkAssignFields.jsx, src/components/CodeAssignmentModal/FileInput.jsx, src/components/CodeAssignmentModal/FileInput.scss, src/components/CodeAssignmentModal/TextAreaAutoSize.jsx, src/components/CodeAssignmentModal/index.jsx
Introduced some changes in the `CodeAssignmentModal` component that should be in the `astankiewicz/assignment-modal` branch.
=> CodeAssignmentModal & CSV upload changes

src/components/CouponDetails/index.jsx, src/components/DownloadCsvButton/index.jsx, src/data/services/EcommerceApiService.js
This PR adds API calls for coupon overview and coupon codes details.
This also ads f/e implementation for CSV download for coupon codes.
[ENT-1346](https://openedx.atlassian.net/browse/ENT-1346)
=> Coupon codes endpoints

src/components/CodeManagement/index.jsx, src/components/Coupon/Coupon.test.jsx, src/containers/CodeAssignmentModal/CodeAssignmentModal.test.jsx, src/containers/CodeManagementPage/CodeManagementPage.test.jsx, src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap, src/containers/EnterpriseApp/EnterpriseApp.test.jsx
This PR adds and/or updates tests for the following components:
* `Coupon`
* `CodeManagementPage`
* `CouponDetails`
* `CodeAssignmentModal`
* The tests for this modal are still minimal; will be completed in a subsequent PR to keep this PR size down.
* `EnterpriseApp`
* Fixes a test to avoid a prop type warning.
=> Adding tests for code management related components

src/components/CodeManagement/index.jsx, src/components/CouponDetails/index.jsx, src/containers/CodeManagementPage/index.jsx, src/demo/coupons.js, src/demo/data.js, src/demo/rewireEcommerceApiService.js
This PR adds demo data for code management screen.
[ENT-1335](https://openedx.atlassian.net/browse/ENT-1335)
=> Demo data for code management

src/components/CouponDetails/index.jsx, src/demo/coupons.js, src/demo/rewireEcommerceApiService.js
The purpose of this PR is to call coupon details API for selected coupon code filter/toggle.
This also adds demo data work related to filters.
[ENT-1471](https://openedx.atlassian.net/browse/ENT-1471)
=> Filter coupon details and demo data

src/components/CodeAssignmentModal/index.jsx, src/components/CouponDetails/index.jsx, src/containers/CodeAssignmentModal/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap, src/data/actions/codeAssignment.js, src/data/services/EcommerceApiService.js, src/demo/coupons.js
This PR adds the capability to call coupon code assignment api. 
Furthermore, this also correctly sets code key column instead of `title`
[ENT-1447](https://openedx.atlassian.net/browse/ENT-1447)
[ENT-1485](https://openedx.atlassian.net/browse/ENT-1485)
=> Coupon backend integration

src/components/CouponDetails/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/demo/coupons.js
This PR renames `redemptions.available` to `redemptions.total`
=> Rename available key to total

src/components/CodeAssignmentModal/index.jsx, src/components/CouponDetails/index.jsx
1. Fixes when assign/revoke/remind status alerts are shown.
2. Also, fixes validation error when bulk assigning without any selected codes.
=> Fix when assign/revoke/remind status alerts are shown

src/components/CodeReminderModal/index.jsx, src/components/CouponDetails/index.jsx, src/containers/CodeReminderModal/CodeReminderModal.test.jsx, src/containers/CodeReminderModal/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
This PR adds the capability to send reminders to all assignments associated with a coupon.
Related backend PR: https://github.com/edx/ecommerce/pull/2132
[ENT-1540](https://openedx.atlassian.net/browse/ENT-1540)
=> Remind all coupon assignments

src/containers/RequestCodesPage/index.jsx
The PR fixes requests page loading issue.
=> Fix request codes page

src/components/CodeAssignmentModal/index.jsx, src/components/CouponDetails/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/demo/coupons.js
[ENT-1597](https://openedx.atlassian.net/browse/ENT-1597)
=> exclude existing code assignments in remaining uses for unassigned filter

src/components/CouponDetails/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
From product notes on  [ENT-1627](https://openedx.atlassian.net/browse/ENT-1627): "Do not add in remind in this case, only revoke."
=> Hide remind button for codes with errors

src/data/actions/enterpriseList.test.js, src/data/actions/portalConfiguration.test.js, src/data/services/LmsApiService.js
This reverts commit db214a1c72b8f2fb6516fd6b5029eb219e664d1d.
=> Revert "Replace with_access_to calls with dashboard_list calls"

package-lock.json, package.json, src/data/actions/dashboardAnalytics.test.js, src/data/actions/enterpriseList.test.js, src/data/actions/portalConfiguration.test.js, src/index.jsx
The 4.0.0 version of frontend-auth resolves an issue where users would be prompted to login more frequently than necessary when reloading the app.
=> Upgrade frontend-auth to 4.0.0

package-lock.json, package.json, src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap, src/components/EnterpriseList/index.jsx, src/components/ErrorPage/ErrorPage.test.jsx, src/components/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap, src/components/ErrorPage/index.jsx, src/components/ForbiddenPage/ForbiddenPage.test.jsx, src/components/ForbiddenPage/__snapshots__/ForbiddenPage.test.jsx.snap, src/components/ForbiddenPage/index.jsx, src/data/apiClient.js
In this PR, instead of logging user out of the portal, we will show a 403 component whenever a 403 response is returned by the API.
[ENT-1753](https://openedx.atlassian.net/browse/ENT-1753)
=> Add a 403 component

src/components/EnterpriseList/EnterpriseList.test.jsx, src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap, src/components/EnterpriseList/index.jsx
This PR fixes a loading screen stuck issue on enterprise list page introduced due to https://github.com/edx/edx-portal/pull/205
=> Fix enterprise list loading screen

src/components/CodeAssignmentModal/emailTemplate.js, src/components/CodeReminderModal/emailTemplate.js, src/components/CodeRevokeModal/emailTemplate.js
[ENT-2373]
- Adjust wording within the code assignment, reminder, and revocation email templates
=> ENT-2373 | Improve enterprise code email template messages

src/components/CouponDetails/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
**Description:** Do not allow to assign codes from an unavailable coupon. To achieve this `Assign` button is disabled for single and bulk assignments. 
**Available Coupon:** `coupon start datetime < current datetime < coupon end datetime`
**JIRA:** [ENT-2467](https://openedx.atlassian.net/browse/ENT-2467)
=> For an unavailable coupon disable `Assign` button for single and bulk code assignment

src/components/CouponDetails/index.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
=> Disable Remind and Revoke actions for an unavailable coupon

public/index.html
Added lang attribute `lang="en"` in HTML to meet WCAG guidelines.
https://openedx.atlassian.net/browse/ENT-2488
=> Added lang attribute in html to meet WCAG guidelines

src/data/services/EcommerceApiService.js
added filter param in fetchCouponOrders
=> ENT-2445 | Ability to hide code batches from e-commerce and/or the Code Management Too

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx, src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap, src/components/EnterpriseList/index.jsx, src/components/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap, src/components/ErrorPage/index.jsx, src/components/ForbiddenPage/__snapshots__/ForbiddenPage.test.jsx.snap, src/components/ForbiddenPage/index.jsx, src/components/NotFoundPage/__snapshots__/NotFoundPage.test.jsx.snap, src/components/NotFoundPage/index.jsx, src/components/SupportPage/__snapshots__/SupportPage.test.jsx.snap, src/components/SupportPage/index.jsx, src/containers/EnterpriseApp/__snapshots__/EnterpriseApp.test.jsx.snap
added <main> elements for Accessibility
=> ENT-2487 | Admin portal needs a <main> element

package.json, src/jestGlobalSetup.js
added globalSetup in jest to fix test failing due to timezone differce
=> ENT-2514 | Flaky jest test for frontend-app-admin-portal

src/components/CodeManagement/index.jsx, src/components/CodeSearchResults/CodeSearchResults.test.jsx, src/components/CodeSearchResults/CodeSearchResultsTable.jsx, src/components/CodeSearchResults/__snapshots__/CodeSearchResults.test.jsx.snap, src/components/CodeSearchResults/index.jsx, src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap
**ENT 2263**: customers need to be able to search for codes in batches.
This pull request is an enhancement of search functionality in **Code Management Portal**. As requested in the ticket (**ENT-2263**), the enterprise admins can now make a search by code as well. The search results would help them figure out which voucher code belongs to which coupon batch and will also give them useful information about the assignment of the _searched_ voucher.
**STEPS TO TEST IT:**
- Open Code Management Portal
- Pick out any voucher from any of the coupons shown below
- Copy/Paste the code in the search bar at the top
- See results
=> ENT-2263 Added Search By Code Functionality

src/components/CodeManagement/index.jsx, src/components/ReportingConfig/index.jsx, src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap
Added main element in Regporting config and Code Management pages
=> ENT-2487 | add missing <main> elements 

src/components/Admin/Admin.test.jsx, src/components/Admin/index.jsx, src/components/CodeSearchResults/CodeSearchResults.test.jsx, src/components/CompletedLearnersTable/CompletedLearnersTable.test.jsx, src/components/Coupon/Coupon.test.jsx, src/components/EnrolledLearnersForInactiveCoursesTable/EnrolledLearnersForInactiveCoursesTable.test.jsx, src/components/EnrolledLearnersTable/EnrolledLearnersTable.test.jsx, src/components/EnrollmentsTable/EnrollmentsTable.test.jsx, src/components/LearnerActivityTable/LearnerActivityTable.test.jsx, src/components/LearnerActivityTable/index.jsx, src/components/PastWeekPassedLearnersTable/PastWeekPassedLearnersTable.test.jsx, src/components/PastWeekPassedLearnersTable/index.jsx, src/components/RegisteredLearnersTable/RegisteredLearnersTable.test.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/DownloadCsvButton/DownloadCsvButton.test.jsx, src/data/actions/table.js, src/data/actions/table.test.js, src/data/services/EnterpriseDataApiService.js
refactored enterpriseDataApiServices to make it independent of the `store`.
=> ENT-2547 | Refactor services method in Frontend App Admin Portal

src/components/CodeAssignmentModal/index.jsx, src/components/CodeReminderModal/index.jsx, src/components/CodeRevokeModal/emailTemplate.js, src/components/CodeRevokeModal/index.jsx
Fixes https://openedx.atlassian.net/browse/ENT-2707
=> ENT-2707 : Bug fixes

src/components/CouponDetails/index.jsx, src/components/EnterpriseList/index.jsx
fixed pagination issue due to params mismatch in `fetchMethod` that is being called in `paginatedTable` action
=> ENT-2704 | Pagination not working in Code Management Tool 

package-lock.json, package.json, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx, src/components/CodeManagement/index.jsx, src/components/CodeSearchResults/__snapshots__/CodeSearchResults.test.jsx.snap, src/components/EnrolledLearnersForInactiveCoursesTable/__snapshots__/EnrolledLearnersForInactiveCoursesTable.test.jsx.snap, src/components/EnterpriseList/EnterpriseList.test.jsx, src/components/EnterpriseList/__snapshots__/EnterpriseList.test.jsx.snap, src/components/EnterpriseList/index.jsx, src/components/LearnerActivityTable/__snapshots__/LearnerActivityTable.test.jsx.snap, src/components/PastWeekPassedLearnersTable/__snapshots__/PastWeekPassedLearnersTable.test.jsx.snap, src/components/SearchBar/SearchBar.test.jsx, src/components/SearchBar/__snapshots__/SearchBar.test.jsx.snap, src/components/subscriptions/SubscriptionManagementPage.jsx, src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
Ticket: https://openedx.atlassian.net/browse/ENT-2771
The SearchField component in Paragon was recently refactored to add support for additional customization and to fix the IE11/Edge bug.
This PR upgrades @edx/paragon to bring in the changes to the SearchField component. The majority of lines changed are in the snapshot tests due to the change in the underlying DOM structure of the SearchField component.
=> Upgrade Paragon for SearchField fix

src/components/SaveTemplateButton/index.jsx
[ENT-2587](https://openedx.atlassian.net/browse/ENT-2587)
=> use selected template name when update existing

src/components/subscriptions/SubscriptionManagementPage.jsx, src/config/index.js
**Jira Ticket:** [ENT-2837](https://openedx.atlassian.net/browse/ENT-2837)
As an administrator, I want to easily reach out to ECS if I have issues performing my duties so that I know where to go to get them quickly resolved.
=> ENT-2837: Add customer support email link on subscription management page.

src/components/CouponDetails/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/CouponDetails/__snapshots__/CouponDetails.test.jsx.snap
JIRA: https://openedx.atlassian.net/browse/ENT-2967
=> ENT-2967: Added assignment and reminder dates columns

src/components/CodeAssignmentModal/index.jsx, src/data/constants/coupons.js
**Description:** Update csv upload to handle csv files with and without csv header. If first row of csv is not a valid emails and equals to `emails` than it will be considered as header otherwise it will treated as an email address.
**JIRA:** [ENT-3064](https://openedx.atlassian.net/browse/ENT-3064)
=> update csv upload to handle csv files with and without csv header

src/components/subscriptions/SubscriptionManagementPage.jsx, src/components/subscriptions/hooks/licenseManagerHooks.js
**Description:** Upon successful license assign, update stats on subscription management page.
**JIRA:** https://openedx.atlassian.net/browse/ENT-2988
=> Refresh data on license assign

src/components/subscriptions/SubscriptionData.jsx, src/components/subscriptions/SubscriptionManagementPage.jsx, src/components/subscriptions/hooks/licenseManagerHooks.js
**Description:** Show subscriptions of the currently selected enterprise customer.
**JIRA:** [ENT-3164](https://openedx.atlassian.net/browse/ENT-3164)
=> show subscriptions for correct enterprise customer

src/components/subscriptions/SubscriptionData.jsx, src/components/subscriptions/SubscriptionManagementPage.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-2951
=> ENT-2951: Added alert for missing subscription

src/components/LicenseRemindModal/index.jsx, src/components/LicenseRevokeModal/index.jsx, src/components/subscriptions/LicenseActions.jsx, src/components/subscriptions/LicenseAllocationNavigation.jsx, src/components/subscriptions/RemindUsersButton.jsx, src/components/subscriptions/SubscriptionData.jsx, src/components/subscriptions/SubscriptionManagementPage.jsx, src/components/subscriptions/TabContentTable.jsx, src/components/subscriptions/constants.js, src/components/subscriptions/hooks/licenseManagerHooks.js
Make sure the Pagination of Subscriptions Page works correctly.
=> ENT-3149-Pagination support for subscription work

src/components/subscriptions/LicenseStatus.jsx, src/components/subscriptions/constants.js
=> Fix user statuses in licenses table

src/components/CouponDetails/index.jsx
Update PAGE URL param when moving between filters to prevent 404. 
JIRA: https://openedx.atlassian.net/browse/ENT-3082
=> ENT-3082: Update page URL param when moving between filters

package-lock.json, src/components/AddUsersModal/emailTemplate.js, src/components/LicenseRemindModal/emailTemplate.js
https://openedx.atlassian.net/browse/ENT-3223
=> ENT-3223 | Add LEARNER_PORTAL_LINK to assign/remind email templates.

config/webpack.prod.config.js
Changed support flag in `webpack.prod.config.js` to `true`
=> Enable support flag in prod config

src/components/CodeSearchResults/CodeSearchResults.test.jsx, src/containers/CodeAssignmentModal/CodeAssignmentModal.test.jsx, src/containers/CodeReminderModal/CodeReminderModal.test.jsx, src/containers/CodeRevokeModal/CodeRevokeModal.test.jsx, src/containers/SaveTemplateButton/SaveTemplateButton.test.jsx, src/utils.js
Make the subject field mandatory to avoid sending emails without subject.
=> ENT-3083: Make sure user enters email subject

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Header/index.jsx, src/components/NumberCard/__snapshots__/NumberCard.test.jsx.snap, src/components/NumberCard/index.jsx, src/components/Sidebar/index.jsx, src/containers/EnterpriseApp/__snapshots__/EnterpriseApp.test.jsx.snap, src/containers/Header/__snapshots__/Header.test.jsx.snap, src/containers/Sidebar/__snapshots__/Sidebar.test.jsx.snap
* Sidebar ul added
* Header levels amended
* aria-labels added to nav components
=> Fix accessibility issues on dashboard

src/components/AddUsersModal/index.jsx, src/components/CodeAssignmentModal/index.jsx, src/components/subscriptions/SubscriptionManagementPage.jsx, src/containers/AddUsersModal/AddUsersModal.test.jsx, src/containers/AddUsersModal/index.jsx, src/data/constants/addUsers.js, src/utils.js
* allow the submission of emails from text and csv. include invalid email addresses in the request to LM
https://openedx.atlassian.net/browse/ENT-3194
=> ENT-3194: refining the "Add User" email functionality

src/components/subscriptions/SubscriptionManagementPage.jsx
=> Switch to pending tab after license assignment

src/components/subscriptions/SubscriptionDetails.jsx
This field no longer exists on the Subscription model so don't display
anything
ENT-3409
=> Remove purchase date info

config/webpack.dev.config.js, config/webpack.prod.config.js, package-lock.json, package.json, src/components/EnterpriseApp/index.jsx, src/components/Sidebar/index.jsx, src/components/analytics/AnalyticsCharts.jsx, src/components/analytics/AnalyticsPage.jsx, src/components/analytics/data/service.js, src/components/analytics/index.js, src/config/index.js, src/containers/EnterpriseApp/EnterpriseApp.test.jsx, src/containers/EnterpriseApp/index.jsx, src/containers/Sidebar/Sidebar.test.jsx, src/containers/Sidebar/index.jsx, src/data/reducers/portalConfiguration.js, src/data/reducers/portalConfiguration.test.js
Description: This PR adds a navigation in the sidebar and pages for embedded tableau
JIRA: https://openedx.atlassian.net/browse/ENT-3125
=> ENT-3125 Added Analytics pages with embedded Tableau

.gitignore, config/webpack.dev.config.js, src/components/JwtAuthenticationRefresh/index.jsx, src/index.jsx
Fixes this the right way now: https://openedx.atlassian.net/browse/ENT-3464
Manual testing demo:
=> Attempt to refresh JWT when in an unauthenticated state (attempt 2).

src/components/CouponDetails/index.jsx
* Adds in informational alert for bulk assign when selecting both public & private codes
* Fixes success message when changing visibility of codes
* Changes Visibility column display name & value display
* Fixes swapping from Public/Private to Both from erroring out
=> Bug fixes for Visibility

src/components/subscriptions/TabContentTable.jsx, src/components/subscriptions/constants.js, src/components/subscriptions/data/service.js, src/components/subscriptions/hooks/licenseManagerHooks.js
https://openedx.atlassian.net/browse/ENT-3441
=> pass page_size option to licenses endpoint

config/webpack.prod.config.js, src/components/analytics/AnalyticsCharts.jsx
Description: This PR logs the tableau url for testing on stage. Change is temporary and PR will be reverted after the test.
=> ENT-3510 Log tableau url 

src/components/analytics/AnalyticsCharts.jsx
Description: This PR removes the logged tableau URL which was added in [PR](https://github.com/edx/frontend-app-admin-portal/pull/351) for testing purpose.
=> ENT-3510 Remove testing console statement

jsdom-with-global.js, package-lock.json, package.json, src/components/CodeReminderModal/index.jsx, src/components/CodeRevokeModal/index.jsx, src/components/CodeSearchResults/CodeSearchResults.test.jsx, src/components/SupportPage/SupportPage.test.jsx, src/containers/AddUsersModal/AddUsersModal.test.jsx, src/containers/AdminRegisterPage/AdminRegisterPage.test.jsx, src/containers/CouponDetails/CouponDetails.test.jsx, src/containers/EnterpriseApp/EnterpriseApp.test.jsx, src/containers/LicenseRemindModal/LicenseRemindModal.test.jsx, src/setupTest.js
This PR is a first pass at removing console errors on tests, with the goal of eventually making a console error fail the test. 
This will both allow us to have more signal and less noise when looking at test results, and catch more errors when they occur, as React console errors are often indicative of actual problems and/or performance issues.
=> Clean up console errors on tests

src/components/CodeRevokeModal/index.jsx, src/components/SaveTemplateButton/index.jsx, src/components/TemplateSourceFields/index.jsx, src/containers/CodeRevokeModal/CodeRevokeModal.test.jsx, src/containers/CodeRevokeModal/index.jsx
JIRA Ticket: [ENT-3657](https://openedx.atlassian.net/browse/ENT-3657)
"As an admin, I want the ability to revoke my learner's code, without having to email them, to make the revoke a softer experience."
A/C:
1. Be able to revoke codes without having to email learners and notify them.
=> ENT-3657: Ability to Revoke Code, but Not Email

config/webpack.dev.config.js, config/webpack.prod.config.js, src/components/EnterpriseApp/index.jsx, src/components/LmsConfigurations/MoodleIntegrationConfigForm.jsx, src/components/LmsConfigurations/MoodleIntegrationConfigForm.test.jsx, src/components/LmsConfigurations/index.jsx, src/components/LmsConfigurations/index.test.jsx, src/components/ReportingConfig/ReportingConfigForm.jsx, src/components/SamlProviderConfiguration/SamlProviderConfigForm.jsx, src/components/SamlProviderConfiguration/SamlProviderDataForm.jsx, src/components/SaveTemplateButton/index.jsx, src/components/Sidebar/index.jsx, src/config/index.js, src/containers/LmsConfigurations/index.jsx, src/containers/Sidebar/index.jsx, src/data/constants/formSubmissions.js, src/data/reducers/portalConfiguration.js, src/data/reducers/portalConfiguration.test.js, src/data/services/LmsApiService.js
adds new sidebar element for LMS configurations.
=> External LMS Configuration screen

src/components/Admin/AdminSearchForm.jsx, src/components/Admin/__snapshots__/Admin.test.jsx.snap
Small CSS fix:  On mobile view, filters on the admin portal learner table should be in a single column.
=> ENT-3772 mobile css filter col fix

src/components/LmsConfigurations/BlackboardIntegrationConfigForm.jsx, src/components/LmsConfigurations/BlackboardIntegrationConfigForm.test.jsx, src/components/LmsConfigurations/index.jsx, src/components/LmsConfigurations/index.test.jsx, src/data/services/LmsApiService.js
Modeled after existing Moodle and Canvas work.
=> Adding frontend configuration for blackboard

src/components/InviteLearnersModal/emailTemplate.js, src/components/InviteLearnersModal/index.jsx, src/components/LicenseRemindModal/emailTemplate.js, src/components/LicenseRemindModal/index.jsx, src/containers/InviteLearnersModal/InviteLearnersModal.test.jsx, src/containers/InviteLearnersModal/index.jsx, src/containers/LicenseRemindModal/LicenseRemindModal.test.jsx, src/containers/LicenseRemindModal/index.jsx, src/data/reducers/portalConfiguration.js, src/data/reducers/portalConfiguration.test.js, src/utils.js
=> feat: update assingment and reminder emails

src/components/LmsConfigurations/SuccessFactorsIntegrationConfigForm.jsx, src/components/LmsConfigurations/SuccessFactorsIntegrationConfigForm.test.jsx, src/components/LmsConfigurations/index.jsx, src/components/LmsConfigurations/index.test.jsx, src/data/services/LmsApiService.js
TODO:
- Tests
- Verify functionality (update in particular)
- Add a feature gate (maybe?)
=> Add Success Factor to LMS Configurations

src/components/LmsConfigurations/CornerstoneIntegrationConfigForm.jsx, src/components/LmsConfigurations/CornerstoneIntegrationConfigForm.test.jsx, src/components/LmsConfigurations/index.jsx, src/components/LmsConfigurations/index.test.jsx, src/data/services/LmsApiService.js
Adds Cornerstone to the LMS config forms.
I also fixed a state warning (something about "uncontrolled input") that was happening with Degreed.
Also made tests more consistent with what they were supposed to be doing (ie they previously only passed due to order of operations)
=> Cornerstone Config Form

config/webpack.dev.config.js, package-lock.json, package.json, src/components/BulkEnrollmentPage/CourseSearchResults.jsx, src/components/BulkEnrollmentPage/CourseSearchResults.test.jsx
Adds a table to display the course data.
=> Add basic table

src/components/AdminRegisterPage/AdminRegisterPage.test.jsx, src/components/AdminRegisterPage/index.jsx, src/components/subscriptions/MultipleSubscriptionsPage.jsx
=> Fix routing after admin-platform merge

src/components/AdminRegisterPage/AdminRegisterPage.test.jsx, src/components/AdminRegisterPage/index.jsx, src/components/subscriptions/MultipleSubscriptionsPage.jsx
Reverts edx/frontend-app-admin-portal#452
=> Revert "Fix routing after admin-platform merge"

src/index.jsx
This conditional got lost in a rebase on `master` branch before merging; adding it back in now.
=> forgot to add conditional around showing maintenance alert

package-lock.json, package.json, src/index.jsx, webpack.prod.config.js
Use the prod config for prod
Add back code-js so that things still work in ie11
**To test on stage before pushing to prod**
**Test on prod immediately after deploy**
=> Fixes to frontend-build update

package-lock.json, package.json
=> Update paragon version

src/components/CodeAssignmentModal/emailTemplate.js, src/components/CodeReminderModal/emailTemplate.js
Updates wording on code emails.
=> Change default email text for codes emails

package-lock.json, package.json, src/index.scss
Changes the way we import scss
=> Update frontend-enterprise version

src/components/CodeAssignmentModal/emailTemplate.js, src/components/CodeReminderModal/emailTemplate.js
ENT-3671: Keep email field populated while switching in between new and old templates
=> ENT-3928 Change body “expiration date” to “code expiration date”.

src/components/analytics/AnalyticsCharts.jsx
Description: This PR adds 50px to the embedded tableau visualisation dimensions.
=> ENT-4330: Updated Embedded Tableau Viz dimensions

src/components/analytics/AnalyticsCharts.jsx
Description: This PR removes the toolbar from the tableau visualisation.
JIRA: https://openedx.atlassian.net/browse/ENT-4329
=> ENT-4329: Removed Tableau toolbar

src/components/CodeAssignmentModal/index.jsx, src/components/CodeReminderModal/index.jsx, src/containers/CodeReminderModal/CodeReminderModal.test.jsx, src/containers/CodeReminderModal/index.jsx, src/containers/CouponDetails/CouponDetails.test.jsx
Also fixes an error in how assignment emails were getting information from the Redux store.
=> Add base_enterprise_url to reminder emails

src/components/CodeAssignmentModal/BulkAssignFields.jsx, src/components/RenderField/index.jsx, src/components/RequestCodesPage/RequestCodesForm.jsx, src/components/TextAreaAutoSize/index.jsx
=> Add description test id to TextAreaAutoSize

src/components/analytics/AnalyticsCharts.jsx, src/components/analytics/data/service.js
**Description:** Send uuid of the enterprise a logged in user is visiting.
=> feat: send enterprise uuid as query param for tableau

src/components/ReportingConfig/ReportingConfigForm.jsx
Reverts edx/frontend-app-admin-portal#558
=> Revert "Revert "ENT-4481: Admin Portal: Fix reporting config password field error""

src/components/ReportingConfig/ReportingConfigForm.jsx
**Jira Ticket:** [ENT-4481](https://openedx.atlassian.net/browse/ENT-4481)
Description:
Found another issue with the email field while testing changes made in https://github.com/edx/frontend-app-admin-portal/pull/557 This PR fixes that.
__Testing Instructions:__
1. Go to the reporting configuration page of some enterprise customer at /<enterprise-customer>/admin/reporting
2. Add/update reporting configuration
3. Select the Change Password checkbox
4. Try to update the password
5. Password should update without any error.
6. Also try updating the email address by selection "Email" in "Delivery Method"
7. Email should be updated/added without any error.
=> ENT-4481: fix: Fixed error raised for email validation while adding reporting configuration.

src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.jsx
=> feat: Change copy text for notify learners checkbox per ux feedback

src/components/LicenseRevokeModal/index.jsx, src/components/subscriptions/licenses/LicenseActions.jsx, src/components/subscriptions/licenses/LicenseManagementTabContentTable.jsx
Related PR: https://github.com/edx/license-manager/pull/221
=> fix: disable revocation cap as required

src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.jsx, src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.test.jsx
based on no. of emails passed
ENT-4681
=> feat: Success toast message with correct grammar

package-lock.json, package.json
Pulls in the changes noted here: https://github.com/edx/frontend-build/pull/179
=> build: upgrade frontend-build to 6.1.0

src/components/BulkEnrollmentPage/stepper/AddCoursesStep.jsx, src/components/BulkEnrollmentPage/stepper/AddLearnersStep.jsx, src/components/BulkEnrollmentPage/stepper/ReviewStep.jsx, src/components/BulkEnrollmentPage/stepper/constants.jsx
[Jira](https://openedx.atlassian.net/browse/ENT-4687)
screenshots:
**before**
step 1
step 2
step 3
**after**
step 1
step 2
step 3
=> maint: adjusting language on bulk enrollment steps descriptions

src/components/BulkEnrollmentPage/stepper/BulkEnrollmentSubmit.jsx, src/components/BulkEnrollmentPage/stepper/constants.jsx
[jira](https://openedx.atlassian.net/browse/ENT-4683)
Note: logic to handle partial vs total failures to come in a fast follow.
=> maint: fixing wording on BE error modal

src/components/BulkEnrollmentPage/CourseSearchResults.test.jsx, src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.test.jsx, src/components/BulkEnrollmentPage/table/BaseSelectionStatus.jsx, src/components/BulkEnrollmentPage/table/BaseSelectionStatus.test.jsx
Will post screenshot but my local devstack is hosed, again
May have to reboot and/or start over
ENT-4684
=> feat: Remove the word 'All' from filter status to avoid confusion ENT-4684

src/components/BulkEnrollmentPage/BulkEnrollment.scss, src/components/BulkEnrollmentPage/CourseSearchResults.jsx, src/components/BulkEnrollmentPage/stepper/AddLearnersStep.jsx
[jira](https://openedx.atlassian.net/browse/ENT-4714)
**Before:**
**After:**
=> maint: making selector column spacing match between BE steps

src/components/ErrorPage/__snapshots__/ErrorPage.test.jsx.snap, src/components/ErrorPage/index.jsx, src/components/InviteLearnersModal/index.jsx, src/components/LicenseRemindModal/index.jsx, src/components/LicenseRevokeModal/index.jsx, src/components/subscriptions/SubscriptionData.jsx, src/components/subscriptions/SubscriptionDetailPage.jsx, src/components/subscriptions/SubscriptionDetails.jsx, src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx, src/components/subscriptions/tests/expiration/SubscriptionExpirationBanner.test.jsx
Closes ENT-4629
Replaces `StatusAlert` component with paragon `Alert`
=> ENT 4629 - Alerts

src/components/FeatureAnnouncementBanner/FeatureAnnouncementBanner.test.jsx, src/components/FeatureAnnouncementBanner/index.jsx
Jira Ticket:
https://openedx.atlassian.net/browse/ENT-4740
Backend PR:
https://github.com/edx/edx-enterprise/pull/1318
Made notification title customizable.
=> ENT4740 Added title for Admin Notification

package-lock.json, package.json, src/components/BulkEnrollmentPage/BulkEnrollment.scss, src/components/BulkEnrollmentPage/stepper/AddCoursesStep.jsx, src/components/BulkEnrollmentPage/stepper/BulkEnrollmentStepper.jsx
Why? To improve the scrollable area UX and make it more apparent the contents are scrollable. Also the shadows look cool!
ENT-4695
DEPENDS ON: https://github.com/edx/paragon/pull/779 ✅ 
ALSO SUBJECT TO: Review from Jen G ✅ 
FIXED! ☑️  Looks like I may need additional margin for the search header 💹 
Tests: The `Scrollable` component will already be tested in Paragon, there is nothing to be done on this side here that adds value.
CURRENT: check sth like https://portal.stage.edx.org/binod-subs/admin/enrollment/a4db1210-93fa-4ffc-af5d-62110484157a
AFTER:
https://user-images.githubusercontent.com/528166/129810541-660d4c96-a6ab-4551-b8b8-4f303aa1131e.mov
=> feat: Add Scrollable component around stepper contents. ENT-4695

src/components/CodeAssignmentModal/index.jsx, src/components/CodeReminderModal/CodeReminderModal.test.jsx, src/components/CodeReminderModal/emailTemplate.js, src/components/CodeReminderModal/index.jsx, src/components/CodeRevokeModal/CodeRevokeModal.test.jsx, src/components/CodeRevokeModal/emailTemplate.js, src/components/CodeRevokeModal/index.jsx, src/containers/CodeReminderModal/CodeReminderModal.test.jsx, src/containers/CodeRevokeModal/CodeRevokeModal.test.jsx, src/data/reducers/emailTemplate.js
=> add file upload link for remind and revoke

src/components/ReportingConfig/ReportingConfigForm.jsx, src/components/ReportingConfig/ReportingConfigForm.test.jsx, src/components/ReportingConfig/index.jsx, src/data/services/LmsApiService.js
Description: This PR adds support for fetching the reporting config dropdown choices from an api
JIRA: https://openedx.atlassian.net/browse/ENT-4482
=> feat: Reporting config getting dropdown values from an API

package-lock.json, package.json, src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx, src/components/subscriptions/expiration/SubscriptionExpirationModals.jsx, src/components/subscriptions/tests/TestUtilities.jsx, src/components/subscriptions/tests/expiration/SubscriptionExpirationBanner.test.jsx, src/components/subscriptions/tests/expiration/SubscriptionExpirationModals.test.jsx
https://openedx.atlassian.net/browse/ENT-4818
=> feat: use new sendEnterpriseTrackEvent from frontend-enterprise-utils

package-lock.json, package.json, src/components/BulkEnrollmentPage/index.jsx, src/components/BulkEnrollmentPage/index.test.jsx, src/components/subscriptions/MultipleSubscriptionPicker.jsx, src/components/subscriptions/MultipleSubscriptionsPage.jsx, src/components/subscriptions/SubscriptionCard.jsx, src/components/subscriptions/SubscriptionManagementPage.jsx, src/components/subscriptions/data/constants.js, src/components/subscriptions/data/utils.js, src/components/subscriptions/styles/_SubscriptionManagementPage.scss, src/components/subscriptions/tests/MultipleSubscriptionsPage.test.jsx, src/components/subscriptions/tests/MultipleSubscriptionsPicker.test.jsx, src/components/subscriptions/tests/SubscriptionCard.test.jsx, src/components/subscriptions/tests/SubscriptionManagementPage.test.jsx, src/components/subscriptions/tests/data/utils.test.js, src/index.scss
=> feat: implement subscription page using paragon components

README.md, package-lock.json, package.json, src/components/Admin/Admin.test.jsx, src/components/BulkEnrollmentPage/stepper/DismissibleCourseWarning.jsx, src/components/DownloadCsvButton/index.jsx, src/components/TableComponent/index.jsx, src/containers/DownloadCsvButton/index.jsx, src/containers/TableContainer/index.jsx, src/setupTest.js
=> fix: re-add segment events for legacy table pagination/sort and csv download

src/components/BulkEnrollmentPage/BulkEnrollment.scss, src/components/BulkEnrollmentPage/CourseSearchResults.test.jsx, src/components/BulkEnrollmentPage/table/CourseSearchResultsCells.jsx, src/components/BulkEnrollmentPage/table/CourseSearchResultsCells.test.jsx
=> feat: add popover to course search title

src/components/subscriptions/data/contextHooks.jsx, src/components/subscriptions/licenses/LicenseManagementTable/LicenseManagementTableActionColumn.jsx, src/components/subscriptions/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/licenses/LicenseManagementTable/tests/index.test.jsx
**Expired (without selection)**
**Non-Expired (with selection)**
=> fix: hide table selection if subscription is expired

README.md, package-lock.json, package.json, src/components/subscriptions/licenses/LicenseManagementTable/LicenseManagementTableBulkActions.jsx
=> fix: Making bulk revoke action modal color filled in/ opaque

src/components/MultipleFileInputField/MultipleFileInputField.jsx, src/components/MultipleFileInputField/MultipleFileInputField.test.jsx
=> fix: change file reading from readAsText to readAsArrayBuffer

src/components/EmailTemplateForm/index.jsx, src/components/MultipleFileInputField/MultipleFileInputField.jsx, src/components/MultipleFileInputField/MultipleFileInputField.test.jsx, src/components/MultipleFileInputField/constants.js
=> fix: change max files size limit from 2mb to 250kb

src/components/ReportingConfig/ReportingConfigForm.jsx, src/components/ReportingConfig/ReportingConfigForm.test.jsx, src/components/ReportingConfig/index.jsx, src/components/ReportingConfig/index.test.jsx
=> fix: reporting config page create and delete bugs

public/index.html
=> fix: ENT-4554 Removed async for tableau api load

public/index.html
This reverts commit 3c09acc6c45fbf1e65d4577334e0885d3ec80a6a.
=> Revert "fix: ENT-4554 Removed async for tableau api load (#665)"

package-lock.json, package.json, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/CouponDetails/index.test.jsx, src/components/EnterpriseList/EnterpriseList.test.jsx, src/components/SearchBar/SearchBar.test.jsx, src/components/SearchBar/__snapshots__/SearchBar.test.jsx.snap, src/components/subscriptions/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/licenses/LicenseManagementTable/tests/index.test.jsx, src/containers/CodeManagementPage/__snapshots__/CodeManagementPage.test.jsx.snap, src/data/actions/dashboardAnalytics.js
=> chore: upgrade paragon to v17.3.2

src/components/EnterpriseList/EnterpriseList.test.jsx, src/components/EnterpriseList/index.jsx, src/data/services/LmsApiService.js
https://user-images.githubusercontent.com/49611774/152549289-8d837b52-ef9c-4cd2-b1e4-b0a7cbfab5ea.mov
=> fix: rectify bug of parsing undefined in query string

src/components/EnterpriseList/index.jsx
**Before**
https://user-images.githubusercontent.com/49611774/152979605-ae18e096-efaf-48cf-aaf1-0b9c8bc7fc29.mov
**After**
https://user-images.githubusercontent.com/49611774/152979665-6af5e9b5-6994-47d8-91e2-21711cf16efe.mov
=> fix: rectify 'search=undefined' in calls and null query passed to searchField

src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx, src/components/settings/data/constants.js, src/utils.js
=> feat: adding lms config validation

src/components/settings/SettingsLMSTab/ConfigError.jsx, src/components/settings/SettingsLMSTab/LMSConfigPage.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx, src/components/settings/SettingsLMSTab/tests/ConfigError.test.jsx, src/components/settings/data/constants.js, src/utils.js
=> Updates to error handling

src/components/settings/SettingsLMSTab/ConfigModal.jsx, src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx, src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx
=> feat: adding save draft functionality

src/components/subsidy-request-management-alerts/NoAvailableCodesBanner.jsx, src/components/subsidy-request-management-alerts/NoAvailableLicensesBanner.jsx, src/components/subsidy-request-management-alerts/index.jsx, src/components/subsidy-request-management-alerts/tests/NoAvailableCodesBanner.test.jsx, src/components/subsidy-request-management-alerts/tests/NoAvailableLicensesBanner.test.jsx
https://openedx.atlassian.net/browse/ENT-5216
=> feat: add subsidy request management alerts

src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx, src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx
=> feat: add incomplete card hover

src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx, src/components/settings/data/constants.js, src/data/hooks.js, src/data/services/LmsApiService.js
=> feat: adding oauth authorization step to lms configs

src/components/CodeManagement/CodeManagementRoutes.jsx, src/components/CodeManagement/tests/CodeManagementRoutes.test.jsx, src/components/CodeManagement/tests/CouponCodeTabs.test.jsx, src/components/CodeManagement/tests/ManageRequestsTab.test.jsx, src/components/subscriptions/SubscriptionRoutes.jsx, src/components/subscriptions/SubscriptionTabs.jsx, src/components/subscriptions/tests/SubscriptionRoutes.test.jsx, src/components/subscriptions/tests/SubscriptionSubsidyRequests.test.jsx, src/components/subscriptions/tests/SubscriptionTabs.test.jsx, src/components/subscriptions/tests/data/hooks.test.jsx, src/data/services/EnterpriseAccessApiService.js
=> Tests for ENT-5226

src/components/CodeManagement/ManageRequestsTab.jsx, src/components/CodeManagement/tests/ManageRequestsTab.test.jsx, src/components/SubsidyRequestManagementTable/ActionCell.jsx, src/components/SubsidyRequestManagementTable/SubsidyRequestManagementTable.jsx, src/components/SubsidyRequestManagementTable/data/actions.js, src/components/SubsidyRequestManagementTable/data/constants.js, src/components/SubsidyRequestManagementTable/data/hooks.js, src/components/SubsidyRequestManagementTable/data/reducer.js, src/components/SubsidyRequestManagementTable/data/tests/actions.test.js, src/components/SubsidyRequestManagementTable/data/tests/hooks.test.js, src/components/SubsidyRequestManagementTable/data/tests/reducer.test.js, src/components/SubsidyRequestManagementTable/data/utils.js, src/components/SubsidyRequestManagementTable/index.js, src/components/SubsidyRequestManagementTable/tests/ActionCell.test.jsx, src/components/subscriptions/SubscriptionSubsidyRequests.jsx, src/components/subscriptions/tests/SubscriptionSubsidyRequests.test.jsx, src/components/subsidy-request-modals/ApproveCouponCodeRequestModal.jsx, src/components/subsidy-request-modals/ApproveLicenseRequestModal.jsx, src/components/subsidy-request-modals/DeclineSubsidyRequestModal.jsx, src/components/subsidy-request-modals/data/hooks.js, src/components/subsidy-request-modals/tests/ApproveCouponCodeRequestModal.test.jsx, src/components/subsidy-request-modals/tests/ApproveLicenseRequestModal.test.jsx, src/components/subsidy-request-modals/tests/DeclineSubsidyRequestModal.test.jsx, src/components/subsidy-request-modals/tests/hooks.test.jsx, src/data/services/EnterpriseAccessApiService.js, src/data/services/EnterpriseCatalogApiService.js, src/data/services/tests/EnterpriseAccessApiService.test.js
https://openedx.atlassian.net/browse/ENT-5533
=> feat: integrate subsidy request modals

src/components/CodeManagement/ManageRequestsTab.jsx, src/components/CodeManagement/tests/ManageRequestsTab.test.jsx, src/components/EnterpriseApp/index.jsx, src/components/SubsidyRequestManagementTable/data/constants.js, src/components/SubsidyRequestManagementTable/data/hooks.js, src/components/SubsidyRequestManagementTable/data/tests/actions.test.js, src/components/SubsidyRequestManagementTable/data/tests/hooks.test.js, src/components/SubsidyRequestManagementTable/data/tests/reducer.test.js, src/components/SubsidyRequestManagementTable/index.js, src/components/subscriptions/SubscriptionSubsidyRequests.jsx, src/components/subscriptions/tests/SubscriptionSubsidyRequests.test.jsx, src/components/subsidy-request-configuration/SubsidyRequestConfigurationContextProvider.jsx, src/components/subsidy-request-configuration/data/hooks.js, src/components/subsidy-request-configuration/data/tests/hooks.test.js, src/components/subsidy-request-configuration/index.js, src/components/subsidy-request-configuration/tests/SubsidyRequestConfigurationContextProvider.test.jsx, src/containers/EnterpriseApp/EnterpriseApp.test.jsx, src/containers/EnterpriseApp/index.jsx, src/data/constants/subsidyRequests.js, src/data/services/EnterpriseAccessApiService.js, src/data/services/tests/EnterpriseAccessApiService.test.js
https://openedx.atlassian.net/browse/ENT-5580
=> feat: create customer subsidy request configuration

package-lock.json, package.json, src/components/CodeManagement/CouponCodeTabs.jsx, src/components/CodeManagement/tests/CouponCodeTabs.test.jsx, src/components/subscriptions/SubscriptionRoutes.jsx, src/components/subscriptions/SubscriptionTabs.jsx, src/components/subscriptions/tests/SubscriptionTabs.test.jsx
**Note:** vice versa for coupons.
=> fix: ENT-5559

src/components/LoadingMessage/_LoadingMessage.scss, src/components/ProductTours/BrowseAndRequestTour.jsx, src/components/ProductTours/tests/BrowseAndRequestTour.test.jsx, src/components/settings/SettingsAccessTab/SettingsAccessGenerateLinkButton.jsx, src/components/settings/SettingsAccessTab/SettingsAccessLinkManagement.jsx, src/components/settings/SettingsAccessTab/SettingsAccessSubsidyRequestManagement.jsx, src/components/settings/SettingsAccessTab/index.jsx, src/components/settings/SettingsAccessTab/tests/SettingsAccessGenerateLinkButton.test.jsx, src/components/settings/SettingsAccessTab/tests/SettingsAccessLinkManagement.test.jsx, src/components/settings/SettingsAccessTab/tests/SettingsAccessTab.test.jsx, src/components/settings/SettingsAccessTab/tests/TestUtils.jsx, src/components/settings/SettingsContext.jsx, src/components/settings/tests/SettingsContext.test.jsx, src/components/settings/tests/SettingsPage.test.jsx, src/components/subsidy-request-modals/DeclineSubsidyRequestModal.jsx, src/components/subsidy-request-modals/tests/DeclineSubsidyRequestModal.test.jsx
=> fix: use latest subsidy expiration date for universal links, misc fixes

src/components/settings/data/tests/hooks.test.js
- fix test that CI didn't catch failing yesterday
- gotta await waitFor or else the assertion never runs like in this test
=> test: fix broken test

src/components/Sidebar/index.jsx
=> feat: properly hide settings tab in side bar

package-lock.json, package.json
=> fix: update frontend-build to 9.1.4

src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx, src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx
=> chore: fixing popover text and draft save bug

src/algoliaUtils/index.js
=> fix: Stop returning undefined query parameter values.

public/index.html
https://openedx.atlassian.net/browse/ENT-5715
[Local testing notes](https://openedx.atlassian.net/browse/ENT-5715?focusedCommentId=610516)
=> feat: add optimizely token

src/components/Sidebar/index.jsx
pass the id so product tour for bnr works again.
=> fix: pass id to icon links in sidebar

src/components/subscriptions/data/hooks.js
=> fix: moar eslint stuff

src/components/analytics/AnalyticsCharts.jsx
=> fix: revert back to original AnalyticsCharts and ignore eslint error

src/components/CodeManagement/CodeManagementRoutes.jsx, src/components/CodeManagement/CouponCodeTabs.jsx, src/components/CodeManagement/tests/CodeManagementRoutes.test.jsx, src/components/EnterpriseApp/EnterpriseApp.test.jsx, src/components/EnterpriseApp/index.jsx, src/components/NewFeatureAlertBrowseAndRequest/NewFeatureAlertBrowseAndRequest.test.jsx, src/components/NewFeatureAlertBrowseAndRequest/index.jsx, src/components/ProductTours/BrowseAndRequestTour.jsx, src/components/ProductTours/tests/BrowseAndRequestTour.test.jsx, src/components/settings/SettingsAccessTab/index.jsx, src/components/settings/SettingsAccessTab/tests/SettingsAccessTab.test.jsx, src/components/settings/SettingsTabs.jsx, src/components/settings/tests/SettingsContext.test.jsx, src/components/settings/tests/SettingsTabs.test.jsx, src/components/subscriptions/SubscriptionDetailPage.jsx, src/components/subscriptions/SubscriptionDetails.jsx, src/components/subscriptions/SubscriptionPlanRoutes.jsx, src/components/subscriptions/SubscriptionRoutes.jsx, src/components/subscriptions/tests/SubscriptionRoutes.test.jsx, src/components/subscriptions/tests/TestUtilities.jsx, src/components/subsidy-requests/SubsidyRequestsContextProvider.jsx, src/components/subsidy-requests/tests/SubsidyRequestsContextProvider.test.jsx, src/containers/EnterpriseApp/index.jsx, src/data/reducers/portalConfiguration.js, src/data/reducers/portalConfiguration.test.js
https://2u-internal.atlassian.net/browse/ENT-5807
=> feat: remove check for customer enableBrowseAndRequest

src/components/settings/SettingsLMSTab/LMSConfigPage.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx, src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/LmsConfigPage.test.jsx, src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx, src/components/settings/data/constants.js
[ENT-5574](https://2u-internal.atlassian.net/browse/ENT-5574)
Now has a loading skeleton instead of allowing user selection 
https://user-images.githubusercontent.com/31229189/168114529-235e84af-8236-41e7-b349-9277ef16bc5b.mov
[ENT-5576](https://2u-internal.atlassian.net/browse/ENT-5576)
Removed the ability to create duplicate display names, now shows validation error.
=> ENT 5574/5576 - SSO Bug Fixes 

src/components/settings/SettingsSSOTab/ExistingSSOConfigs.jsx, src/components/settings/SettingsSSOTab/SSOConfigContext.jsx, src/components/settings/SettingsSSOTab/SSOStepper.jsx, src/components/settings/SettingsSSOTab/data/actions.js, src/components/settings/SettingsSSOTab/data/reducer.js, src/components/settings/SettingsSSOTab/hooks.js, src/components/settings/SettingsSSOTab/index.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.test.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigServiceProviderStep.jsx, src/components/settings/SettingsSSOTab/tests/ExistingSSOConfigs.test.jsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
=> Asheehan edx/ent 5499 sso save draft

package-lock.json, package.json, src/components/settings/SettingsAccessTab/SettingsAccessLinkManagement.jsx, src/components/settings/SettingsAccessTab/SettingsAccessTabSection.jsx, src/components/settings/SettingsAccessTab/index.jsx
Remove box shown below. Move toggle to same level as header.
=> fix: remove unnecessary box in settings access tab section

src/components/settings/SettingsLMSTab/LMSConfigs/BlackboardConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CanvasConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/CornerstoneConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/Degreed2Config.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/DegreedConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/MoodleConfig.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAPConfig.jsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/Degreed2Config.test.jsx, src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx, src/components/settings/SettingsLMSTab/utils.js
=> fix: add authorize redirect

.github/workflows/ci.yml
Pin Npm to 8.5.x to resolve Peer Dependency issues
=> Pin Npm to 8.5.x to resolve Peer Dependency issues

package-lock.json, package.json, src/components/Admin/Admin.test.jsx, src/components/Admin/index.jsx, src/components/EnterpriseApp/index.jsx, src/components/EnterpriseSubsidiesContext/hooks/hooks.js, src/components/LearnerActivityTable/index.jsx, src/components/PastWeekPassedLearnersTable/index.jsx, src/components/learner-credit-management/EmailAddressTableCell.jsx, src/components/learner-credit-management/LearnerCreditAggregateCards.jsx, src/components/learner-credit-management/LearnerCreditAllocationTable.jsx, src/components/learner-credit-management/LearnerCreditManagement.jsx, src/components/learner-credit-management/OfferDates.jsx, src/components/learner-credit-management/OfferNameHeading.jsx, src/components/learner-credit-management/TableTextFilter.jsx, src/components/learner-credit-management/data/constants.js, src/components/learner-credit-management/data/hooks.js, src/components/learner-credit-management/data/tests/hooks.test.js, src/components/learner-credit-management/data/utils.js, src/components/learner-credit-management/tests/EmailAddressTableCell.test.jsx, src/components/learner-credit-management/tests/LearnerCreditAggregateCards.test.jsx, src/components/learner-credit-management/tests/LearnerCreditManagement.test.jsx, src/components/learner-credit-management/tests/OfferDates.test.jsx, src/components/learner-credit-management/tests/OfferNameHeading.test.jsx, src/components/learner-credit-management/tests/TableTextFilter.test.jsx, src/containers/EnterpriseApp/index.jsx, src/data/services/EnterpriseDataApiService.js, src/setupTest.js
=> feat: learner credit mgmt offer metadata display

src/components/settings/SettingsSSOTab/hooks.js
special handling for API errors relating to unique key validation errors when creating provider configs
=> fix: accounting for unique entity ID errors

src/components/learner-credit-management/LearnerCreditManagement.jsx, src/components/learner-credit-management/data/hooks.js, src/components/learner-credit-management/data/tests/hooks.test.js, src/components/learner-credit-management/data/utils.js, src/components/learner-credit-management/tests/LearnerCreditManagement.test.jsx, src/data/services/EnterpriseDataApiService.js
Integrate offers api and remove mocked data. Renamed utilization -> summary to more accurately represent the data.
=> feat: integrate offers api from analytics

src/components/settings/SettingsSSOTab/NewSSOConfigForm.jsx, src/components/settings/SettingsSSOTab/SSOConfigConfiguredCard.jsx, src/components/settings/SettingsSSOTab/hooks.js
=> fix: tweaking error responses to read better

src/index.jsx
Add `?feature=LEARNER_CREDIT_MANAGEMENT` to end of URL to enable the Learner Credit Management page.
=> fix: add ability to enable FEATURE_LEARNER_CREDIT_MANAGEMENT via query param

src/components/settings/SettingsTabs.jsx, src/components/settings/tests/SettingsTabs.test.jsx
=> chore: cleaning up SSO and LMS settings page feature flags

src/components/App/index.jsx, src/components/settings/SettingsAccessTab/data/utils.js
=> fix: pass bool to hotjarDebug

src/components/learner-credit-management/data/hooks.js, src/components/learner-credit-management/data/tests/hooks.test.js
=> feat: ignore null course price in learner credit mgmt table

src/containers/EnterpriseApp/index.jsx
=> fix: rename value comning from redux store for reporting config

src/components/learner-credit-management/data/tests/hooks.test.js, src/components/learner-credit-management/data/tests/utils.test.js, src/components/learner-credit-management/data/utils.js
=> fix: guard against bad offer summary data

src/components/EnterpriseApp/EnterpriseAppContextProvider.jsx, src/components/EnterpriseApp/index.jsx, src/components/EnterpriseSubsidiesContext/hooks/hooks.js, src/components/EnterpriseSubsidiesContext/hooks/tests/hooks.test.js, src/components/EnterpriseSubsidiesContext/index.jsx, src/containers/EnterpriseApp/index.jsx, src/data/reducers/portalConfiguration.js, src/data/reducers/portalConfiguration.test.js, src/data/services/EcommerceApiService.js
=> feat: adhere to enable_learner_portal_offers customer config flag

src/components/learner-credit-management/OfferUtilizationAlerts.jsx, src/components/learner-credit-management/data/tests/utils.test.js, src/components/learner-credit-management/data/utils.js, src/components/learner-credit-management/tests/OfferUtilizationAlerts.test.jsx
=> fix: handle when max discount is not available in offer summary metrics

src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx, src/components/settings/SettingsSSOTab/NewSSOConfigForm.jsx, src/components/settings/SettingsSSOTab/SSOConfigConfiguredCard.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigIDPStep.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigServiceProviderStep.jsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx, src/components/settings/SettingsSSOTab/tests/SSOConfigCard.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6011
sso steps wording refactor
alphabetizing LMS existing config cards
alphabetize new LMS config buttons
=> chore: cleaning up language + alphabetize existing cards

src/components/EnterpriseApp/index.jsx
=> chore: properly enabling self service settings pages

src/components/Sidebar/index.jsx, src/components/settings/SettingsTabs.jsx
=> chore: fixing how Tabs components are implemented

src/components/settings/SettingsAccessTab/tests/ActionsTableCell.test.jsx, src/components/settings/data/tests/hooks.test.js, src/components/subscriptions/SubscriptionDetailPage.jsx, src/components/subscriptions/SubscriptionPlanRoutes.jsx, src/components/subscriptions/tests/SubscriptionDetailPage.test.jsx, src/components/subscriptions/tests/SubscriptionManagementPage.test.jsx, src/components/subscriptions/tests/data/hooks.test.jsx
Fixes test where we were not using await with waitFor.
=> chore: fix tests using waitFor without await

package-lock.json, package.json, src/components/settings/SettingsAppearanceTab/CustomThemeModal.jsx, src/components/settings/SettingsAppearanceTab/tests/SettingsAppearanceTab.test.jsx
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/boards/630?modal=detail&selectedIssue=ENT-6105
=> feat: add a11y validation to branding

package-lock.json, package.json, src/components/settings/SettingsLMSTab/ErrorReporting/ContentMetadataTable.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/ErrorReporting.test.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/ErrorReportingModal.jsx, src/components/settings/SettingsLMSTab/ExistingCard.jsx, src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx, src/components/settings/SettingsSSOTab/ExistingSSOConfigs.jsx, src/components/settings/data/constants.js, src/components/settings/settings.scss, src/data/services/LmsApiService.js
Three JIRA tickets are included in this PR 
[ENT-6214](https://2u-internal.atlassian.net/browse/ENT-6214) **|**  [ENT-6221](https://2u-internal.atlassian.net/browse/ENT-6221) **|** [ENT-6371](https://2u-internal.atlassian.net/browse/ENT-6371)
=> fix: adding error reporting functionality to LMS integrations

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Hero/Hero.test.jsx, src/components/Hero/index.jsx, src/components/analytics/AnalyticsPage.test.jsx
[Jira Ticket
](https://2u-internal.atlassian.net/browse/ENT-6343)Note: Unfortunately, without changing the way the logo fetches locally, its a little harder to test this if you were to pull in these changes, but you can see the functionality working in the tests.
=> fix: add dynamic color logo

src/components/settings/SettingsLMSTab/ErrorReporting/ContentMetadataTable.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/DownloadCsvButton.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/tests/ErrorReporting.test.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/utils.jsx
[Jira Ticket
](https://2u-internal.atlassian.net/browse/ENT-6212)
=> feat: add in csv download button

src/components/PlotlyAnalytics/PlotlyAnalyticsCharts.jsx
=> fix: token api response handling

src/components/settings/SettingsLMSTab/ErrorReporting/ContentMetadataTable.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/LearnerMetadataTable.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/tests/ErrorReporting.test.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/utils.jsx
FOR TESTING: Must have [this branch](https://github.com/openedx/edx-enterprise/pull/1666) of edx-enterprise locally for it to work!
[Jira ticket](https://2u-internal.atlassian.net/browse/ENT-6461)
=> feat: add error popover

src/components/settings/SettingsLMSTab/ErrorReporting/ContentMetadataTable.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/DownloadCsvButton.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/LearnerMetadataTable.jsx, src/components/settings/SettingsLMSTab/ErrorReporting/tests/ErrorReporting.test.jsx
Tested with 1000 transmission records
=> feat: full csv download implementation for error reporting

src/components/ContentHighlights/HighlightStepper/ContentHighlightStepper.jsx
Quick fix for QA issue regarding highlight set count
=> [skip ci] fix: resolve issue

src/components/ContentHighlights/ContentHighlightCardItem.jsx, src/components/ContentHighlights/ContentHighlightsCardItemsContainer.jsx, src/components/ContentHighlights/HighlightStepper/HighlightStepperConfirmContent.jsx
=> fix: length to itemCount

public/index.html, src/components/Admin/index.jsx, src/components/Admin/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/licenses/LicenseManagementTable/index.jsx, src/index.jsx, src/optimizely.js
=> optimizely experiment for subscriptions and lpr

src/components/Admin/EmbeddedSubscription.jsx, src/components/Admin/SubscriptionDetailPage.jsx, src/components/Admin/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/SubscriptionDetailContextProvider.jsx, src/components/subscriptions/data/constants.js, src/components/subscriptions/data/hooks.js, src/data/services/LicenseManagerAPIService.js
These changes are related to OPTIMIZELY Experiment. Will add the test cases if the experiment changes need to retain. Here is the ticket which will cover this.
https://2u-internal.atlassian.net/browse/ENT-6624
=> feat: Make changes in license table in admin tab.

src/components/ContentHighlights/DeleteHighlightSet.jsx
=> fix: add period at end of sentence

src/components/Admin/Admin.test.jsx, src/components/Admin/index.jsx
=> refactor: Remove SUBSCRIPTION_LPR feature flag.

src/components/subscriptions/data/hooks.js
=> fix: prevent infinite calls on customer-agreement API call when error occurs

src/components/subscriptions/data/hooks.js
=> fix: prevent addtl infinite API calls to license-manager

src/components/Admin/SubscriptionDetailPage.jsx, src/components/Admin/SubscriptionDetails.jsx, src/components/Admin/licenses/LicenseAllocationDetails.jsx, src/components/Admin/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/SubscriptionDetailContextProvider.jsx, src/components/subscriptions/data/constants.js, src/components/subscriptions/data/hooks.js
These changes are related to OPTIMIZELY Experiment. Here is the ticket to cover the test cases for this work.
https://2u-internal.atlassian.net/browse/ENT-6624
=> feat: Enable sorting for the license table on LPR page

src/components/Admin/EmbeddedSubscription.jsx, src/components/Admin/SubscriptionDetailPage.jsx, src/components/Admin/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/SubscriptionDetailContextProvider.jsx, src/components/subscriptions/data/constants.js
Relevant Ticket: https://2u-internal.atlassian.net/browse/ENT-6711
=> refactor: Fix link and remove download button

src/components/ContentHighlights/HighlightStepper/HighlightStepperTitleInput.jsx
Ticket: https://2u-internal.atlassian.net/browse/ENT-6724
Fixes issue with input as described in the ticket.
Passes all existing test and validation to match previous behavior
=> fix: Input reload fix implemented

src/components/settings/SettingsLMSTab/ErrorReporting/utils.jsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/settings.scss
[Jira Ticket
](https://2u-internal.atlassian.net/browse/ENT-6563)
=> fix: FF error reporting fixes

src/components/Admin/EmbeddedSubscription.test.jsx, src/components/Admin/SubscriptionDetailPage.test.jsx, src/components/Admin/SubscriptionDetails.test.jsx, src/components/Admin/licenses/LicenseAllocationDetails.test.jsx, src/components/Admin/licenses/LicenseAllocationHeader.test.jsx, src/components/Admin/licenses/LicenseManagementTable/index.test.jsx, src/components/Admin/licenses/__snapshots__/LicenseAllocationHeader.test.jsx.snap
=> feat: tests for the learner progress report

src/components/settings/SettingsLMSTab/ExistingCard.jsx
Before (FF = false):
After (FF = false):
=> fix: hide integration sync status message behind feature flag

src/components/settings/SettingsLMSTab/LMSConfigPage.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/Blackboard/BlackboardConfig.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Blackboard/BlackboardConfigAuthorizePage.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Canvas/CanvasConfig.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Canvas/CanvasConfigAuthorizePage.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Cornerstone/CornerstoneConfig.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Degreed/DegreedConfig.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Degreed/DegreedConfigEnablePage.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Moodle/MoodleConfig.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/Moodle/MoodleConfigEnablePage.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAP/SAPConfig.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/SAP/SAPConfigEnablePage.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/utils.tsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.tsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.tsx, src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.tsx, src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx, src/components/settings/SettingsLMSTab/utils.js
You can see in the recording when you make a change to an existing canvas config, it prompts you to reauthorize (you can see the link icon in the button). 
https://github.com/openedx/frontend-app-admin-portal/assets/31229189/955bbb81-7b7d-438e-844c-9ee3aa08137f
=> fix: bug bash fixes

src/components/forms/data/reducer.ts, src/components/settings/SettingsLMSTab/ErrorReporting/tests/SyncHistory.test.jsx, src/components/settings/SettingsLMSTab/index.jsx
Addressing the New Relic issue identified from this ticket https://2u-internal.atlassian.net/browse/ENT-7276. Fix removes the error below.
=> fix: adding query size check

src/components/learner-credit-management/LearnerCreditAllocationTable.jsx, src/components/learner-credit-management/data/utils.js, src/components/learner-credit-management/tests/LearnerCreditAllocationTable.test.jsx, src/utils.js
**Description**: This PR adds a new column for course product line in the learner credit summary table
**JIRA**: [ENT-7033](https://2u-internal.atlassian.net/browse/ENT-7033)
=> feat: Added column for course product line in learner credit table

src/components/Admin/licenses/LicenseAllocationHeader.jsx, src/components/Admin/licenses/__snapshots__/LicenseAllocationHeader.test.jsx.snap
=> refactor: fix the subscription table label value on LPR

src/containers/Sidebar/Sidebar.test.jsx
Sidebar component is missing a few tests.
Added more unit tests for more coverage
[JIRA](https://2u-internal.atlassian.net/browse/ENT-3958)
=> test: add test coverage for sidebar component

src/components/EnterpriseSubsidiesContext/data/hooks.js
**Description**: This PR adds support for multiple active plans in the the subsidies context
**JIRA**: [ENT-7519](https://2u-internal.atlassian.net/browse/ENT-7519)
=> feat: ENT-7519 Added support for multiple active offers in subsidy context

src/components/learner-credit-management/BudgetCard-V2.jsx, src/components/learner-credit-management/LearnerCreditAllocationTable.jsx, src/components/learner-credit-management/MultipleBudgetsPicker.jsx, src/components/learner-credit-management/tests/BudgetCard.test.jsx
=> feat: Show one card on learner credit screen

src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
=> fix: ensure budget_id query param is passed to analytics api

src/data/services/LmsApiService.js
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-7363
**Description**: Removed trailing` /` from AI analytics endpoint url
=> Fix: removed trailing / from AI analytics endpoint url

src/components/Admin/AIAnalyticsSummary.jsx, src/components/Admin/AIAnalyticsSummary.test.jsx, src/components/Admin/AIAnalyticsSummarySkeleton.jsx, src/components/Admin/__snapshots__/AIAnalyticsSummary.test.jsx.snap, src/components/Admin/__snapshots__/Admin.test.jsx.snap
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-7363
**Description**: Track Progress is currently hidden due to data inconsistency. It will be addressed as part of [ENT-7812](https://2u-internal.atlassian.net/browse/ENT-7812)
=> fix: hide track progress tab temporarily due to data issues

src/components/learner-credit-management/index.js, src/components/learner-credit-management/index.jsx
=> fix: detailpage routes issue

src/components/forms/FormContextWrapper.tsx, src/components/forms/FormWorkflow.tsx, src/components/forms/ValidatedFormControl.tsx, src/components/forms/ValidatedFormRadio.tsx, src/components/forms/data/reducer.test.ts, src/components/forms/data/reducer.ts, src/components/settings/SettingsSSOTab/NewSSOStepper.jsx, src/components/settings/SettingsSSOTab/SSOFormWorkflowConfig.tsx, src/components/settings/SettingsSSOTab/UnsavedSSOChangesModal.tsx, src/components/settings/SettingsSSOTab/steps/NewSSOConfigAuthorizeStep.tsx, src/components/settings/SettingsSSOTab/steps/NewSSOConfigConfigureStep.tsx, src/components/settings/SettingsSSOTab/steps/NewSSOConfigConnectStep.tsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7578)
=> Hook up new SSO Config Workflow to API

src/components/forms/FormWorkflow.tsx, src/components/forms/_FormWorkflow.scss
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7910)
=> feat: Add loading spinner to FormWorkflow next button

src/components/settings/SettingsSSOTab/NewExistingSSOConfigs.jsx, src/components/settings/SettingsSSOTab/NewSSOConfigCard.jsx, src/components/settings/SettingsSSOTab/NewSSOConfigForm.jsx, src/components/settings/SettingsSSOTab/NewSSOStepper.jsx, src/components/settings/SettingsSSOTab/index.jsx, src/components/settings/SettingsSSOTab/steps/SSOConfigIDPStep.jsx, src/components/settings/SettingsSSOTab/tests/ExistingSSOConfigs.test.jsx, src/components/settings/SettingsSSOTab/tests/NewExistingSSOConfigs.test.jsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigCard.test.jsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
=> fix: cleaning up sso self service wording and behaviors

src/components/forms/ValidatedFormCheckbox.tsx, src/components/settings/SettingsSSOTab/steps/NewSSOConfigAuthorizeStep.tsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7984)
=> chore: Add error message for SSO config step 3 authorization checkbox

src/components/settings/SettingsSSOTab/index.jsx, src/components/settings/SettingsSSOTab/tests/SettingsSSOTab.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7989)
https://github.com/openedx/frontend-app-admin-portal/assets/322346/da39a0c5-7b6d-4b12-b5e4-139e41134a4e
=> Add loading spinner to Create new SSO button

src/components/settings/SettingsSSOTab/SSOFormWorkflowConfig.tsx, src/components/settings/SettingsSSOTab/steps/NewSSOConfigAuthorizeStep.tsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-7990)
Utilizing changes made in https://github.com/openedx/edx-enterprise/pull/1951
=> feat: Persist SSO Config 'authorized' checkbox state

src/components/EnterpriseSubsidiesContext/data/hooks.js, src/components/ProductTours/data/hooks.js
Reverts openedx/frontend-app-admin-portal#1125
Further stage testing revealed lingering problems on Assignment that wasn't manifesting itself locally
=> Revert "fix: disables refetch on window focus for useEnterpriseBudgets useQuery hook call"

src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
Makes the button red for new assignments to match figma.
=> fix: update variant on new assignment button

src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx
Sets button variant to primary (its default variant) for the "New course assignment" button
=> fix: sets button variant to primary

src/components/settings/data/hooks.js
=> fix: remove color style on outline button variants for dynamic themes

src/components/ContentHighlights/tests/ContentHighlights.test.jsx, src/components/learner-credit-management/BudgetDetailCatalogTabContents.jsx
=> fix: updates package reference for useLocation

src/components/settings/SettingsSSOTab/steps/NewSSOConfigConfigureStep.tsx
https://2u-internal.atlassian.net/browse/ENT-8170
=> fix: adding country attribute mapping to sso self serve stepper

src/components/PlotlyAnalytics/data/service.jsx
=> fix: correct object key name

src/components/NumberCard/index.jsx
=> fix: navigation issue of admin card on learners page

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx
=> fix: disable issue of download button on admin page

src/components/Admin/AIAnalyticsSummary.jsx
=> feat: add segment event for summarize analytics button

src/components/settings/SettingsLMSTab/ExistingCard.jsx
=> fix: redirectPath should end with slash

src/data/services/EnterpriseDataApiService.js
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-8296
=> fix: summarize analytics for demo data

src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
=> fix: features gated behind flag

package-lock.json, package.json, src/i18n/index.js
=> fix: Added atlas as a dependency

src/components/Admin/AdminSearchForm.jsx, src/components/Admin/__snapshots__/Admin.test.jsx.snap
Jira ->. [ENT-8490](https://2u-internal.atlassian.net/browse/ENT-8490)
=> fix: info tooltip issue on overview page

src/components/learner-credit-management/BudgetDetailActivityTabContents.jsx, src/components/learner-credit-management/BudgetDetailMembersTabContents.jsx, src/components/learner-credit-management/BudgetDetailTabsAndRoutes.jsx, src/components/learner-credit-management/LearnerCreditGroupMembersTable.jsx, src/components/learner-credit-management/MemberDetailsTableCell.jsx, src/components/learner-credit-management/MemberEnrollmentsTableColumnHeader.jsx, src/components/learner-credit-management/MemberStatusTableCell.jsx, src/components/learner-credit-management/MemberStatusTableColumnHeader.jsx, src/components/learner-credit-management/data/constants.js, src/components/learner-credit-management/data/hooks/index.js, src/components/learner-credit-management/data/hooks/useBudgetDetailTabs.jsx, src/components/learner-credit-management/data/hooks/useEnterpriseGroupLearners.js, src/components/learner-credit-management/data/hooks/useEnterpriseGroupMembersTableData.js, src/components/learner-credit-management/data/tests/constants.js, src/components/learner-credit-management/data/utils.js, src/components/learner-credit-management/invite-modal/InviteMembersModalWrapper.jsx, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx, src/data/services/LmsApiService.js
https://2u-internal.atlassian.net/browse/ENT-8503
=> feat: adding budget group members tab

.gitignore, src/components/Admin/AIAnalyticsSummary.jsx, src/components/learner-credit-management/search/CatalogSearch.jsx
__Jira Ticket:__ [ENT-8744](https://2u-internal.atlassian.net/browse/ENT-8744)
This PR fixes `extract_translations` commands to make sure the i18n pipeline completes with success.
=> ENT-8744:  fixed errors for i18n related commands.

src/components/settings/SettingsLMSTab/ErrorReporting/SyncHistory.jsx
=> fix: remove unnecessary trailing slash in redirect path

src/components/ContentHighlights/CatalogVisibility/ContentHighlightCatalogVisibilityAlert.jsx, src/components/ContentHighlights/CatalogVisibility/ContentHighlightCatalogVisibilityHeader.jsx, src/components/ContentHighlights/CatalogVisibility/ContentHighlightCatalogVisibilityRadioInput.jsx, src/components/ContentHighlights/CatalogVisibility/tests/ContentHighlightCatalogVisibilityAlert.test.jsx, src/components/ContentHighlights/CatalogVisibility/tests/ContentHighlightCatalogVisibilityRadioInput.test.jsx, src/components/ContentHighlights/ContentHighlightArchivedAlert.jsx, src/components/ContentHighlights/ContentHighlightCardContainer.jsx, src/components/ContentHighlights/ContentHighlightCardItem.jsx, src/components/ContentHighlights/ContentHighlightSetCard.jsx, src/components/ContentHighlights/ContentHighlights.jsx, src/components/ContentHighlights/ContentHighlightsCardItemsContainer.jsx, src/components/ContentHighlights/ContentHighlightsDashboard.jsx, src/components/ContentHighlights/CurrentContentHighlightHeader.jsx, src/components/ContentHighlights/DeleteArchivedHighlightsDialogs.jsx, src/components/ContentHighlights/DeleteHighlightSet.jsx, src/components/ContentHighlights/HighlightStepper/tests/ContentConfirmContentCard.test.jsx, src/components/ContentHighlights/HighlightStepper/tests/HighlightStepperConfirmContent.test.jsx, src/components/ContentHighlights/ZeroState/ZeroStateHighlights.jsx, src/components/ContentHighlights/data/constants.js, src/components/ContentHighlights/data/utils.js, src/components/ContentHighlights/tests/ContentHighlightCardItem.test.jsx, src/components/ContentHighlights/tests/ContentHighlightSetCard.test.jsx, src/components/ContentHighlights/tests/ContentHighlightsDashboard.test.jsx, src/components/ContentHighlights/tests/HighlightSetSection.test.jsx, src/components/Sidebar/index.jsx, src/containers/Sidebar/Sidebar.test.jsx
**Description:** Mark static text on highlights page for i18n.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-8753
=> feat: mark static text in highlights page for i18n

src/components/BudgetExpiryAlertAndModal/index.jsx, src/components/CodeManagement/tests/CouponCodeTabs.test.jsx, src/components/EnterpriseApp/EnterpriseApp.test.jsx, src/components/NotFoundPage/NotFoundPage.test.jsx, src/components/NotFoundPage/index.jsx, src/components/learner-credit-management/AssignMoreCoursesEmptyStateMinimal.jsx, src/components/learner-credit-management/BudgetAssignmentsTable.jsx, src/components/learner-credit-management/BudgetDetailAssignments.jsx, src/components/learner-credit-management/BudgetDetailPage.jsx, src/components/learner-credit-management/BudgetDetailPageBreadcrumbs.jsx, src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx, src/components/learner-credit-management/BudgetDetailPageOverviewUtilization.jsx, src/components/learner-credit-management/BudgetDetailPageWrapper.jsx, src/components/learner-credit-management/BudgetDetailRedemptions.jsx, src/components/learner-credit-management/BudgetOverviewContent.jsx, src/components/learner-credit-management/BudgetStatusSubtitle.jsx, src/components/learner-credit-management/CustomDataTableEmptyState.jsx, src/components/learner-credit-management/LearnerCreditAllocationTable.jsx, src/components/settings/tests/SettingsPage.test.jsx, src/components/subscriptions/tests/SubscriptionTabs.test.jsx
JIRA ->[ ENT-8751](https://2u-internal.atlassian.net/browse/ENT-8751)
=> feat: mark static strings for i18n on lcm detail page

src/components/learner-credit-management/AssignmentTableCancel.jsx, src/components/learner-credit-management/AssignmentTableRemind.jsx, src/components/learner-credit-management/AssignmentsTableRefreshAction.jsx, src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx, src/components/learner-credit-management/CancelAssignmentModal.jsx, src/components/learner-credit-management/RemindAssignmentModal.jsx, src/components/learner-credit-management/assignment-modal/AssignmentAllocationHelpCollapsibles.jsx, src/components/learner-credit-management/assignment-modal/AssignmentModalContent.jsx, src/components/learner-credit-management/assignment-modal/AssignmentModalSummary.jsx, src/components/learner-credit-management/assignment-modal/AssignmentModalSummaryEmptyState.jsx, src/components/learner-credit-management/assignment-modal/AssignmentModalSummaryErrorState.jsx, src/components/learner-credit-management/assignment-modal/AssignmentModalSummaryLearnerList.jsx, src/components/learner-credit-management/assignment-modal/NewAssignmentModalButton.jsx, src/components/learner-credit-management/cards/BaseCourseCard.jsx, src/components/learner-credit-management/cards/CourseCardFooterActions.jsx, src/components/learner-credit-management/cards/tests/CourseCard.test.jsx, src/components/learner-credit-management/data/hooks/useBudgetDetailTabs.jsx, src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRemindModal.test.jsx
JIRA -> [ENT-8752](https://2u-internal.atlassian.net/browse/ENT-8752)
=> feat: mark static strings for i18n on new course assignment page

src/components/ContentHighlights/HighlightStepper/ContentHighlightStepper.jsx, src/components/ContentHighlights/HighlightStepper/HighlightStepperTitle.jsx, src/components/ContentHighlights/data/constants.js
=> feat: Added new highlights stepper i18n text

src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx, src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8865
https://github.com/openedx/enterprise-access/pull/462
=> feat: allowing for sort by enrollment count on group members table

src/components/learner-credit-management/BudgetDetail.jsx, src/components/learner-credit-management/BudgetDetailPageOverviewAvailability.jsx, src/components/learner-credit-management/BudgetOverviewContent.jsx, src/components/learner-credit-management/data/hooks/index.js, src/components/learner-credit-management/data/hooks/useContentMetadata.js, src/components/learner-credit-management/invite-modal/InviteMembersModalWrapper.jsx, src/components/learner-credit-management/invite-modal/InviteModalBudgetCard.jsx, src/components/learner-credit-management/invite-modal/InviteModalContent.jsx, src/components/learner-credit-management/invite-modal/InviteModalMembershipInfo.jsx, src/components/learner-credit-management/invite-modal/InviteModalPermissions.jsx, src/components/learner-credit-management/invite-modal/tests/InviteMemberModal.test.jsx, src/components/learner-credit-management/styles/index.scss, src/data/services/EnterpriseCatalogApiService.js, src/data/services/LmsApiService.js
[Figma](https://www.figma.com/file/H69Met5YL7xu5w5LRliumQ/Groups-MVP?type=design&node-id=4387-19230&mode=design&t=wVu1M1K1B4CtZ316-4) | [Jira](https://2u-internal.atlassian.net/browse/ENT-8500) 
https://github.com/openedx/frontend-app-admin-portal/assets/31229189/258c6690-52fe-4f6f-97dd-563a9fc4cc29
=> feat: adding in extra modal info

src/components/learner-credit-management/BudgetDetailPage.jsx, src/components/learner-credit-management/BudgetDetailTabsAndRoutes.jsx, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx
[Jira ticket 
](https://2u-internal.atlassian.net/browse/ENT-8883)<img width="475" alt="Screenshot 2024-05-10 at 10 18 17 AM" src="https://github.com/openedx/frontend-app-admin-portal/assets/31229189/164bcb12-282e-40aa-939a-a36d6aff0b9e">
=> fix: fixing member tab bug

src/components/learner-credit-management/MultipleBudgetsPage.jsx, src/components/learner-credit-management/MultipleBudgetsPicker.jsx, src/components/learner-credit-management/SubBudgetCard.jsx, src/components/learner-credit-management/data/tests/utils.test.js, src/components/learner-credit-management/data/utils.js
JIRA -> [ENT-8750](https://2u-internal.atlassian.net/browse/ENT-8750)
=> feat: mark static strings for i18n on lcm budgets page

src/components/learner-credit-management/BudgetStatusSubtitle.jsx, src/components/learner-credit-management/cards/data/utils.js, src/components/learner-credit-management/invite-modal/FileUpload.jsx, src/components/learner-credit-management/invite-modal/InviteModalContent.jsx, src/components/learner-credit-management/invite-modal/InviteModalInputFeedback.jsx, src/components/learner-credit-management/invite-modal/tests/InviteMemberModal.test.jsx, src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx, src/components/learner-credit-management/members-tab/bulk-actions/MemberRemoveModal.jsx, src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8940
Update text labels for groups feature.
|description|before|after|
|-----------|------|-----|
|Budget headers: "Assignable" should read "Assignment"|![Screenshot 2024-05-15 at 1 22 59 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/290fb571-d34d-4a8e-97ad-7667f7a0e880)|![Screenshot 2024-05-15 at 1 22 42 PM](https://github.com/openedx/frontend-app-admin-portal/assets/71999631/61430dee-8f25-4a21-b8f1-0ffeaee14907)|
|Incorrect messaging with 1001+ emails|<img width="372" alt="0c4e1bde-bbd2-4992-9d36-f310330bbc0d" src="https://github.com/openedx/frontend-app-admin-portal/assets/71999631/09f8f0da-2170-42b0-8add-0a0152741418">|![Screenshot 2024-05-15 at 1 29 59 PM](https://github.com/openedx/frontend-app-admin-portal/asset …
=> fix: text labeling fixes

src/components/learner-credit-management/data/tests/constants.js, src/components/learner-credit-management/members-tab/GroupMembersCsvDownloadTableAction.jsx, src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx, src/components/learner-credit-management/members-tab/bulk-actions/MemberRemoveModal.jsx, src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx
[ENT-9023](https://2u-internal.atlassian.net/browse/ENT-9023)
Page selected, not all records:
Page all records selected:
=>  fix: allowing members table to select all

src/components/Admin/licenses/LicenseAllocationDetails.test.jsx, src/components/ContactCustomerSupportButton/index.jsx, src/components/InviteLearnersModal/index.jsx, src/components/NewFeatureAlertBrowseAndRequest/index.jsx, src/components/SubsidyRequestManagementTable/SubsidyRequestManagementTable.jsx, src/components/subscriptions/MultipleSubscriptionsPage.jsx, src/components/subscriptions/SubscriptionData.jsx, src/components/subscriptions/SubscriptionDetails.jsx, src/components/subscriptions/SubscriptionManagementPage.jsx, src/components/subscriptions/SubscriptionSubsidyRequests.jsx, src/components/subscriptions/SubscriptionTabs.jsx, src/components/subscriptions/SubscriptionZeroStateMessage.jsx, src/components/subscriptions/buttons/DownloadCsvButton.jsx, src/components/subscriptions/buttons/InviteLearnersButton.jsx, src/components/subscriptions/expiration/SubscriptionExpirationBanner.jsx, src/components/subscriptions/expiration/SubscriptionExpiringModal.jsx, src/components/subscriptions/licenses/LicenseAllocationHeader.jsx, src/components/subscriptions/licenses/LicenseManagementTable/index.jsx, src/components/subscriptions/tests/SubscriptionDetailPage.test.jsx, src/components/subscriptions/tests/SubscriptionSubsidyRequests.test.jsx, src/components/subscriptions/tests/expiration/SubscriptionExpirationModals.test.jsx, src/components/subscriptions/tests/expiration/SubscriptionExpiredModal.test.jsx, src/components/subscriptions/tests/licenses/LicenseAllocationHeader.test.jsx, src/components/subsidy-request-management-alerts/NoAvailableLicensesBanner.jsx, src/components/subsidy-request-modals/ApproveLicenseRequestModal.jsx, src/components/subsidy-request-modals/tests/ApproveLicenseRequestModal.test.jsx, src/containers/InviteLearnersModal/InviteLearnersModal.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8765
Marked all the static strings for i18n on subscription management page
=> [ENT-8765] Marked strings for i18n on Subscription Management page

src/components/settings/HelpCenterButton.jsx, src/components/settings/SettingsApiCredentialsTab/APICredentialsPage.jsx, src/components/settings/SettingsApiCredentialsTab/ZeroStateCard.jsx, src/components/settings/SettingsApiCredentialsTab/index.jsx, src/components/settings/SettingsApiCredentialsTab/tests/SettingsAPICredentialsPage.test.jsx, src/components/settings/SettingsAppearanceTab/CustomThemeModal.jsx, src/components/settings/SettingsAppearanceTab/index.jsx, src/components/settings/SettingsAppearanceTab/tests/SettingsAppearanceTab.test.jsx, src/components/settings/SettingsLMSTab/ExistingCard.jsx, src/components/settings/SettingsLMSTab/ExistingLMSCardDeck.jsx, src/components/settings/SettingsLMSTab/LMSConfigPage.jsx, src/components/settings/SettingsLMSTab/LMSConfigs/Blackboard/BlackboardConfigAuthorizePage.tsx, src/components/settings/SettingsLMSTab/LMSConfigs/ConfigBasePages/ConfigActivatePage.tsx, src/components/settings/SettingsLMSTab/LMSSelectorPage.tsx, src/components/settings/SettingsLMSTab/NoConfigCard.jsx, src/components/settings/SettingsLMSTab/UnsavedChangesModal.tsx, src/components/settings/SettingsLMSTab/index.jsx, src/components/settings/SettingsLMSTab/tests/BlackboardConfig.test.tsx, src/components/settings/SettingsLMSTab/tests/CanvasConfig.test.tsx, src/components/settings/SettingsLMSTab/tests/CornerstoneConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/DegreedConfig.test.tsx, src/components/settings/SettingsLMSTab/tests/ExistingLMSCardDeck.test.jsx, src/components/settings/SettingsLMSTab/tests/LmsConfigPage.test.jsx, src/components/settings/SettingsLMSTab/tests/MoodleConfig.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx, src/components/subsidy-request-management-alerts/NoAvailableLicensesBanner.jsx
https://2u-internal.atlassian.net/browse/ENT-8763
Marked strings on following last three tabs of settings page
- Learning Platform Tab
- Portal Appearances Tab
- API Credentials Tab
=> [ENT-8763] Marked strings on last three tabs of settings page

src/components/learner-credit-management/cards/data/utils.js, src/components/learner-credit-management/invite-modal/InviteModalSummary.jsx, src/components/learner-credit-management/invite-modal/tests/InviteMemberModal.test.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-8941)
Corrects error message for multiple invalid email addresses when inviting group members, and also allows for inviting valid emails to groups.
=> fix: rules for invalid emails in group invite modal

.github/workflows/ci.yml, package.json
=> feat: add github check to validate i18n string extraction

src/components/learner-credit-management/members-tab/BudgetDetailMembersTabContents.jsx, src/components/learner-credit-management/members-tab/GroupMembersCsvDownloadTableAction.jsx, src/components/learner-credit-management/members-tab/LearnerCreditGroupMembersTable.jsx, src/components/learner-credit-management/members-tab/MemberDetailsTableCell.jsx, src/components/learner-credit-management/members-tab/MemberEnrollmentsTableColumnHeader.jsx, src/components/learner-credit-management/members-tab/MemberStatusTableCell.jsx, src/components/learner-credit-management/members-tab/MemberStatusTableColumnHeader.jsx, src/components/learner-credit-management/members-tab/MembersTableSwitchFilter.jsx, src/components/learner-credit-management/members-tab/bulk-actions/MemberRemoveAction.jsx, src/components/learner-credit-management/members-tab/bulk-actions/MemberRemoveModal.jsx
=> feat: mark static strings for i18n in members tab on budget detail page

src/components/learner-credit-management/BudgetStatusSubtitle.jsx
=> fix: small subtitle fix

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx
=> fix: Fixed a small UI inconsistency.

src/components/AdvanceAnalyticsV2/data/constants.js, src/components/AdvanceAnalyticsV2/data/hooks.js, src/components/AdvanceAnalyticsV2/tabs/Leaderboard.jsx, src/components/AdvanceAnalyticsV2/tabs/Leaderboard.test.jsx, src/data/services/EnterpriseDataApiService.js, src/utils.js
**Description:** Add datatable on leaderboard tab.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-9240
=> add leaderboard datatable

src/components/subscriptions/licenses/LicenseManagementModals/LicenseManagementRevokeModal.jsx, src/components/subscriptions/licenses/LicenseManagementModals/tests/LicenseManagementRevokeModal.test.jsx
https://github.com/user-attachments/assets/294e3bc2-bcd8-47ac-85f5-59521c7ffa63
=> [ENT-9206] - bulk-revoke endpoint changes

src/components/AdvanceAnalyticsV2/styles/index.scss
we were facing a chart height issue while we loaded data. So, this PR is fixing the height of the charts so that it looks consistent in all states.
=> fix: loading charts height issue

src/components/AdvanceAnalyticsV2/data/utils.js, src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
__Jira Ticket:__ [ENT-9420](https://2u-internal.atlassian.net/browse/ENT-9420)
This PR fixes the format of CSV data downloaded by the download buttons.
=> fix: Fixed CSV data.

src/components/AdvanceAnalyticsV2/tabs/Completions.jsx, src/components/AdvanceAnalyticsV2/tabs/Enrollments.jsx
=> fix: Updated courseKey with courseTitle for charts

src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx
CSV name was not including start and end dates in file names. So fix that issue.
=> fix: csv name issue in analytics v2

src/components/PeopleManagement/GroupCardGrid.jsx, src/components/PeopleManagement/_PeopleManagement.scss
Wraps CSS changes in a parent class and applies it to the groups related collapsible.
=> fix: specify parent class for css changes

src/components/AdvanceAnalyticsV2/AnalyticsV2Page.jsx, src/components/AdvanceAnalyticsV2/WarningBanner.jsx, src/components/AdvanceAnalyticsV2/data/constants.js, src/components/AdvanceAnalyticsV2/tests/WarningBanner.test.jsx
=> feat: added dismissable warning banner on analytics v2

src/components/PeopleManagement/CreateGroupModalContent.jsx
Fixes bug that adds invalid org members to a group in the create group modal.
https://2u-internal.atlassian.net/browse/ENT-9858
https://github.com/user-attachments/assets/1a0ae621-61f8-4b0c-ac88-673fdf212ac8
=> feat: fixes invalid members being added to groups

renovate.json
This PR will hopefully start consolidating renovate PRs with the goal of alleviating renovate package validation.
=> chore: consolidate renovate PRs into a single PR

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/index.jsx, src/components/NumberCard/NumberCard.test.jsx, src/components/NumberCard/index.jsx
https://github.com/user-attachments/assets/b4f919d4-e4d5-4850-a247-70f83b92dd4a
JIRA-> [ENT-9931](https://2u-internal.atlassian.net/browse/ENT-9931)
=> fix: lpr scroll to reports issue when click selecting additional details

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/tabs/ModuleActivityReport.jsx, src/components/Admin/tabs/ModuleActivityReport.test.jsx
__Jira Ticket:__ [ENT-10021](https://2u-internal.atlassian.net/browse/ENT-10021)
This PR adds 3 new columns for module activity report's data table and the CSV file that user can download. The columns are listed below
1. `Learning Outcomes: Before` This column that contains user's learning outcome score before starting the course.
2. `Learning Outcomes: After` This column that contains user's learning outcome score after completing the course.
3. `Learning Outcomes % Difference` This columns shows the % increment/decrement in user's learning outcome score.
=> ENT-10021: Added 3 new columns in module activity report.

src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Admin/tabs/ModuleActivityReport.jsx
Forgot to push a commit as part of https://github.com/openedx/frontend-app-admin-portal/pull/1434 details are on that PR.
=> Added % sign to 2 columns that contain percentage values.

docs/decisions/0011-typescript-migration-over-time.rst
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10156)
This ADR lays out recommendations for adopting TypeScript over time in Admin Portal.
=> docs: ADR for adopting typescript over time

src/components/settings/SettingsSSOTab/steps/SSOConfigConfigureStep.jsx
Ref https://github.com/openedx/docs.openedx.org/issues/955
This is the only instance I see in this repository.
=> docs: Update edx.rtd links to docs.openedx.org

public/index.html
Adds meta tag to prevent indexing of the admin portal in search engines.
=> fix: add meta tag to prevent search indexing

src/data/actions/csv.js, src/data/actions/csv.test.js
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-10107
=> fix: set mime type on csv blob

src/components/ContentHighlights/HighlightStepper/ContentHighlightStepper.jsx, src/components/ContentHighlights/tests/ContentHighlightsDashboard.test.jsx, src/components/ContentHighlights/tests/DeleteHighlightSet.test.jsx, src/components/EnterpriseSubsidiesContext/data/tests/hooks.test.jsx, src/components/learner-credit-management/data/hooks/tests/useBudgetContentAssignments.test.js, src/components/learner-credit-management/data/hooks/useEnterpriseGroup.ts, src/components/learner-credit-management/invite-modal/tests/InviteMemberModal.test.jsx, src/components/learner-credit-management/members-tab/tests/MembersTab.test.jsx, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx, src/components/settings/SettingsSSOTab/index.jsx
Updates some test for the React 18 upgrade.
=> fix: update tests for react 18 upgrade

src/components/Admin/__snapshots__/AIAnalyticsSummary.test.jsx.snap, src/components/Admin/__snapshots__/Admin.test.jsx.snap, src/components/Coupon/__snapshots__/Coupon.test.jsx.snap, src/components/subsidy-requests/data/hooks.js, src/components/subsidy-requests/data/tests/hooks.test.js
Additional updates for the react 18 upgrade.
=> chore: update tests and snapshot

src/components/CouponDetails/CouponBulkActions.test.jsx, src/components/forms/tests/ValidatedFormRadio.test.tsx, src/components/learner-credit-management/data/hooks/tests/useBudgetRedemptions.test.jsx, src/components/settings/SettingsLMSTab/tests/SAPConfig.test.jsx, src/components/settings/SettingsSSOTab/tests/NewExistingSSOConfigs.test.jsx, src/components/settings/SettingsSSOTab/tests/NewSSOConfigForm.test.jsx, src/components/subscriptions/tests/SubscriptionDetails.test.jsx, src/setupTest.js
Update additional tests for react 18 upgrade.
=> chore: add additional tests updates

src/components/AdvanceAnalyticsV2.0/AnalyticsFilters.jsx, src/components/AdvanceAnalyticsV2.0/AnalyticsPage.jsx, src/components/AdvanceAnalyticsV2.0/styles/index.scss, src/components/AdvanceAnalyticsV2.0/tabs/Engagements.jsx, src/components/AdvanceAnalyticsV2.0/tests/AnalyticsFilters.test.jsx
This PR restores the lost commits that were originally merged into the parent branch in [PR #1539](https://github.com/openedx/frontend-app-admin-portal/pull/1539), which was mistakenly overwritten due to a rebase conflict. The changes have been cherry-picked and are now being reintroduced again here.
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-10539
=> [ENT-10539] Reintroduced granularity and calculation filters from PR #1539 after rebase conflict

src/components/Admin/licenses/LicenseManagementTable/index.test.jsx, src/components/AdvanceAnalyticsV2.0/charts/BarChart.test.jsx, src/components/AdvanceAnalyticsV2.0/charts/EmptyChart.test.jsx, src/components/AdvanceAnalyticsV2.0/charts/LineChart.test.jsx, src/components/AdvanceAnalyticsV2.0/charts/ScatterChart.test.jsx, src/components/AdvanceAnalyticsV2.0/data/hooks.test.jsx, src/components/AdvanceAnalyticsV2.0/tests/AnalyticsPage.test.jsx, src/components/AdvanceAnalyticsV2.0/tests/DownloadCSVButton.test.jsx, src/components/AdvanceAnalyticsV2.0/tests/Header.test.jsx, src/components/AdvanceAnalyticsV2.0/tests/Stats.test.jsx, src/components/ProductTours/tests/ProductTours.test.jsx
Clean up final set of tests for react 18 tests
=> chore: cleanup final tests

src/components/AdvanceAnalyticsV2.0/charts/EmptyChart.test.jsx, src/components/AdvanceAnalyticsV2.0/charts/SkillsByLearningHoursChart.test.jsx, src/components/AdvanceAnalyticsV2.0/charts/Treemap.test.jsx
Comment out net new test that utilize enzyme with the expectation that the owning team will refactor.
=> chore: comment out new enzyme tests

src/components/Admin/index.jsx, src/utils.js
**Description:** Pass query params to backend to fetch the filtered data only.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-10564
=> feat: fetch filtered data when filters are active

src/components/learner-credit-management/BudgetDetailTabsAndRoutes.jsx, src/components/learner-credit-management/cards/CourseCardFooterActions.jsx, src/components/learner-credit-management/data/hooks/tests/useBudgetDetailTabs.test.jsx, src/components/learner-credit-management/data/hooks/useBudgetDetailTabs.jsx, src/components/learner-credit-management/data/types.ts, src/components/learner-credit-management/search/CatalogSearch.tsx
=> feat: made changes in catalog tab for BNR policy

src/components/AdminV2/LearnerReport.jsx, src/components/AdminV2/tests/Admin.test.jsx
=> feat: show-hide module activity report for LPRv2

src/components/ProductTours/AdminOnboardingTours/CustomizeReportsFlow.tsx, src/components/ProductTours/AdminOnboardingTours/SetUpPreferencesFlow.tsx, src/components/ProductTours/AdminOnboardingTours/constants.js, src/components/ProductTours/AdminOnboardingTours/flows/AdminOnboardingTour.tsx, src/components/ProductTours/AdminOnboardingTours/flows/CustomizeReportsFlow.tsx, src/components/ProductTours/AdminOnboardingTours/messages.js, src/components/ProductTours/AdminOnboardingTours/tests/CustomizeReportsFlow.test.jsx, src/components/ProductTours/AdminOnboardingTours/tests/SetUpPreferencesFlow.test.jsx, src/components/ProductTours/TourCollapsible.tsx, src/components/ProductTours/tests/TourCollapsible.test.jsx, src/components/Sidebar/index.jsx
[Jira Ticket](https://2u-internal.atlassian.net/browse/ENT-10360)
https://github.com/user-attachments/assets/7c5e5ba0-a578-43b1-86c4-e7db0b7d0cc6
Customer with Reporting Enabled: https://localhost.stage.edx.org:1991/exec-ed-2u-integration-qa/admin/learners
Customer with Reporting Disabled: https://localhost.stage.edx.org:1991/alc-general/admin/learners
=> feat: add onboarding flows for settings and reporting

src/components/learner-credit-management/requests-tab/RequestFailureModal.jsx
=> fix: supporting url for help center on requests table

src/components/learner-credit-management/ApprovedRequestActionsTableCell.jsx, src/components/learner-credit-management/ApprovedRequestTableCancel.jsx, src/components/learner-credit-management/BudgetDetailApprovedRequestTable.jsx, src/components/learner-credit-management/CancelApprovedRequestModal.jsx, src/components/learner-credit-management/CancelAssignmentModal.jsx, src/components/learner-credit-management/data/hooks/index.js, src/components/learner-credit-management/data/hooks/tests/useCancelApprovedRequest.test.jsx, src/components/learner-credit-management/data/hooks/useCancelApprovedRequest.js, src/components/learner-credit-management/data/hooks/useSuccessfulCancellationToastContextValue.js, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx, src/data/services/EnterpriseAccessApiService.ts, src/eventTracking.js
=> feat: add cancel approval functionality for learner credit requests

src/components/learner-credit-management/data/hooks/useBudgetDetailHeaderData.js
**Ticket:** [ENT-10704](https://2u-internal.atlassian.net/browse/ENT-10704)
**Description:** Aggregate pending and spent amount as utilized for bnr enabled policies.
=> fix: aggregate pending and spent amount as utilized for bnr

src/components/learner-credit-management/ApprovedRequestTableRemind.jsx, src/components/learner-credit-management/data/hooks/tests/useRemindApprovedRequest.test.jsx, src/components/learner-credit-management/data/hooks/useRemindApprovedRequest.jsx, src/components/learner-credit-management/tests/BudgetDetailPage.test.jsx, src/data/services/EnterpriseAccessApiService.ts
=> fix: admin permission issue for remind endpoint

src/components/learner-credit-management/data/hooks/useBnrSubsidyRequests.js, src/data/services/EnterpriseAccessApiService.ts, src/data/services/tests/EnterpriseAccessApiService.test.js
=> fix: added policy_uuid in requests preview endpoint

src/components/Admin/licenses/LicenseManagementTable/index.jsx, src/components/CheckboxFilter/CheckboxFilter.tsx, src/components/CheckboxFilter/index.ts, src/components/subscriptions/licenses/LicenseManagementTable/index.jsx
- Temporary stopgap: replace Paragon’s CheckboxFilter with a local implementation until the official fix in Paragon v22.
- Preserves existing UX and accessibility; intended to be reverted after upgrading to Paragon v22.
https://github.com/user-attachments/assets/3440daef-7115-4528-b0b6-5ba52b485df1
- Added local CheckboxFilter component and export:
- `src/components/CheckboxFilter/CheckboxFilter.tsx`
- `src/components/CheckboxFilter/index.ts`
- Replaced Paragon’s `CheckboxFilter` usage in License Management tables:
- `src/components/Admin/licenses/LicenseManagementTable/index.jsx`
- `src/components/subscriptions/licenses/LicenseManagementTable/index.jsx`
- Ensured table state initializes with an empty `filters` array where applicable.
```diff
- import {
-   CheckboxFilter, DataTable, …
```
=> fix: implement local CheckboxFilter

src/components/settings/SettingsSSOTab/NewExistingSSOConfigs.jsx
Reverts openedx/frontend-app-admin-portal#1658
=> Revert "fix: sso configuration failed message in admin portal"

src/components/learner-credit-management/data/utils.js
Add courseRunStartDate to tableData transformers
=> fix: Spent Table - start date column

src/components/AdvanceAnalyticsV2.0/charts/TopSkillsChart.jsx, src/components/AdvanceAnalyticsV2.0/tabs/Engagements.jsx, src/components/AdvanceAnalyticsV2.0/tabs/Outcomes.jsx
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-10916
=> [ENT-10916] Move skills modules from engagement to outcomes

src/components/AdvanceAnalyticsV2.0/AnalyticsFilters.jsx, src/components/AdvanceAnalyticsV2.0/AnalyticsPage.jsx, src/components/AdvanceAnalyticsV2.0/charts/CompletionsOverTimeChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/SkillsByLearningHoursChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/TopSkillsByCompletionChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/TopSkillsChart.jsx
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-10874
=> fix: minor improvements for better ux

src/components/AdvanceAnalyticsV2.0/charts/ChartWrapper.jsx, src/components/AdvanceAnalyticsV2.0/charts/CompletionsOverTimeChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/LineChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/SkillsByEnrollmentChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/SkillsByLearningHoursChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/TopSkillsByCompletionChart.jsx, src/components/AdvanceAnalyticsV2.0/charts/TopSkillsChart.jsx, src/components/AdvanceAnalyticsV2.0/data/utils.js, src/components/AdvanceAnalyticsV2.0/tables/AnalyticsTable.jsx, src/components/AdvanceAnalyticsV2.0/tables/LeaderboardTable.jsx, src/components/AdvanceAnalyticsV2.0/tabs/Engagements.jsx
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-10995
=> misc fixes
